#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const PATCH = "pfotentechnik-seo-week2-top20-10.0.1";
const CHECK = process.argv.includes("--check");
const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Eingebettete Ersatzdateien: Der Hotfix ist vollständig selbstständig.
const EMBEDDED_POLAR_MD = Buffer.from(
  "LS0tCnRpdGxlOiAiUEVUTElCUk8gUG9sYXIgV2V0IEZvb2QgRmVlZGVyIgpzbHVnOiAicGV0bGlicm8tcG9sYXItd2V0LWZvb2QtZmVlZGVyIgp0eXBlOiAicHJvZHVjdCIKbGF5b3V0OiAicHJvZHVjdCIKdGVzdFN0YXR1czogImVkaXRvcmlhbC1yZXZpZXciCnByb2R1Y3RTdGF0dXM6ICJhY3RpdmUiCmRlc2NyaXB0aW9uOiAiQWt0aXYgZ2Vrw7xobHRlciBOYXNzZnV0dGVyYXV0b21hdCBtaXQgZHJlaSAyMDAtbWwtRsOkY2hlcm4sIEFwcC1TdGV1ZXJ1bmcsIEVkZWxzdGFobC1TY2hhbGUgdW5kIHplaXRsaWNoIGJlZ3Jlbnp0ZW0gQmF0dGVyaWUtQmFja3VwLiIKcmVjb21tZW5kYXRpb246ICJFaW5lIGRlciBpbnRlcmVzc2FudGVzdGVuIGF1dG9tYXRpc2NoZW4gTmFzc2Z1dHRlcmzDtnN1bmdlbiBmw7xyIEthdHplbiB1bmQga2xlaW5lIEh1bmRlLCB3ZW5uIGFrdGl2ZSBLw7xobHVuZyB1bmQgZHJlaSB2b3JiZXJlaXRldGUgTWFobHplaXRlbiB3aWNodGlnZXIgc2luZCBhbHMgdm9sbHN0w6RuZGlnIG5ldHp1bmFiaMOkbmdpZ2VyIEJldHJpZWIuIgptYW51ZmFjdHVyZXI6CiAga2V5OiAicGV0bGlicm8iCiAgbmFtZTogIlBFVExJQlJPIgogIHNsdWc6ICJwZXRsaWJybyIKY2F0ZWdvcnk6CiAga2V5OiAiZnV0dGVyYXV0b21hdGVuIgogIGxhYmVsOiAiRnV0dGVyYXV0b21hdGVuIgogIHBhdGg6ICIvc21hcnRlLWZ1dHRlcmF1dG9tYXRlbi8iCnByb2R1Y3RVcmw6ICIvcHJvZHVrdC9wZXRsaWJyby1wb2xhci13ZXQtZm9vZC1mZWVkZXIvIgpwdWJsaXNoZWRBdDogIjIwMjYtMDctMTIiCnVwZGF0ZWRBdDogIjIwMjYtMDctMjUiCmF1dGhvcjoKICBuYW1lOiAiUGZvdGVuVGVjaG5payBSZWRha3Rpb24iCiAgcm9sZTogIlJlZGFrdGlvbiIKc2VvOgogIHRpdGxlOiAiUEVUTElCUk8gUG9sYXIgaW0gQ2hlY2s6IGFrdGl2ZSBLw7xobHVuZyBmw7xyIE5hc3NmdXR0ZXIiCiAgZGVzY3JpcHRpb246ICJQRVRMSUJSTyBQb2xhciBQTEFGMTA5IG1pdCBha3RpdmVyIEvDvGhsdW5nLCBkcmVpIDIwMC1tbC1Gw6RjaGVybiwgMiw0LUdIei1XTEFOLCBFZGVsc3RhaGwtU2NoYWxlIHVuZCAxMi1TdHVuZGVuLUF1c2ZhbGxzY2h1dHouIgogIGNhbm9uaWNhbDogIi9wcm9kdWt0L3BldGxpYnJvLXBvbGFyLXdldC1mb29kLWZlZWRlci8iCiAgc2l0ZW1hcDogdHJ1ZQogIHByaW9yaXR5OiAwLjkKaHViOgogIHNlY3Rpb25zOgogICAgLSAicHJvZHVrdGUiCiAgICAtICJmdXR0ZXJhdXRvbWF0ZW4iCnRhZ3M6CiAgLSAia2F0emUiCiAgLSAia2xlaW5lci1odW5kIgogIC0gImFwcCIKICAtICJuYXNzZnV0dGVyIgogIC0gImFrdGl2ZS1rdWVobHVuZyIKICAtICJlZGVsc3RhaGwiCiAgLSAicHJlbWl1bSIKaW1hZ2VzOgogIGhlcm86CiAgICBzcmM6ICIuLi8uLi9hc3NldHMvaW1hZ2VzL3Byb2R1Y3RzL3BldGxpYnJvLXBvbGFyLXdldC1mb29kLWZlZWRlci9oZXJvLndlYnAiCiAgICBhbHQ6ICJQRVRMSUJSTyBQb2xhciBXZXQgRm9vZCBGZWVkZXIgbWl0IGRyZWkgZ2Vrw7xobHRlbiBOYXNzZnV0dGVyZsOkY2hlcm4iCiAgdGh1bWJuYWlsOgogICAgc3JjOiAiLi4vLi4vYXNzZXRzL2ltYWdlcy9wcm9kdWN0cy9wZXRsaWJyby1wb2xhci13ZXQtZm9vZC1mZWVkZXIvdGh1bWJuYWlsLndlYnAiCiAgICBhbHQ6ICJQRVRMSUJSTyBQb2xhciBXZXQgRm9vZCBGZWVkZXIgYWxzIGtvbXBha3RlIFByb2R1a3RhbnNpY2h0IgogIGNvbXBhcmlzb246CiAgICBzcmM6ICIuLi8uLi9hc3NldHMvaW1hZ2VzL3Byb2R1Y3RzL3BldGxpYnJvLXBvbGFyLXdldC1mb29kLWZlZWRlci9jb21wYXJpc29uLndlYnAiCiAgICBhbHQ6ICJQRVRMSUJSTyBQb2xhciBXZXQgRm9vZCBGZWVkZXIgaW0gTmFzc2Z1dHRlcnZlcmdsZWljaCIKICBnYWxsZXJ5OgogICAgLSBzcmM6ICIuLi8uLi9hc3NldHMvaW1hZ2VzL3Byb2R1Y3RzL3BldGxpYnJvLXBvbGFyLXdldC1mb29kLWZlZWRlci9nYWxsZXJ5LTEud2VicCIKICAgICAgYWx0OiAiRHJlaSBFZGVsc3RhaGwtRnV0dGVyZsOkY2hlciBkZXMgUEVUTElCUk8gUG9sYXIiCiAgICAtIHNyYzogIi4uLy4uL2Fzc2V0cy9pbWFnZXMvcHJvZHVjdHMvcGV0bGlicm8tcG9sYXItd2V0LWZvb2QtZmVlZGVyL2dhbGxlcnktMi53ZWJwIgogICAgICBhbHQ6ICJLw7xobGJhc2lzIGRlcyBQRVRMSUJSTyBQb2xhciIKICAgIC0gc3JjOiAiLi4vLi4vYXNzZXRzL2ltYWdlcy9wcm9kdWN0cy9wZXRsaWJyby1wb2xhci13ZXQtZm9vZC1mZWVkZXIvZ2FsbGVyeS0zLndlYnAiCiAgICAgIGFsdDogIlBFVExJQlJPIFBvbGFyIGFuIGVpbmVtIEthdHplbmZ1dHRlcnBsYXR6IgphZmZpbGlhdGU6CiAgcHJvdmlkZXI6ICJhbWF6b24iCiAgbGFiZWw6ICJBa3R1ZWxsZW4gUHJlaXMgcHLDvGZlbiIKICB1cmw6ICJodHRwczovL3d3dy5hbWF6b24uZGUvcz9rPVBFVExJQlJPK1BvbGFyK1dldCtGb29kK0ZlZWRlciIKcmF0aW5nOiA0CnNjb3JlOiA4MApyYXRpbmdzOgogIGFwcDogMy45CiAgcG9ydGlvbmllcnVuZzogNC40CiAgcmVpbmlndW5nOiA0LjMKICB6dXZlcmxhZXNzaWdrZWl0OiA0LjAKICBzaWNoZXJoZWl0OiA0LjQKICBwcmVpc2xlaXN0dW5nOiAzLjcKZGVjaXNpb246CiAgYmVzdEZvcjoKICAgIC0gIkthdHplbiB1bmQga2xlaW5lIEh1bmRlIG1pdCBOYXNzZnV0dGVyIgogICAgLSAiYmlzIHp1IGRyZWkgdm9yYmVyZWl0ZXRlIE1haGx6ZWl0ZW4iCiAgICAtICJha3RpdmUgS8O8aGx1bmcgb2huZSBLw7xobGFra3VzIgogICAgLSAiSGF1c2hhbHRlIG1pdCAyLDQtR0h6LVdMQU4gdW5kIEFwcC1TdGV1ZXJ1bmciCiAgYXR0ZW50aW9uOgogICAgLSAibnVyIGRyZWkgTWFobHplaXRlbiIKICAgIC0gImFrdGl2ZSBLw7xobHVuZyBiZW7DtnRpZ3QgTmV0enN0cm9tIgogICAgLSAiQmF0dGVyaWUtQmFja3VwIHNjaMO8dHp0IGxhdXQgSGVyc3RlbGxlciBkZW4gWmVpdHBsYW4gYmlzIHp1IDEyIFN0dW5kZW47IGZvcnRnZXNldHp0ZSBLw7xobHVuZyBpc3QgZGFiZWkgbmljaHQgYmVsZWd0IgogICAgLSAia2VpbmUgcGh5c2lzY2hlIFRhc3RlIGbDvHIgZWluZSBzcG9udGFuZSBtYW51ZWxsZSBGw7x0dGVydW5nIgogICAgLSAibmljaHQgZsO8ciBSb2hmbGVpc2NoIGVtcGZvaGxlbiIKICAgIC0gIjcyIFN0dW5kZW4gc2luZCBlaW5lIEhlcnN0ZWxsZXJhbmdhYmUgdW50ZXIgZGVmaW5pZXJ0ZW4gQmVkaW5ndW5nZW4sIGtlaW5lIHBhdXNjaGFsZSBIYWx0YmFya2VpdHNnYXJhbnRpZSIKcmV2aWV3OgogIHN1bW1hcnk6ICJEZXIgUG9sYXIgUExBRjEwOSBrb21iaW5pZXJ0IHRoZXJtb2VsZWt0cmlzY2hlIEvDvGhsdW5nIG1pdCBkcmVpIGVpbnplbG4gcGxhbmJhcmVuIDIwMC1tbC1Gw6RjaGVybiB1bmQgZWluZXIgc3DDvGxtYXNjaGluZW5nZWVpZ25ldGVuIEVkZWxzdGFobC1TY2hhbGUuIgogIHZlcmRpY3Q6ICJEZXIgUEVUTElCUk8gUG9sYXIgaXN0IHRlY2huaXNjaCBkZXV0bGljaCDDvGJlcnpldWdlbmRlciBhbHMgZWluIGVpbmZhY2hlciBGYWNoYXV0b21hdCBtaXQgS8O8aGxha2t1cy4gU2VpbmUgR3JlbnplbiBibGVpYmVuIGRpZSB2b2xsc3TDpG5kaWdlIEFiaMOkbmdpZ2tlaXQgZGVyIGFrdGl2ZW4gS8O8aGx1bmcgdm9tIE5ldHpzdHJvbSwgbnVyIGRyZWkgTWFobHplaXRlbiB1bmQgZGllIEFwcC1BYmjDpG5naWdrZWl0IGbDvHIgc3BvbnRhbmUgw5ZmZm51bmdlbi4iCnN0cmVuZ3RoczoKICAtICJha3RpdmUgdGhlcm1vZWxla3RyaXNjaGUgS8O8aGx1bmcgc3RhdHQgS8O8aGxha2t1cyIKICAtICJkcmVpIEbDpGNoZXIgbWl0IGpld2VpbHMgMjAwIG1sIgogIC0gInNww7xsbWFzY2hpbmVuZ2VlaWduZXRlIEVkZWxzdGFobC1GdXR0ZXJzY2hhbGUiCiAgLSAiMiw0LUdIei1XTEFOIHVuZCBBcHAtWmVpdHBsw6RuZSIKICAtICJBbnRpLVBpbmNoLVNlbnNvciBhbSBEZWNrZWwiCiAgLSAibGF1dCBIZXJzdGVsbGVyIGJpcyB6dSAxMiBTdHVuZGVuIFNjaHV0eiBkZXMgRsO8dHRlcnVuZ3NwbGFucyDDvGJlciBkcmVpIEFBLUJhdHRlcmllbiIKICAtICIyNCBNb25hdGUgSGVyc3RlbGxlcmdhcmFudGllIGxhdXQgYWt0dWVsbGVyIGRldXRzY2hlciBQcm9kdWt0c2VpdGUiCndlYWtuZXNzZXM6CiAgLSAiYWt0aXZlIEvDvGhsdW5nIGJlbsO2dGlndCBOZXR6c3Ryb20iCiAgLSAibnVyIGRyZWkgTWFobHplaXRlbiIKICAtICJrZWluZSBwaHlzaXNjaGUgRsO8dHRlcnVuZ3N0YXN0ZSBhbSBHZXLDpHQiCiAgLSAiUm9oZmxlaXNjaCB3aXJkIHZvbSBIZXJzdGVsbGVyIG5pY2h0IGVtcGZvaGxlbiIKICAtICJ2ZXJnbGVpY2hzd2Vpc2UgZ3Jvw58gdW5kIG1pdCAzLDQga2cgc2Nod2VyIgogIC0gIkFwcCB1bmQgQmVudXR6ZXJrb250byBnZWjDtnJlbiB6dW0gQmVkaWVua29uemVwdCIKZXhwZXJpZW5jZToKICBzdW1tYXJ5OiAiQWt0aXZlIEvDvGhsdW5nIGlzdCBrb250cm9sbGllcmJhcmVyIGFscyBlaW5mYWNoZSBLw7xobGFra3VzLiBEaWUgcmVhbGUgRnV0dGVydGVtcGVyYXR1ciBow6RuZ3QgZGVubm9jaCB2b24gUmF1bXRlbXBlcmF0dXIsIEJlZsO8bGx1bmcsIHNhdWJlcmVtIFfDpHJtZcO8YmVyZ2FuZyB1bmQgU3Ryb212ZXJzb3JndW5nIGFiLiIKICBtZXRob2RvbG9neTogIlJlZGFrdGlvbmVsbGUgRWlub3JkbnVuZyBhbmhhbmQgZGVyIGFrdHVlbGxlbiBkZXV0c2NoZW4gdW5kIGludGVybmF0aW9uYWxlbiBQRVRMSUJSTy1Qcm9kdWt0c2VpdGVuIHNvd2llIGRlcyBvZmZpemllbGxlbiBIaWxmZWJlcmVpY2hzOyBrZWluIGVpZ2VuZXIgTGFuZ3plaXQtLCBUZW1wZXJhdHVyLSBvZGVyIFN0cm9tYXVzZmFsbHRlc3QuIgogIG1haW50ZW5hbmNlOiAiRWRlbHN0YWhsLVNjaGFsZSBuYWNoIGplZGVyIE5hc3Nmw7x0dGVydW5nIHJlaW5pZ2VuLiBLw7xobGZsw6RjaGUsIERpY2h0dW5nZW4sIERlY2tlbCB1bmQgRHJlaG1lY2hhbmlzbXVzIGZyZWkgdm9uIEZ1dHRlcnJlc3RlbiwgS29uZGVuc3dhc3NlciB1bmQgRWlzIGhhbHRlbi4iCmFsdGVybmF0aXZlczoKICAtICJjYXQtbWF0ZS1jNTAwIgogIC0gInN1cmVmZWVkLW1pY3JvY2hpcC1wZXQtZmVlZGVyIgogIC0gImNhdC1tYXRlLWMzMDAiCmNvbXBhcmlzb25zOgogIC0gImJlc3RlLWZ1dHRlcmF1dG9tYXRlbi1mdWVyLWthdHplbiIKICAtICJiZXN0ZS1mdXR0ZXJhdXRvbWF0ZW4tZnVlci1odW5kZSIKICAtICJiZXN0ZS1mdXR0ZXJhdXRvbWF0ZW4tZnVlci1uYXNzZnV0dGVyIgpjb21wYXJpc29uRmlsdGVyczoKICBhbmltYWw6IFsiZG9nIiwgImNhdCJdCiAgcGV0U2l6ZTogWyJzbWFsbCJdCiAgZm9vZFR5cGU6IFsid2V0Il0KICBhcHA6IHRydWUKICBjYW1lcmE6IGZhbHNlCiAgYmFja3VwUG93ZXI6IHRydWUKICBhY2Nlc3M6ICJvcGVuIgogIHByaWNlVGllcjogInByZW1pdW0iCnNwZWNzOgogIC0gbGFiZWw6ICJNb2RlbGwiCiAgICB2YWx1ZTogIlBMQUYxMDkiCiAgLSBsYWJlbDogIkZ1dHRlcmFydCIKICAgIHZhbHVlOiAiRG9zZW4tTmFzc2Z1dHRlciwgUG9ydGlvbnNiZXV0ZWwsIGhhbGJmZXN0ZXMgRmV1Y2h0ZnV0dGVyIHVuZCB2ZXJzY2hyZWlidW5nc3BmbGljaHRpZ2VzIERvc2VuZnV0dGVyIgogIC0gbGFiZWw6ICJLYXBheml0w6R0IgogICAgdmFsdWU6ICJkcmVpIEbDpGNoZXIgbWl0IGplIDIwMCBtbCIKICAtIGxhYmVsOiAiS8O8aGx1bmciCiAgICB2YWx1ZTogInRoZXJtb2VsZWt0cmlzY2hlIEFrdGl2a8O8aGx1bmciCiAgLSBsYWJlbDogIkhlcnN0ZWxsZXJhbmdhYmUgenVyIEvDvGhsdW5nIgogICAgdmFsdWU6ICJiZWkgMjUgwrBDIFJhdW10ZW1wZXJhdHVyIHVuZ2Vmw6RociAxMiDCsEMgRnV0dGVydGVtcGVyYXR1cjsgYmlzIHp1IDcyIFN0dW5kZW4gRnJpc2NoZSIKICAtIGxhYmVsOiAiQXBwIgogICAgdmFsdWU6ICJQRVRMSUJSTy1BcHAgZsO8ciBBbmRyb2lkIHVuZCBpT1MgMTMgb2RlciBuZXVlciIKICAtIGxhYmVsOiAiV0xBTiIKICAgIHZhbHVlOiAiMiw0IEdIeiIKICAtIGxhYmVsOiAiTWFudWVsbGUgw5ZmZm51bmciCiAgICB2YWx1ZTogIm51ciDDvGJlciBGZWVkIE5vdyBiZXppZWh1bmdzd2Vpc2UgT3BlbiBOb3cgaW4gZGVyIEFwcDsga2VpbmUgcGh5c2lzY2hlIEbDvHR0ZXJ1bmdzdGFzdGUiCiAgLSBsYWJlbDogIkthbWVyYSIKICAgIHZhbHVlOiAiTmVpbiIKICAtIGxhYmVsOiAiTmFwZiIKICAgIHZhbHVlOiAic3DDvGxtYXNjaGluZW5nZWVpZ25ldGUgRWRlbHN0YWhsLUZ1dHRlcnNjaGFsZSIKICAtIGxhYmVsOiAiUmVpbmlndW5nIgogICAgdmFsdWU6ICJFZGVsc3RhaGwtRnV0dGVydGVpbGUgc3DDvGxtYXNjaGluZW5nZWVpZ25ldDsgQmFzaXMgdm9uIEhhbmQgcmVpbmlnZW4iCiAgLSBsYWJlbDogIlN0cm9tdmVyc29yZ3VuZyIKICAgIHZhbHVlOiAiTmV0enRlaWwgMTIgVi81IEEiCiAgLSBsYWJlbDogIkJhdHRlcmllLUJhY2t1cCIKICAgIHZhbHVlOiAiZHJlaSBBQS1CYXR0ZXJpZW47IGxhdXQgSGVyc3RlbGxlciBiaXMgenUgMTIgU3R1bmRlbiBTY2h1dHogZGVzIEbDvHR0ZXJ1bmdzcGxhbnMiCiAgLSBsYWJlbDogIkFibWVzc3VuZ2VuIgogICAgdmFsdWU6ICIzNjEgw5cgMzQwIMOXIDE5NiBtbSIKICAtIGxhYmVsOiAiR2V3aWNodCIKICAgIHZhbHVlOiAiMyw0IGtnIG9obmUgTmV0enRlaWwiCiAgLSBsYWJlbDogIkdlZWlnbmV0IGbDvHIiCiAgICB2YWx1ZTogIkthdHplbiB1bmQga2xlaW5lIEh1bmRlIgpmYXE6CiAgLSBxdWVzdGlvbjogIldpZSBsYW5nZSBrw7xobHQgZGVyIFBFVExJQlJPIFBvbGFyIE5hc3NmdXR0ZXI/IgogICAgYW5zd2VyOiAiUEVUTElCUk8gbmVubnQgYmlzIHp1IDcyIFN0dW5kZW4uIERhcyBpc3QgZWluZSBIZXJzdGVsbGVyYW5nYWJlIHVudGVyIGRlZmluaWVydGVuIEJlZGluZ3VuZ2VuIHVuZCBrZWluZSBwYXVzY2hhbGUgSGFsdGJhcmtlaXRzZ2FyYW50aWUgZsO8ciBqZWRlcyBGdXR0ZXIgdW5kIGplZGUgUmF1bXRlbXBlcmF0dXIuIgogIC0gcXVlc3Rpb246ICJXZWxjaGUgVGVtcGVyYXR1ciBlcnJlaWNodCBkZXIgUEVUTElCUk8gUG9sYXI/IgogICAgYW5zd2VyOiAiUEVUTElCUk8gbmVubnQgYXVzIExhYm9ydGVzdHMgYmVpIDI1IMKwQyBSYXVtdGVtcGVyYXR1ciB1bmdlZsOkaHIgMTIgwrBDIEZ1dHRlcnRlbXBlcmF0dXIuIFZvciBkZXIgQXVzZ2FiZSB3aXJkIGRpZSBLw7xobHVuZyB6ZWl0d2Vpc2UgcGF1c2llcnQuIgogIC0gcXVlc3Rpb246ICJCcmF1Y2h0IGRlciBQRVRMSUJSTyBQb2xhciBLw7xobGFra3VzPyIKICAgIGFuc3dlcjogIk5laW4uIERhcyBHZXLDpHQgbnV0enQgZWluZSB0aGVybW9lbGVrdHJpc2NoZSBBa3RpdmvDvGhsdW5nLiIKICAtIHF1ZXN0aW9uOiAiV2llIHZpZWxlIE1haGx6ZWl0ZW4gcGFzc2VuIGhpbmVpbj8iCiAgICBhbnN3ZXI6ICJEcmVpIEbDpGNoZXIgbWl0IGpld2VpbHMgYmlzIHp1IDIwMCBtbC4iCiAgLSBxdWVzdGlvbjogIkZ1bmt0aW9uaWVydCBkZXIgUG9sYXIgYmVpIFN0cm9tYXVzZmFsbD8iCiAgICBhbnN3ZXI6ICJEcmVpIEFBLUJhdHRlcmllbiBzb2xsZW4gbGF1dCBQRVRMSUJSTyBkZW4gRsO8dHRlcnVuZ3NwbGFuIGJpcyB6dSB6d8O2bGYgU3R1bmRlbiB3ZWl0ZXJmw7xocmVuLiBEYXNzIGRpZSBha3RpdmUgS8O8aGx1bmcgZGFiZWkgd2VpdGVybMOkdWZ0LCBpc3QgbmljaHQgYmVsZWd0LiIKICAtIHF1ZXN0aW9uOiAiS2FubiBpY2ggZGVuIFBvbGFyIG9obmUgQXBwIMO2ZmZuZW4/IgogICAgYW5zd2VyOiAiRWluZSBwaHlzaXNjaGUgRsO8dHRlcnVuZ3N0YXN0ZSBiZXNpdHp0IGRhcyBHZXLDpHQgbmljaHQuIFNwb250YW5lIMOWZmZudW5nZW4gd2VyZGVuIGxhdXQgUEVUTElCUk8gw7xiZXIgRmVlZCBOb3cgb2RlciBPcGVuIE5vdyBpbiBkZXIgQXBwIGF1c2dlbMO2c3QuIgogIC0gcXVlc3Rpb246ICJJc3QgUm9oZmxlaXNjaCBnZWVpZ25ldD8iCiAgICBhbnN3ZXI6ICJOZWluLiBQRVRMSUJSTyBlbXBmaWVobHQgZGFzIEdlcsOkdCB3ZWdlbiBkZXIgdW50ZXJzY2hpZWRsaWNoZW4gVmVyZGVyYmxpY2hrZWl0IG5pY2h0IGbDvHIgUm9oZmxlaXNjaC4iCiAgLSBxdWVzdGlvbjogIklzdCBkaWUgU2NoYWxlIHNww7xsbWFzY2hpbmVuZ2VlaWduZXQ/IgogICAgYW5zd2VyOiAiRGllIGFrdHVlbGxlIGRldXRzY2hlIFByb2R1a3RzZWl0ZSBuZW5udCBzcMO8bG1hc2NoaW5lbmdlZWlnbmV0ZSBFZGVsc3RhaGwtRnV0dGVydGVpbGUuIERpZSBlbGVrdHJpc2NoZSBCYXNpcyBkYXJmIG5pY2h0IGluIGRpZSBTcMO8bG1hc2NoaW5lLiIKdXNlQ2FzZTogIkbDvHIgS2F0emVuIHVuZCBrbGVpbmUgSHVuZGUgbWl0IHZvcmJlcmVpdGV0ZW4gTmFzc2Z1dHRlcnBvcnRpb25lbiIKY2FwYWNpdHk6ICJEcmVpIE1haGx6ZWl0ZW4gw6AgMjAwIG1sIgpleHBhbmRhYmxlOiAiTmljaHQgdm9yZ2VzZWhlbiIKZmVhdHVyZXM6CiAgLSAiYWt0aXZlIHRoZXJtb2VsZWt0cmlzY2hlIEvDvGhsdW5nIgogIC0gIkFwcC1TdGV1ZXJ1bmcgw7xiZXIgMiw0LUdIei1XTEFOIgogIC0gImRyZWkgRWRlbHN0YWhsLUbDpGNoZXIiCiAgLSAiQW50aS1QaW5jaC1TZW5zb3IiCiAgLSAiemVpdGxpY2ggYmVncmVuenRlciBBdXNmYWxsc2NodXR6IMO8YmVyIGRyZWkgQUEtQmF0dGVyaWVuIgpjb21wYXJpc29uRGF0YToKICB2ZXJzaW9uOiAxCiAgZ2VuZXJhbDoKICAgIGFuaW1hbDoKICAgICAgLSAiZG9nIgogICAgICAtICJjYXQiCiAgICBwZXRTaXplOgogICAgICAtICJzbWFsbCIKICAgIGZvb2RUeXBlOgogICAgICAtICJ3ZXQiCiAgZWRpdG9yaWFsOgogICAgcmF0aW5nOiA0CiAgICBzY29yZTogODAKICAgIHByb2R1Y3RTdGF0dXM6ICJhY3RpdmUiCiAgY3VzdG9tOgogICAga3VlaGxwcmluemlwOiAiVGhlcm1vZWxla3RyaXNjaGUgQWt0aXZrw7xobHVuZyIKICAgIG1haGx6ZWl0ZW46ICIzIEbDpGNoZXIgbWl0IGplIDIwMCBtbCIKICAgIHN0ZXVlcnVuZzogIlBFVExJQlJPLUFwcDsgMiw0LUdIei1XTEFOIgogICAgc3Ryb212ZXJzb3JndW5nOiAiTmV0emJldHJpZWI7IGRyZWkgQUEtQmF0dGVyaWVuIHNjaMO8dHplbiBsYXV0IEhlcnN0ZWxsZXIgZGVuIFplaXRwbGFuIGJpcyB6dSAxMiBTdHVuZGVuIgogICAgaHlnaWVuZTogIlNww7xsbWFzY2hpbmVuZ2VlaWduZXRlIEVkZWxzdGFobC1GdXR0ZXJzY2hhbGUiCiAgICB0aWVydHJlbm51bmc6ICJOZWluIgogICAgZ2VlaWduZXRmdWVyOiAiS2F0emVuIHVuZCBrbGVpbmUgSHVuZGUiCiAgICB3aWNodGlnc3RlZ3JlbnplOiAiTnVyIGRyZWkgTWFobHplaXRlbjsgYWt0aXZlIEvDvGhsdW5nIGJsZWlidCB2b20gTmV0enN0cm9tIGFiaMOkbmdpZyIKLS0tCgpEZXIgKipQRVRMSUJSTyBQb2xhciBXZXQgRm9vZCBGZWVkZXIgUExBRjEwOSoqIGdlaMO2cnQgenUgZGVuIHdlbmlnZW4gTmFzc2Z1dHRlcmF1dG9tYXRlbiBtaXQgYWt0aXZlciBLw7xobHVuZy4gRHJlaSB2b3JiZXJlaXRldGUgUG9ydGlvbmVuIHdlcmRlbiBuaWNodCBudXIgbWl0IEvDvGhsYWtrdXMgdGVtcGVyaWVydCwgc29uZGVybiDDvGJlciBlaW4gdGhlcm1vZWxla3RyaXNjaGVzIFN5c3RlbSBnZWvDvGhsdC4KCiMjIEt1cnp1cnRlaWwKCkRlciBQb2xhciBpc3QgYmVzb25kZXJzIGludGVyZXNzYW50LCB3ZW5uIGR1OgoKLSBiaXMgenUgZHJlaSBOYXNzZnV0dGVybWFobHplaXRlbiB2b3JiZXJlaXRlbiBtw7ZjaHRlc3QsCi0ga2VpbmUgS8O8aGxha2t1cyBlaW5mcmllcmVuIHdpbGxzdCwKLSBBcHAtWmVpdHBsw6RuZSBha3plcHRpZXJzdCwKLSBkYXMgR2Vyw6R0IGRhdWVyaGFmdCBhbSBOZXR6IGJldHJlaWJlbiBrYW5uc3QuCgpXZW5pZ2VyIHBhc3NlbmQgaXN0IGVyLCB3ZW5uIG1laHIgYWxzIGRyZWkgTWFobHplaXRlbiwgdm9sbHN0w6RuZGlnZXIgT2ZmbGluZS1CZXRyaWViIG9kZXIgUm9oZsO8dHRlcnVuZyBlcmZvcmRlcmxpY2ggc2luZC4KCiMjIEvDvGhsdW5nIHJlYWxpc3Rpc2NoIGVpbm9yZG5lbgoKUEVUTElCUk8gbmVubnQgYmVpIDI1IMKwQyBSYXVtdGVtcGVyYXR1ciB1bmdlZsOkaHIgMTIgwrBDIEZ1dHRlcnRlbXBlcmF0dXIgdW5kIGJpcyB6dSA3MiBTdHVuZGVuIEZyaXNjaGUuIERpZXNlIFdlcnRlIHNpbmQgSGVyc3RlbGxlcmFuZ2FiZW4uIEZ1dHRlcmFydCwgQXVzZ2FuZ3N0ZW1wZXJhdHVyLCBSYXVta2xpbWEsIEJlZsO8bGx1bmcgdW5kIFNhdWJlcmtlaXQgZGVyIEvDvGhsZmzDpGNoZSBiZWVpbmZsdXNzZW4gZGVuIHJlYWxlbiBWZXJsYXVmLgoKRGllIEvDvGhsdW5nIHdpcmQgdm9yIGVpbmVyIGdlcGxhbnRlbiBBdXNnYWJlIHplaXR3ZWlzZSBwYXVzaWVydCwgZGFtaXQgZGllIE1haGx6ZWl0IG5pY2h0IHp1IGthbHQgYW5nZWJvdGVuIHdpcmQuIE5hY2ggZGVtIFBsYW4gYmxlaWJ0IGRpZSBLw7xobGZ1bmt0aW9uIGxhdXQgSGVyc3RlbGxlciBha3RpdjsgUmVzdGUgc29sbHRlbiB0cm90emRlbSB6ZWl0bmFoIGVudGZlcm50IHdlcmRlbi4KCiMjIFN0cm9tYXVzZmFsbDogWmVpdHBsYW4gamEsIEvDvGhsdW5nIG5pY2h0IGJlbGVndAoKRHJlaSBBQS1CYXR0ZXJpZW4gc29sbGVuIGRlbiBnZXNwZWljaGVydGVuIEbDvHR0ZXJ1bmdzcGxhbiBiaXMgenUgenfDtmxmIFN0dW5kZW4gd2VpdGVyZsO8aHJlbi4gRGllIGFrdHVlbGxlIEhlcnN0ZWxsZXJkYXJzdGVsbHVuZyBiZWxlZ3QgamVkb2NoIG5pY2h0LCBkYXNzIGF1Y2ggZGllIGFrdGl2ZSBLw7xobHVuZyBpbSBCYXR0ZXJpZWJldHJpZWIgZXJoYWx0ZW4gYmxlaWJ0LgoKRGVyIEF1c2ZhbGxzY2h1dHogaXN0IGRlc2hhbGIga2VpbiBFcnNhdHogZsO8cjoKCi0gS29udHJvbGxlIGRlciBSYXVtdGVtcGVyYXR1ciwKLSBQcsO8ZnVuZyBkZXMgRnV0dGVycyBuYWNoIGzDpG5nZXJlbiBBdXNmw6RsbGVuLAotIGVpbmUgZXJyZWljaGJhcmUgQmV0cmV1dW5nc3BlcnNvbiwKLSBlaW5lbiBtYW51ZWxsZW4gTm90ZmFsbHBsYW4uCgojIyBCZWRpZW51bmcgdW5kIEFwcC1BYmjDpG5naWdrZWl0CgpaZWl0cGzDpG5lIHVuZCBzcG9udGFuZSDDlmZmbnVuZ2VuIHdlcmRlbiDDvGJlciBkaWUgUEVUTElCUk8tQXBwIGdlc3RldWVydC4gRWluZSBwaHlzaXNjaGUgRsO8dHRlcnVuZ3N0YXN0ZSBhbSBHZXLDpHQgZ2lidCBlcyBsYXV0IEhpbGZlYmVyZWljaCBuaWNodC4KCkRhcyBpc3Qga29tZm9ydGFiZWwsIHNvbGFuZ2UgS29udG8sIEFwcCB1bmQgVmVyYmluZHVuZyBmdW5rdGlvbmllcmVuLiBWb3IgbMOkbmdlcmVyIEFid2VzZW5oZWl0IHNvbGx0ZW4gWmVpdHBsYW4sIFdMQU4tQXVzZmFsbCwgU3Ryb211bnRlcmJyZWNodW5nIHVuZCBCYXR0ZXJpZXdlY2hzZWwgdW50ZXIgQXVmc2ljaHQgZ2V0ZXN0ZXQgd2VyZGVuLgoKIyMgUmVpbmlndW5nCgpEaWUgYWt0dWVsbGUgZGV1dHNjaGUgUHJvZHVrdHNlaXRlIG5lbm50IHNww7xsbWFzY2hpbmVuZ2VlaWduZXRlIEVkZWxzdGFobC1GdXR0ZXJ0ZWlsZS4gRGllIGVsZWt0cmlzY2hlIEJhc2lzLCBLw7xobGZsw6RjaGUgdW5kIE1lY2hhbmlrIHdlcmRlbiB2b24gSGFuZCBnZXJlaW5pZ3QuCgpOYWNoIGplZGVyIEJlZsO8bGx1bmdzcnVuZGUgc29sbHRlbiBrb250cm9sbGllcnQgd2VyZGVuOgoKLSBGdXR0ZXJzY2hhbGUgdW5kIERlY2tlbHJhbmQsCi0gRHJlaG1lY2hhbmlzbXVzLAotIEvDvGhsZmzDpGNoZSB1bmQgS29uZGVuc3dhc3NlciwKLSBEaWNodHVuZ2VuIHVuZCBBbnRpLVBpbmNoLUJlcmVpY2gsCi0gbcO2Z2xpY2hlIEVpc2JpbGR1bmcuCgojIyBGw7xyIHdlbiBpc3QgZGVyIFBvbGFyIGdlZWlnbmV0PwoKfCBTaXR1YXRpb24gfCBFaW5vcmRudW5nIHwKfC0tLXwtLS18CnwgS2F0emUgbWl0IGRyZWkgdm9yYmVyZWl0ZXRlbiBOYXNzZnV0dGVybWFobHplaXRlbiB8IHNlaHIgcGFzc2VuZCB8Cnwga2xlaW5lciBIdW5kIG1pdCBrb250cm9sbGllcnRlbiBGZXVjaHRmdXR0ZXJwb3J0aW9uZW4gfCBncnVuZHPDpHR6bGljaCBwYXNzZW5kIHwKfCBSb2hmw7x0dGVydW5nIHwgdm9tIEhlcnN0ZWxsZXIgbmljaHQgZW1wZm9obGVuIHwKfCBtZWhyIGFscyBkcmVpIE1haGx6ZWl0ZW4gfCB6dSBnZXJpbmdlIEZhY2h6YWhsIHwKfCBIYXVzaGFsdCBvaG5lIHN0YWJpbGVzIFdMQU4gfCBlaW5nZXNjaHLDpG5rdCB8CnwgbMOkbmdlcmVyIFN0cm9tYXVzZmFsbCB8IEvDvGhsdW5nIG5pY2h0IGJlbGFzdGJhciBhYmdlc2ljaGVydCB8CgojIyBNZXRob2RpayB1bmQgUXVlbGxlbgoKRGllIEVpbm9yZG51bmcgYmFzaWVydCBhdWYgYWt0dWVsbGVuIFBFVExJQlJPLVVudGVybGFnZW47IGVpbiBlaWdlbmVyIExhbmd6ZWl0LSBvZGVyIFRlbXBlcmF0dXJ0ZXN0IGxpZWd0IG5pY2h0IHZvci4KCi0gW1BFVExJQlJPIERldXRzY2hsYW5kOiBQb2xhciBOYXNzZnV0dGVyYXV0b21hdF0oaHR0cHM6Ly9kZS5wZXRsaWJyby5jb20vcHJvZHVjdHMvcG9sYXItd2V0LWZvb2QtcGV0LWZlZWRlcikKLSBbUEVUTElCUk86IFBvbGFyIFdldCBGb29kIEZlZWRlciBQTEFGMTA5XShodHRwczovL3BldGxpYnJvLmNvbS9wcm9kdWN0cy9wb2xhci1zbWFydC13ZXQtZm9vZC1mZWVkZXItZm9yLXBldHMpCi0gW1BFVExJQlJPIEhpbGZlYmVyZWljaDogUG9sYXIgU21hcnQgV2V0IEZvb2QgRmVlZGVyXShodHRwczovL3BldGxpYnJvLmNvbS9wYWdlcy9mYXEtcHJvZHVjdC9wb2xhci1zbWFydC13ZXQtZm9vZC1mZWVkZXIpCi0gW1BFVExJQlJPOiBNYW51ZWxsZSDDlmZmbnVuZyBkZXMgUG9sYXJdKGh0dHBzOi8vcGV0bGlicm8uY29tL3BhZ2VzL2hvdy1jb3VsZC1pLW1hbnVhbGx5LWZlZWQtbXktcGV0LWlzLXRoZXJlLWFueS1mZWVkaW5nLWJ1dHRvbi1vbi10aGUtcG9sYXItd2V0LWZvb2QtZmVlZGVyKQoKIyMgRmF6aXQKCkRlciBQRVRMSUJSTyBQb2xhciBpc3QgZWluZSB0ZWNobmlzY2ggc3RhcmtlIEzDtnN1bmcgZsO8ciBkcmVpIHZvcmJlcmVpdGV0ZSBOYXNzZnV0dGVycG9ydGlvbmVuLiBBa3RpdmUgS8O8aGx1bmcsIEVkZWxzdGFobC1TY2hhbGUgdW5kIEFwcC1aZWl0cGzDpG5lIHNpbmQga2xhcmUgVm9ydGVpbGUuIERpZSB3aWNodGlnc3RlbiBHcmVuemVuIHNpbmQgZGllIGdlcmluZ2UgRmFjaHphaGwsIGRpZSBBcHAtQWJow6RuZ2lna2VpdCB1bmQgZGllIFRhdHNhY2hlLCBkYXNzIGRhcyBCYXR0ZXJpZS1CYWNrdXAgZGVuIFplaXRwbGFuLCBhYmVyIG5pY2h0IG5hY2h3ZWlzbGljaCBkaWUgS8O8aGx1bmcgc2Now7x0enQuCg==",
  "base64"
).toString("utf8");

const EMBEDDED_DOG_FOUNTAINS_MD = Buffer.from(
  "LS0tCnRpdGxlOiAiQmVzdGUgVHJpbmticnVubmVuIGbDvHIgSHVuZGUiCnNsdWc6ICJiZXN0ZS10cmlua2JydW5uZW4tZnVlci1odW5kZSIKdHlwZTogImNvbXBhcmlzb24iCmxheW91dDogImNvbXBhcmlzb24iCmRlc2NyaXB0aW9uOiAiU2VjaHMgVHJpbmticnVubmVuIGbDvHIgSHVuZGUgbmFjaCBLYXBheml0w6R0LCBUcmlua2Zsw6RjaGUsIE1hdGVyaWFsLCBSZWluaWd1bmcsIEZpbHRlciB1bmQgU3Ryb212ZXJzb3JndW5nIHZlcmdsZWljaGVuLiIKcHVibGlzaGVkQXQ6ICIyMDI2LTA3LTI0Igp1cGRhdGVkQXQ6ICIyMDI2LTA3LTI1IgphdXRob3I6CiAgbmFtZTogIlBmb3RlblRlY2huaWsgUmVkYWt0aW9uIgogIHJvbGU6ICJSZWRha3Rpb24iCnRhZ3M6CiAgLSAiVHJpbmticnVubmVuIgogIC0gIkh1bmQiCiAgLSAiVmVyZ2xlaWNoIgogIC0gIkthdWZiZXJhdHVuZyIKICAtICJHcm/Dn2UgSHVuZGUiCmh1YjoKICBzZWN0aW9uczoKICAgIC0gInZlcmdsZWljaGUiCiAgICAtICJ0cmlua2JydW5uZW4iCiAgdGl0bGU6ICJCZXN0ZSBUcmlua2JydW5uZW4gZsO8ciBIdW5kZSIKICBkZXNjcmlwdGlvbjogIlNlY2hzIE1vZGVsbGUgZsO8ciBrbGVpbmUsIG1pdHRlbGdyb8OfZSB1bmQgZ3Jvw59lIEh1bmRlIG5hY2ggUmVzZXJ2ZSwgVHJpbmtmbMOkY2hlIHVuZCBSZWluaWd1bmcuIgogIGljb246ICLwn5CVIgogIGZlYXR1cmVkOiB0cnVlCiAgb3JkZXI6IDIxCnNlbzoKICB0aXRsZTogIlRyaW5rYnJ1bm5lbiBmw7xyIEh1bmRlOiA2IE1vZGVsbGUgaW0gVmVyZ2xlaWNoIDIwMjYiCiAgZGVzY3JpcHRpb246ICJTZWNocyBIdW5kZXRyaW5rYnJ1bm5lbiB2ZXJnbGVpY2hlbjogZ3Jvw59lIFRhbmtzLCBrYWJlbGxvc2UgTW9kZWxsZSwgRWRlbHN0YWhsLCBSZWluaWd1bmcsIEZpbHRlciB1bmQgcGFzc2VuZGUgQmF1Zm9ybSBmw7xyIGtsZWluZSBiaXMgZ3Jvw59lIEh1bmRlLiIKICBjYW5vbmljYWw6ICIvdmVyZ2xlaWNoZS9iZXN0ZS10cmlua2JydW5uZW4tZnVlci1odW5kZS8iCiAgc2l0ZW1hcDogdHJ1ZQogIHByaW9yaXR5OiAwLjkKICBjaGFuZ2VmcmVxOiAibW9udGhseSIKY29tcGFyaXNvblR5cGU6ICJ1c2UtY2FzZSIKZ3JvdXA6ICJUcmlua2JydW5uZW4iCmljb246ICLwn5CVIgppdGVtczoKICAtIHNsdWc6ICJvbmVpc2FsbC03bC1kb2ctd2F0ZXItZm91bnRhaW4iCiAgICBsYWJlbDogIm9uZWlzYWxsIDdMIERvZyBXYXRlciBGb3VudGFpbiIKICAgIHR5cGU6ICJwcm9kdWN0IgogICAgcmVjb21tZW5kYXRpb246ICJCZXN0ZSBHZXNhbXRvcHRpb24gZsO8ciBncm/Dn2UgSHVuZGUgdW5kIE1laHJodW5kZWhhdXNoYWx0ZSwgd2VubiBzaWViZW4gTGl0ZXIgUmVzZXJ2ZSB1bmQgZWluZSBicmVpdGUgVHJpbmtmbMOkY2hlIHdpY2h0aWdlciBzaW5kIGFscyBBa2t1IG9kZXIgQXBwLiIKICAgIHZhbHVlczoKICAgICAga2FwYXppdGFldDogIjcgTGl0ZXIiCiAgICAgIG1hdGVyaWFsOiAiVHJpbmtzY2hhbGUgYXVzIEVkZWxzdGFobCAzMDQ7IFRhbmsgdGVpbHdlaXNlIEt1bnN0c3RvZmYiCiAgICAgIGxhdXRzdGFlcmtlOiAiSGVyc3RlbGxlcmFuZ2FiZSB1bmdlZsOkaHIgMzUgZEIiCiAgICAgIGZpbHRlcjogIk1laHJzdHVmaWdlIEZpbHRlcnBhdHJvbmUgcGx1cyBQdW1wZW5zY2h3YW1tIgogICAgICByZWluaWd1bmc6ICJNaW5kZXN0ZW5zIHfDtmNoZW50bGljaDsgUHVtcGUgdW5kIEZpbHRlcmthbW1lciBzZXBhcmF0IgogICAgICBzdHJvbXZlcnNvcmd1bmc6ICJOZXR6YmV0cmllYiwgREMgNSBWLzEgQSIKICAgICAgZWlnbnVuZzogIk1pdHRlbGdyb8OfZSB1bmQgZ3Jvw59lIEh1bmRlOyBNZWhyaHVuZGVoYXVzaGFsdGUiCiAgLSBzbHVnOiAicGV0bGlicm8tY2Fwc3VsZS1kb2ctZm91bnRhaW4iCiAgICBsYWJlbDogIlBFVExJQlJPIENhcHN1bGUgRG9nIEZvdW50YWluIgogICAgdHlwZTogInByb2R1Y3QiCiAgICByZWNvbW1lbmRhdGlvbjogIlN0YXJrZSBHcm/Dn3RhbmstQWx0ZXJuYXRpdmUgZsO8ciBtaXR0ZWxncm/Dn2UgdW5kIGdyb8OfZSBIdW5kZSwgd2VubiBrbmFwcCBhY2h0IExpdGVyIFJlc2VydmUsIGJyZWl0ZSBUcmlua2Zsw6RjaGUgdW5kIFNwcml0enNjaHV0eiBpbSBNaXR0ZWxwdW5rdCBzdGVoZW4uIgogICAgdmFsdWVzOgogICAgICBrYXBheml0YWV0OiAiS25hcHAgOCBMaXRlciIKICAgICAgbWF0ZXJpYWw6ICJCcmVpdGUgVHJpbmtmbMOkY2hlOyBNYXRlcmlhbG1peCBsYXV0IFByb2R1a3RkYXRlbiIKICAgICAgbGF1dHN0YWVya2U6ICJLZWluZSBiZWxhc3RiYXJlIEhlcnN0ZWxsZXJhbmdhYmUiCiAgICAgIGZpbHRlcjogIk1vZGVsbGdlYnVuZGVuZXIgRmlsdGVyIgogICAgICByZWluaWd1bmc6ICJHcm/Dn2VyIFRhbms7IFB1bXBlbi0gdW5kIFJhbmRiZXJlaWNoZSBzZXBhcmF0IHJlaW5pZ2VuIgogICAgICBzdHJvbXZlcnNvcmd1bmc6ICJOZXR6YmV0cmllYiIKICAgICAgZWlnbnVuZzogIk1pdHRlbGdyb8OfZSB1bmQgZ3Jvw59lIEh1bmRlIgogIC0gc2x1ZzogIm9uZWlzYWxsLTMtNWwtY29yZGxlc3MtZm91bnRhaW4iCiAgICBsYWJlbDogIm9uZWlzYWxsIDMsNUwgQ29yZGxlc3MgRm91bnRhaW4iCiAgICB0eXBlOiAicHJvZHVjdCIKICAgIHJlY29tbWVuZGF0aW9uOiAiQmVzdGUga2FiZWxsb3NlIE9wdGlvbiBmw7xyIGtsZWluZSBiaXMgbWl0dGVsZ3Jvw59lIEh1bmRlLCB3ZW5uIGZsZXhpYmxlIEF1ZnN0ZWxsdW5nLCBFZGVsc3RhaGwtVHJpbmtmbMOkY2hlIHVuZCBncm/Dn2UgQWtrdXJlc2VydmUgd2ljaHRpZyBzaW5kLiIKICAgIHZhbHVlczoKICAgICAga2FwYXppdGFldDogIjMsNSBMaXRlciIKICAgICAgbWF0ZXJpYWw6ICJFZGVsc3RhaGwtVHJpbmtmbMOkY2hlIgogICAgICBsYXV0c3RhZXJrZTogIkhlcnN0ZWxsZXJhbmdhYmUgdW50ZXIgMzAgZEIiCiAgICAgIGZpbHRlcjogIkbDvG5mc3R1ZmlnIgogICAgICByZWluaWd1bmc6ICJUYW5rLCBUcmlua2Zsw6RjaGUgdW5kIFB1bXBlIGdldHJlbm50IHJlaW5pZ2VuIgogICAgICBzdHJvbXZlcnNvcmd1bmc6ICI1LjAwMC1tQWgtQWtrdTsgSGVyc3RlbGxlcmFuZ2FiZSBiaXMgenUgNjAgVGFnZSIKICAgICAgZWlnbnVuZzogIktsZWluZSBiaXMgbWl0dGVsZ3Jvw59lIEh1bmRlIgogIC0gc2x1ZzogInBldGtpdC1ldmVyc3dlZXQtbWF4LTItdXZjIgogICAgbGFiZWw6ICJQRVRLSVQgRXZlcnN3ZWV0IE1heCAyIFVWQyIKICAgIHR5cGU6ICJwcm9kdWN0IgogICAgcmVjb21tZW5kYXRpb246ICJQcmVtaXVtb3B0aW9uIGbDvHIga2xlaW5lIEh1bmRlLCB3ZW5uIGthYmVsbG9zZSBBdWZzdGVsbHVuZywgVVZDLVB1bXBlLCBBcHAtU3RhdHVzIHVuZCBzcMO8bG1hc2NoaW5lbmdlZWlnbmV0ZSBUZWlsZSB3aWNodGlnZXIgc2luZCBhbHMgZWluIGdyb8OfZXIgVGFuay4iCiAgICB2YWx1ZXM6CiAgICAgIGthcGF6aXRhZXQ6ICIzIExpdGVyIgogICAgICBtYXRlcmlhbDogIkVkZWxzdGFobC1Ucmlua2Zsw6RjaGUiCiAgICAgIGxhdXRzdGFlcmtlOiAiS2VpbmUgYmVsYXN0YmFyZSBIZXJzdGVsbGVyYW5nYWJlIgogICAgICBmaWx0ZXI6ICJNb2RlbGxnZWJ1bmRlbmVyIFBFVEtJVC1GaWx0ZXIiCiAgICAgIHJlaW5pZ3VuZzogIkxhdXQgSGVyc3RlbGxlciB2b2xsc3TDpG5kaWcgc3DDvGxtYXNjaGluZW5nZWVpZ25ldGUgV2Fzc2VydGVpbGUiCiAgICAgIHN0cm9tdmVyc29yZ3VuZzogIkFra3UtIHVuZCBOZXR6YmV0cmllYiIKICAgICAgZWlnbnVuZzogIktsZWluZSBIdW5kZSIKICAtIHNsdWc6ICJwZXRsaWJyby1zdGFpbmxlc3Mtc3RlZWwtZm91bnRhaW4iCiAgICBsYWJlbDogIlBFVExJQlJPIFN0YWlubGVzcyBTdGVlbCBGb3VudGFpbiAzTCIKICAgIHR5cGU6ICJwcm9kdWN0IgogICAgcmVjb21tZW5kYXRpb246ICJCZXN0ZSBlaW5mYWNoZSBFZGVsc3RhaGxvcHRpb24gZsO8ciBrbGVpbmUgYmlzIG1pdHRlbGdyb8OfZSBIdW5kZSwgd2VubiBlaW4gc3DDvGxtYXNjaGluZW5nZWVpZ25ldGVyIFRhbmsgd2ljaHRpZ2VyIGlzdCBhbHMgQXBwIG9kZXIgQWtrdS4iCiAgICB2YWx1ZXM6CiAgICAgIGthcGF6aXRhZXQ6ICIzIExpdGVyIgogICAgICBtYXRlcmlhbDogIlRhbmsgdW5kIFRyaW5rZmzDpGNoZSBhdXMgRWRlbHN0YWhsIDMwNCIKICAgICAgbGF1dHN0YWVya2U6ICJLZWluZSBiZWxhc3RiYXJlIEhlcnN0ZWxsZXJhbmdhYmUiCiAgICAgIGZpbHRlcjogIk1vZGVsbGdlYnVuZGVuZXIgRmlsdGVyIgogICAgICByZWluaWd1bmc6ICJUYW5rIGxhdXQgSGVyc3RlbGxlciBzcMO8bG1hc2NoaW5lbmdlZWlnbmV0IgogICAgICBzdHJvbXZlcnNvcmd1bmc6ICJOZXR6YmV0cmllYiIKICAgICAgZWlnbnVuZzogIktsZWluZSBiaXMgbWl0dGVsZ3Jvw59lIEh1bmRlIgogIC0gc2x1ZzogImNhdC1tYXRlLTMzNS1wZXQtZm91bnRhaW4iCiAgICBsYWJlbDogIkNhdCBNYXRlIFBldCBGb3VudGFpbiAzMzUiCiAgICB0eXBlOiAicHJvZHVjdCIKICAgIHJlY29tbWVuZGF0aW9uOiAiRWluZmFjaGUgT2ZmbGluZS1BbHRlcm5hdGl2ZSBmw7xyIGtsZWluZSBIdW5kZSwgd2VubiBtZWhyZXJlIFRyaW5raMO2aGVuLCBsYW5nZSBLYWJlbHJlaWNod2VpdGUgdW5kIGd1dCB2ZXJmw7xnYmFyZSBFcnNhdHp0ZWlsZSB3aWNodGlnZXIgc2luZCBhbHMgRWRlbHN0YWhsIG9kZXIgQXBwLiIKICAgIHZhbHVlczoKICAgICAga2FwYXppdGFldDogIlJ1bmQgMiBMaXRlciIKICAgICAgbWF0ZXJpYWw6ICJCUEEtIHVuZCBCSFQtZnJlaWVyIEt1bnN0c3RvZmYiCiAgICAgIGxhdXRzdGFlcmtlOiAiS2VpbmUgYmVsYXN0YmFyZSBIZXJzdGVsbGVyYW5nYWJlIgogICAgICBmaWx0ZXI6ICJQb2x5bWVyLUFrdGl2a29obGVmaWx0ZXIiCiAgICAgIHJlaW5pZ3VuZzogIk1vbmF0bGljaCwgYmVpIGhhcnRlbSBXYXNzZXIgaMOkdWZpZ2VyOyBQdW1wZSBzZXBhcmF0IgogICAgICBzdHJvbXZlcnNvcmd1bmc6ICJOaWVkZXJ2b2x0LU5ldHpiZXRyaWViIG1pdCAzLW0tS2FiZWwiCiAgICAgIGVpZ251bmc6ICJLbGVpbmUgSHVuZGUiCmNyaXRlcmlhOgogIC0ga2V5OiAia2FwYXppdGFldCIKICAgIGxhYmVsOiAiS2FwYXppdMOkdCIKICAgIGRlc2NyaXB0aW9uOiAiTnV0emJhcmUgV2Fzc2VycmVzZXJ2ZSBkZXMgQmVow6RsdGVycy4iCiAgICB3ZWlnaHQ6IDEuNQogIC0ga2V5OiAiZWlnbnVuZyIKICAgIGxhYmVsOiAiSHVuZGVncsO2w59lIgogICAgZGVzY3JpcHRpb246ICJCYXVmb3JtLCBUcmlua2jDtmhlLCBUcmlua2Zsw6RjaGUgdW5kIFJlc2VydmUgcGFzc2VuZCB6dW0gRWluc2F0enp3ZWNrLiIKICAgIHdlaWdodDogMS41CiAgLSBrZXk6ICJtYXRlcmlhbCIKICAgIGxhYmVsOiAiTWF0ZXJpYWwiCiAgICBkZXNjcmlwdGlvbjogIk1hdGVyaWFsIHZvbiBUcmlua2Zsw6RjaGUsIFRhbmsgdW5kIHdhc3NlcmbDvGhyZW5kZW4gVGVpbGVuLiIKICAgIHdlaWdodDogMS4yCiAgLSBrZXk6ICJyZWluaWd1bmciCiAgICBsYWJlbDogIlJlaW5pZ3VuZyIKICAgIGRlc2NyaXB0aW9uOiAiWmVybGVnYmFya2VpdCwgUHVtcGVuenVnYW5nIHVuZCBTcMO8bG1hc2NoaW5lbmVpZ251bmcuIgogICAgd2VpZ2h0OiAxLjQKICAtIGtleTogImZpbHRlciIKICAgIGxhYmVsOiAiRmlsdGVyIHVuZCBGb2xnZWtvc3RlbiIKICAgIGRlc2NyaXB0aW9uOiAiRmlsdGVyYXVmYmF1LCBtb2RlbGxnZWJ1bmRlbmUgV2VjaHNlbHRlaWxlIHVuZCBWZXJmw7xnYmFya2VpdC4iCiAgICB3ZWlnaHQ6IDEuMAogIC0ga2V5OiAic3Ryb212ZXJzb3JndW5nIgogICAgbGFiZWw6ICJTdHJvbXZlcnNvcmd1bmciCiAgICBkZXNjcmlwdGlvbjogIk5ldHpiZXRyaWViIG9kZXIgQWtrdSB1bmQgZGllIGRhcmF1cyBmb2xnZW5kZSBQbGF0emllcnVuZ3NmcmVpaGVpdC4iCiAgICB3ZWlnaHQ6IDEuMAogIC0ga2V5OiAibGF1dHN0YWVya2UiCiAgICBsYWJlbDogIkxhdXRzdMOkcmtlIgogICAgZGVzY3JpcHRpb246ICJEb2t1bWVudGllcnRlIEhlcnN0ZWxsZXJhbmdhYmUgb2RlciB0cmFuc3BhcmVudGUgRGF0ZW5sw7xja2UuIgogICAgd2VpZ2h0OiAwLjYKYXV0b21hdGljUmVjb21tZW5kYXRpb25zOgogIGVuYWJsZWQ6IGZhbHNlCnJlY29tbWVuZGF0aW9uOgogIHdpbm5lclNsdWc6ICJvbmVpc2FsbC03bC1kb2ctd2F0ZXItZm91bnRhaW4iCiAgYWx0ZXJuYXRpdmVTbHVnOiAib25laXNhbGwtMy01bC1jb3JkbGVzcy1mb3VudGFpbiIKICB0aXRsZTogIm9uZWlzYWxsIDdMIGbDvHIgZ3Jvw59lIEh1bmRlLCAzLDVMIENvcmRsZXNzIGbDvHIgZmxleGlibGUgQXVmc3RlbGx1bmciCiAgdGV4dDogIkbDvHIgZ3Jvw59lIEh1bmRlIHVuZCBtZWhyZXJlIFRpZXJlIGlzdCBkZXIgb25laXNhbGwgN0wgd2VnZW4gUmVzZXJ2ZSB1bmQgYnJlaXRlciBUcmlua2Zsw6RjaGUgZGllIGF1c2dld29nZW5zdGUgV2FobC4gRsO8ciBrbGVpbmUgYmlzIG1pdHRlbGdyb8OfZSBIdW5kZSBpc3QgZGllIGthYmVsbG9zZSAzLDUtTGl0ZXItVmVyc2lvbiBmbGV4aWJsZXIuIFBFVExJQlJPIENhcHN1bGUgaXN0IGRpZSBHcm/Dn3RhbmstQWx0ZXJuYXRpdmUsIFBFVEtJVCBNYXggMiBVVkMgZGllIHNtYXJ0ZSBQcmVtaXVtb3B0aW9uIGbDvHIga2xlaW5lIEh1bmRlLiIKdGFibGVUaXRsZTogIjYgVHJpbmticnVubmVuIGbDvHIgSHVuZGUgZGlyZWt0IHZlcmdsaWNoZW4iCmNhcmRzVGl0bGU6ICJFbXBmZWhsdW5nZW4gbmFjaCBIdW5kZWdyw7bDn2UgdW5kIEF1ZnN0ZWxsdW5nIgpmYXE6CiAgLSBxdWVzdGlvbjogIldlbGNoZXIgVHJpbmticnVubmVuIGVpZ25ldCBzaWNoIGFtIGJlc3RlbiBmw7xyIGdyb8OfZSBIdW5kZT8iCiAgICBhbnN3ZXI6ICJGw7xyIGdyb8OfZSBIdW5kZSBzaW5kIGVpbmUgYnJlaXRlIFRyaW5rZmzDpGNoZSwgZ3V0ZXIgU3RhbmQgdW5kIGVpbmUgaG9oZSBSZXNlcnZlIHdpY2h0aWdlciBhbHMgQXBwLUZ1bmt0aW9uZW4uIEltIFZlcmdsZWljaCBzaW5kIG9uZWlzYWxsIDdMIHVuZCBQRVRMSUJSTyBDYXBzdWxlIGRpZSBwbGF1c2liZWxzdGVuIEdyb8OfdGFua2zDtnN1bmdlbi4iCiAgLSBxdWVzdGlvbjogIldpZSBncm/DnyBzb2xsdGUgZWluIFRyaW5rYnJ1bm5lbiBmw7xyIGVpbmVuIEh1bmQgc2Vpbj8iCiAgICBhbnN3ZXI6ICJEaWUgcGFzc2VuZGUgR3LDtsOfZSBow6RuZ3Qgdm9uIEvDtnJwZXJnZXdpY2h0LCBUaWVyemFobCwgUmF1bXRlbXBlcmF0dXIgdW5kIFRyaW5rdmVyaGFsdGVuIGFiLiBEZXIgVGFuayBzb2xsdGUgUmVzZXJ2ZW4gYmlldGVuLCBkYXJmIGFiZXIgbmljaHQgZGF6dSBmw7xocmVuLCBkYXNzIFdhc3NlciBzZWx0ZW5lciBnZXdlY2hzZWx0IHdpcmQuIgogIC0gcXVlc3Rpb246ICJJc3QgZWluIDItTGl0ZXItQnJ1bm5lbiBmw7xyIGVpbmVuIGdyb8OfZW4gSHVuZCBhdXNyZWljaGVuZD8iCiAgICBhbnN3ZXI6ICJNZWlzdCBudXIgZWluZ2VzY2hyw6Rua3QuIE5lYmVuIGRlciBnZXJpbmdlbiBSZXNlcnZlIGvDtm5uZW4gVHJpbmtmbMOkY2hlLCBIw7ZoZSB1bmQgU3RhbmRmZXN0aWdrZWl0IHVucGFzc2VuZCBzZWluLiIKICAtIHF1ZXN0aW9uOiAiSXN0IEVkZWxzdGFobCBiZXNzZXIgYWxzIEt1bnN0c3RvZmY/IgogICAgYW5zd2VyOiAiRWRlbHN0YWhsIGlzdCByb2J1c3QgdW5kIGjDpHVmaWcgbGVpY2h0IHp1IHJlaW5pZ2VuLiBFbnRzY2hlaWRlbmQgYmxlaWJlbiB6dWfDpG5nbGljaGUgUHVtcGUsIGdsYXR0ZSBLb250YWt0ZmzDpGNoZW4gdW5kIHZvbGxzdMOkbmRpZyB0cm9ja25lbmRlIEJhdXRlaWxlLiIKICAtIHF1ZXN0aW9uOiAiSXN0IGVpbiBrYWJlbGxvc2VyIFRyaW5rYnJ1bm5lbiBzaW5udm9sbD8iCiAgICBhbnN3ZXI6ICJFciBlcmxlaWNodGVydCBkaWUgUGxhdHppZXJ1bmcgb2huZSBzaWNodGJhcmVzIEthYmVsLiBBa2t1bGF1ZnplaXQgaMOkbmd0IGplZG9jaCBzdGFyayB2b20gQmV0cmllYnNtb2R1cyBhYiB1bmQgZXJzZXR6dCBrZWluZSByZWdlbG3DpMOfaWdlIEtvbnRyb2xsZS4iCiAgLSBxdWVzdGlvbjogIldpZSBvZnQgbXVzcyBlaW4gSHVuZGV0cmlua2JydW5uZW4gZ2VyZWluaWd0IHdlcmRlbj8iCiAgICBhbnN3ZXI6ICJXYXNzZXIgdW5kIHNpY2h0YmFyZSBGbMOkY2hlbiBzb2xsdGVuIGjDpHVmaWcga29udHJvbGxpZXJ0IHdlcmRlbi4gVGFuaywgUHVtcGUsIEZpbHRlcmthbW1lciB1bmQgc2Nod2VyIHp1Z8OkbmdsaWNoZSBCZXJlaWNoZSBiZW7DtnRpZ2VuIGFiaMOkbmdpZyB2b24gTnV0enVuZyB1bmQgV2Fzc2VycXVhbGl0w6R0IG1pbmRlc3RlbnMgd8O2Y2hlbnRsaWNoIGVpbmUgZ3LDvG5kbGljaGUgUHLDvGZ1bmcuIgogIC0gcXVlc3Rpb246ICJXaWUgb2Z0IG11c3MgZGVyIEZpbHRlciBnZXdlY2hzZWx0IHdlcmRlbj8iCiAgICBhbnN3ZXI6ICJEYXMgaMOkbmd0IHZvbiBGaWx0ZXJ0eXAsIFdhc3NlcnF1YWxpdMOkdCB1bmQgVGllcnphaGwgYWIuIEhlcnN0ZWxsZXJpbnRlcnZhbGxlIHNpbmQgT2JlcmdyZW56ZW47IEdlcnVjaCwgQmVsYWcgb2RlciBzaW5rZW5kZXIgRHVyY2hmbHVzcyBlcmZvcmRlcm4gZWluZSBmcsO8aGVyZSBSZWluaWd1bmcgb2RlciBlaW5lbiBXZWNoc2VsLiIKICAtIHF1ZXN0aW9uOiAiU2luZCBUcmlua2JydW5uZW4gZsO8ciBIdW5kZSB3aXJrbGljaCBsZWlzZT8iCiAgICBhbnN3ZXI6ICJHZXLDpHVzY2ggaMOkbmd0IHZvbiBQdW1wZSwgV2Fzc2Vyc3RhbmQsIFVudGVyZ3J1bmQgdW5kIFZlcnNjaG11dHp1bmcgYWIuIEVpbnplbG5lIERlemliZWx3ZXJ0ZSBzaW5kIG51ciBlaW5nZXNjaHLDpG5rdCB2ZXJnbGVpY2hiYXIuIgogIC0gcXVlc3Rpb246ICJCcmF1Y2h0IGVpbiBIdW5kZXRyaW5rYnJ1bm5lbiBlaW5lIEFwcD8iCiAgICBhbnN3ZXI6ICJOZWluLiBBcHAtRXJpbm5lcnVuZ2VuIGvDtm5uZW4gaGVsZmVuLCBhYmVyIFRhbmtncsO2w59lLCBUcmlua2Zsw6RjaGUsIFJlaW5pZ3VuZyB1bmQgRXJzYXR6dGVpbHZlcnNvcmd1bmcgc2luZCB3aWNodGlnZXIuIgogIC0gcXVlc3Rpb246ICJFcnNldHp0IGVpbiBUcmlua2JydW5uZW4gbWVocmVyZSBXYXNzZXJuw6RwZmU/IgogICAgYW5zd2VyOiAiTmVpbi4gRWluZSB6dXPDpHR6bGljaGUgdW5hYmjDpG5naWdlIFdhc3NlcnN0ZWxsZSBpc3QgYmVzb25kZXJzIGJlaSBTdHJvbWF1c2ZhbGwsIFB1bXBlbmZlaGxlcm4sIEhpdHplIG9kZXIgbWVocmVyZW4gVGllcmVuIHNpbm52b2xsLiIKLS0tCgpFaW4gKipUcmlua2JydW5uZW4gZsO8ciBIdW5kZSoqIG11c3MgbWVjaGFuaXNjaCB6dW0gVGllciBwYXNzZW4uIEbDvHIgZWluZW4gZ3Jvw59lbiBIdW5kIGlzdCBlaW4ga29tcGFrdGVyIEthdHplbmJydW5uZW4gbWl0IEFwcCBvZnQgd2VuaWdlciBnZWVpZ25ldCBhbHMgZWluIGVpbmZhY2hlciBncm/Dn2VyIFRhbmsgbWl0IGJyZWl0ZXIgVHJpbmtmbMOkY2hlLgoKIyMgU2NobmVsbGVudHNjaGVpZHVuZwoKLSAqKm9uZWlzYWxsIDdMOioqIHN0w6Rya3N0ZSBHZXNhbXRvcHRpb24gZsO8ciBncm/Dn2UgSHVuZGUgdW5kIE1laHJodW5kZWhhdXNoYWx0ZS4KLSAqKlBFVExJQlJPIENhcHN1bGUgRG9nIEZvdW50YWluOioqIGdyb8OfZSBSZXNlcnZlIHVuZCBicmVpdGUgVHJpbmtmbMOkY2hlIGFscyBBbHRlcm5hdGl2ZS4KLSAqKm9uZWlzYWxsIDMsNUwgQ29yZGxlc3M6KiogZmxleGliZWwgZsO8ciBrbGVpbmUgYmlzIG1pdHRlbGdyb8OfZSBIdW5kZS4KLSAqKlBFVEtJVCBFdmVyc3dlZXQgTWF4IDIgVVZDOioqIHNtYXJ0ZSBQcmVtaXVtb3B0aW9uIGbDvHIga2xlaW5lIEh1bmRlLgotICoqUEVUTElCUk8gU3RhaW5sZXNzIFN0ZWVsIDNMOioqIGVpbmZhY2hlIEVkZWxzdGFobG9wdGlvbiBvaG5lIEFwcC4KLSAqKkNhdCBNYXRlIDMzNToqKiBrb21wYWt0ZSBPZmZsaW5lLUzDtnN1bmcgbWl0IG1laHJlcmVuIFRyaW5raMO2aGVuLgoKIyMgV2VsY2hlIEdyw7bDn2UgcGFzc3Q/Cgp8IEVpbnNhdHogfCBTaW5udm9sbGUgQXVzZ2FuZ3NncsO2w59lIHwgTW9kZWxsZSB8CnwtLS18LS0tOnwtLS18Cnwga2xlaW5lciBIdW5kIHwgZXR3YSAyIGJpcyAzIExpdGVyIHwgQ2F0IE1hdGUgMzM1LCBQRVRLSVQgTWF4IDIgVVZDIHwKfCBrbGVpbmVyIGJpcyBtaXR0ZWxncm/Dn2VyIEh1bmQgfCBldHdhIDMgYmlzIDQgTGl0ZXIgfCBvbmVpc2FsbCAzLDVMLCBQRVRMSUJSTyBFZGVsc3RhaGwgM0wgfAp8IGdyb8OfZXIgSHVuZCB8IG1pbmRlc3RlbnMgZXR3YSA1IExpdGVyIHVuZCBicmVpdGUgRmzDpGNoZSB8IG9uZWlzYWxsIDdMLCBQRVRMSUJSTyBDYXBzdWxlIHwKfCBtZWhyZXJlIEh1bmRlIHwgZ3Jvw59lIFJlc2VydmUgcGx1cyB6dXPDpHR6bGljaGUgV2Fzc2Vyc3RlbGxlIHwgb25laXNhbGwgN0wgb2RlciBDYXBzdWxlIHwKCkRpZXNlIFdlcnRlIHNpbmQga2VpbmUgbWVkaXppbmlzY2hlIEJlZGFyZnNiZXJlY2hudW5nLiBEaWUgdGF0c8OkY2hsaWNoIG7DtnRpZ2UgUmVzZXJ2ZSBow6RuZ3Qgdm9uIFRlbXBlcmF0dXIsIEZ1dHRlciwgQWt0aXZpdMOkdCB1bmQgVGllcnphaGwgYWIuCgojIyBUYW5rdm9sdW1lbiBpc3QgbmljaHQgYWxsZXMKCkVpbiBncm/Dn2VyIFRhbmsga2FubiB0cm90emRlbSB1bmdlZWlnbmV0IHNlaW4sIHdlbm46CgotIGRpZSBUcmlua2Zsw6RjaGUgenUgc2NobWFsIGlzdCwKLSBkZXIgSHVuZCBkZW4gQnJ1bm5lbiBsZWljaHQgdmVyc2NoaWVidCwKLSBSYW5kIG9kZXIgQXVzbGF1ZiBkaWUgU2NobmF1emUgYmVoaW5kZXJuLAotIFB1bXBlIHVuZCBFY2tlbiBzY2h3ZXIgenUgcmVpbmlnZW4gc2luZCwKLSBFcnNhdHpmaWx0ZXIga2F1bSB2ZXJmw7xnYmFyIHNpbmQuCgojIyBSZWluaWd1bmcgdW5kIEh5Z2llbmUKCkVkZWxzdGFobCBlcmxlaWNodGVydCBkaWUgUmVpbmlndW5nLCB2ZXJoaW5kZXJ0IEJpb2ZpbG0gYWJlciBuaWNodC4gQmVzb25kZXJzIHJlbGV2YW50IHNpbmQ6CgotIFB1bXBlbmdlaMOkdXNlIHVuZCBSb3RvciwKLSBLYWJlbGR1cmNoZsO8aHJ1bmcsCi0gRmlsdGVya2FtbWVyLAotIERpY2h0dW5nZW4gdW5kIMOcYmVyZ8OkbmdlLAotIFVudGVyc2VpdGUgZGVyIFRyaW5rZmzDpGNoZSwKLSBzdGVoZW5kZXMgUmVzdHdhc3Nlci4KCkVpbiBGaWx0ZXIgZXJzZXR6dCB3ZWRlciBXYXNzZXJ3ZWNoc2VsIG5vY2ggbWVjaGFuaXNjaGUgUmVpbmlndW5nLgoKIyMgTmV0emJldHJpZWIgb2RlciBBa2t1PwoKTmV0emJldHJpZWIgZWlnbmV0IHNpY2ggZsO8ciBlaW5lbiBmZXN0ZW4gU3RhbmRvcnQuIEVpbiBBa2t1IGVybcO2Z2xpY2h0IGVpbmUgZnJlaWVyZSBQbGF0emllcnVuZywgYXJiZWl0ZXQgamUgbmFjaCBNb2RlbGwgYWJlciBvZnQgaW0gSW50ZXJ2YWxsLSBvZGVyIFNlbnNvcm1vZHVzLgoKVW5hYmjDpG5naWcgdm9uIGRlciBCYXVhcnQgc29sbHRlIGVpbmUgendlaXRlIFdhc3NlcnN0ZWxsZSB2b3JoYW5kZW4gc2Vpbi4gRWluIGxlZXJlciBBa2t1LCBTdHJvbWF1c2ZhbGwgb2RlciBQdW1wZW5zdGF1IGRhcmYgbmljaHQgZGllIGVpbnppZ2UgVmVyc29yZ3VuZyB1bnRlcmJyZWNoZW4uCgojIyBNZXRob2RpawoKRGVyIFZlcmdsZWljaCBwcmlvcmlzaWVydCBIdW5kZWdyw7bDn2UsIG51dHpiYXJlIFRyaW5rZmzDpGNoZSwgS2FwYXppdMOkdCB1bmQgUmVpbmlndW5nIHZvciBBcHAgb2RlciBTb25kZXJmdW5rdGlvbmVuLiBEaWUgc2VjaHMgTW9kZWxsZSB3dXJkZW4gYmV3dXNzdCBrdXJhdGllcnQuIE5pY2h0IGRva3VtZW50aWVydGUgSGVyc3RlbGxlcmFuZ2FiZW4gd2VyZGVuIG5pY2h0IGdlc2Now6R0enQuCgpWZXJ0aWVmZW5kIGhlbGZlbiBbVHJpbmticnVubmVuIGbDvHIgSHVuZGUgdW5kIEthdHplbl0oL3RyaW5rYnJ1bm5lbi8pLCBbVHJpbmticnVubmVuIHJpY2h0aWcgcmVpbmlnZW5dKC90cmlua2JydW5uZW4tcmljaHRpZy1yZWluaWdlbi8pIHVuZCBbV2llIHZpZWwgV2Fzc2VyIGJyYXVjaHQgZWluIEh1bmQ/XSgvd2Fzc2VyYmVkYXJmLWh1bmQvKS4KCiMjIEZheml0CgpGw7xyIGdyb8OfZSBIdW5kZSBpc3QgZGVyIG9uZWlzYWxsIDdMIGRpZSBhdXNnZXdvZ2Vuc3RlIFdhaGwgaW0gYWt0dWVsbGVuIEJlc3RhbmQuIFBFVExJQlJPIENhcHN1bGUgYmlldGV0IGVpbmUgbm9jaCBncsO2w59lcmUgUmVzZXJ2ZS4gS2xlaW5lIEh1bmRlIHByb2ZpdGllcmVuIGVoZXIgdm9uIGd1dCB6dWfDpG5nbGljaGVuIDItIGJpcyAzLDUtTGl0ZXItTW9kZWxsZW4uIEVudHNjaGVpZGVuZCBzaW5kIG5pY2h0IEFwcCBvZGVyIERlc2lnbiwgc29uZGVybiBUcmlua2Zsw6RjaGUsIFN0YW5kZmVzdGlna2VpdCwgUmVpbmlndW5nIHVuZCBlaW5lIHZlcmzDpHNzbGljaGUgendlaXRlIFdhc3NlcnN0ZWxsZS4K",
  "base64"
).toString("utf8");

function findRepoRoot(start) {
  let current = path.resolve(start);
  for (let i = 0; i < 12; i += 1) {
    if (
      fs.existsSync(path.join(current, "apps", "pfotentechnik")) &&
      fs.existsSync(path.join(current, "package.json"))
    ) return current;
    const parent = path.dirname(current);
    if (parent === current) break;
    current = parent;
  }
  throw new Error("Repository-Root mit apps/pfotentechnik nicht gefunden.");
}

const root = findRepoRoot(process.cwd());
const app = path.join(root, "apps", "pfotentechnik");
const changed = new Map();
const deleted = new Map();

function rel(file) { return path.relative(root, file).replaceAll("\\", "/"); }
function read(file) {
  if (!fs.existsSync(file)) throw new Error(`Datei fehlt: ${rel(file)}`);
  return fs.readFileSync(file, "utf8");
}
function stage(file, content) {
  const normalized = content.replace(/\r\n/g, "\n");
  const old = read(file).replace(/\r\n/g, "\n");
  if (old !== normalized) changed.set(file, { old, next: normalized });
}
function scalar(text, key, value) {
  const rx = new RegExp(`^(\\s*)${key}:.*$`, "m");
  if (!rx.test(text)) throw new Error(`Feld ${key} nicht gefunden.`);
  return text.replace(rx, (_, indent) => `${indent}${key}: ${JSON.stringify(value)}`);
}
function replaceBetween(text, startMarker, endMarker, replacement, label) {
  const start = text.indexOf(startMarker);
  const end = text.indexOf(endMarker, start + startMarker.length);
  if (start < 0 || end < 0) throw new Error(`${label}: Blockgrenzen nicht gefunden.`);
  return text.slice(0, start) + replacement + text.slice(end);
}
function splitFrontmatter(text) {
  const match = text.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) throw new Error("Frontmatter konnte nicht getrennt werden.");
  return { fm: match[1], body: match[2] };
}
function joinFrontmatter(fm, body) {
  return `---\n${fm.trimEnd()}\n---\n\n${body.trim()}\n`;
}
function ensureAfter(text, anchor, insert, label) {
  if (text.includes(insert.trim())) return text;
  const pos = text.indexOf(anchor);
  if (pos < 0) throw new Error(`${label}: Anker nicht gefunden.`);
  return text.slice(0, pos + anchor.length) + insert + text.slice(pos + anchor.length);
}
function ensureCardCta(text, title, href, cta, label) {
  const titleNeedle = `title: "${title}"`;
  const titlePos = text.indexOf(titleNeedle);
  if (titlePos < 0) throw new Error(`${label}: Titel nicht gefunden.`);
  const blockStart = text.lastIndexOf("\n      - ", titlePos);
  const nextCard = text.indexOf("\n      - ", titlePos + titleNeedle.length);
  const nextBlock = text.indexOf("\n  - type:", titlePos + titleNeedle.length);
  const candidates = [nextCard, nextBlock, text.length].filter((value) => value >= 0);
  const blockEnd = Math.min(...candidates);
  const start = blockStart >= 0 ? blockStart : titlePos;
  const block = text.slice(start, blockEnd);
  if (block.includes(`href: "${href}"`)) return text;
  const lines = block.split("\n");
  const textIndex = lines.findIndex((line) => /^\s+text:/.test(line));
  if (textIndex < 0) throw new Error(`${label}: Textzeile im Block nicht gefunden.`);
  const indent = lines[textIndex].match(/^\s*/)?.[0] ?? "";
  lines.splice(textIndex + 1, 0, `${indent}href: "${href}"`, `${indent}cta: "${cta}"`);
  return text.slice(0, start) + lines.join("\n") + text.slice(blockEnd);
}
function replaceRegex(text, rx, replacement, label) {
  if (!rx.test(text)) throw new Error(`${label}: Muster nicht gefunden.`);
  return text.replace(rx, replacement);
}

const files = {
  offline: path.join(app, "src/content/pages/futterautomat-ohne-wlan.md"),
  camera: path.join(app, "src/content/pages/futterautomat-mit-kamera.md"),
  twoCats: path.join(app, "src/content/pages/futterautomat-fuer-zwei-katzen.md"),
  petlibro: path.join(app, "src/content/manufacturers/petlibro.md"),
  hub: path.join(app, "src/content/pages/smarte-futterautomaten.md"),
  polar: path.join(app, "src/content/products/petlibro-polar-wet-food-feeder.md"),
  fountains: path.join(app, "src/content/comparisons/beste-trinkbrunnen-fuer-hunde.md"),
  renderer: path.join(app, "src/pages/produkt/[product].astro"),
  audit: path.join(app, "scripts/seo/audit-week2-top20.mjs")
};

// 1) Vollständige, recherchierte Ersatzdateien
stage(files.polar, EMBEDDED_POLAR_MD);
stage(files.fountains, EMBEDDED_DOG_FOUNTAINS_MD);

// 2) Offline-Ratgeber
{
  let text = read(files.offline);
  text = scalar(text, "seoTitle", "Futterautomat ohne WLAN: ohne App, Cloud und Konto");
  text = scalar(text, "seoDescription", "Futterautomat ohne WLAN auswählen: drei Offline-Konzepte, lokale Zeitpläne, Batteriebetrieb, Datenschutz und direkte Modelle im Vergleich.");
  text = scalar(text, "updatedAt", "2026-07-25");
  text = text.replace(
    /comparisonProducts:\s*\[[^\]]*\]/,
    'comparisonProducts: ["cat-mate-c500", "surefeed-microchip-pet-feeder", "imipaw-3l"]'
  );
  text = text.replace(
    /comparisonHref:\s*\/vergleiche\/beste-futterautomaten\/?/g,
    "comparisonHref: /vergleiche/beste-futterautomaten-ohne-wlan/"
  );
  text = ensureCardCta(
    text,
    "Lokale Zeitsteuerung reicht für viele Routinen",
    "/vergleiche/beste-futterautomaten-ohne-wlan/",
    "Offline-Modelle vergleichen",
    "Offline-Antwort-CTA"
  );
  const extraSection = `
## Drei Offline-Bauarten direkt vergleichen

Der spezialisierte [Vergleich der besten Futterautomaten ohne WLAN](/vergleiche/beste-futterautomaten-ohne-wlan/) trennt drei Konzepte:

- **Cat Mate C500:** vorbereitete Nass- oder Trockenfutterfächer mit lokaler Zeitsteuerung,
- **SureFeed Microchip Pet Feeder:** geschützter Zugang ohne automatische Vorratsdosierung,
- **IMIPAW 3L:** klassischer Trockenfutterautomat mit lokalem Plan.

Die Geräte sind keine direkten Funktionszwillinge. Entscheidend ist zuerst, ob du Zeitsteuerung, Zugangsschutz oder automatische Trockenfutterdosierung benötigst.

`;
  if (!text.includes("## Drei Offline-Bauarten direkt vergleichen")) {
    text = text.replace("## Methodik unserer Einordnung", extraSection + "## Methodik unserer Einordnung");
  }
  const faqBlock = `faq:
  - question: "Ist ein Futterautomat ohne WLAN ausfallsicherer?"
    answer: "Er hat weniger Netzwerkabhängigkeiten, kann aber weiterhin durch leere Batterien, falsche Uhrzeit oder mechanische Blockaden ausfallen. Ausfallsicherheit entsteht durch Tests, regelmäßige Kontrolle und eine passende Stromreserve."
  - question: "Kann ich einen App-Futterautomaten ohne WLAN verwenden?"
    answer: "Das hängt vom Modell ab. Manche Geräte benötigen WLAN nur für Einrichtung und Fernfunktionen, andere setzen ein Konto oder eine Verbindung voraus. Anleitung und Offline-Verhalten sollten vor dem Kauf geprüft werden."
  - question: "Welcher Futterautomat funktioniert vollständig ohne App?"
    answer: "Fachautomaten wie Cat Mate C500, Mikrochip-Näpfe wie SureFeed und lokal programmierbare Trockenfutterautomaten können ohne App arbeiten. Sie lösen jedoch unterschiedliche Aufgaben."
  - question: "Gibt es Futterautomaten ohne WLAN für Nassfutter?"
    answer: "Ja. Ein Fachautomat kann vorbereitete Nassfutterportionen zu festen Zeiten öffnen. Kühlung, Standzeit und Reinigung bleiben separat zu prüfen."
  - question: "Speichert ein Futterautomat ohne WLAN den Zeitplan bei Batteriewechsel?"
    answer: "Das ist modellabhängig. Nach jedem Batteriewechsel müssen Uhr, Datum und gespeicherte Mahlzeiten kontrolliert werden."
  - question: "Ist ein Offline-Futterautomat datenschutzfreundlicher?"
    answer: "Ein vollständig lokales Gerät überträgt keine App-, Kamera- oder Nutzungsdaten an eine Cloud. Kauf- und Garantiedaten können dennoch beim Händler oder Hersteller anfallen."
`;
  text = replaceRegex(text, /faq:\n[\s\S]*?\ncontentPlatform:/, `${faqBlock}\ncontentPlatform:`, "Offline-FAQ");
  stage(files.offline, text);
}

// 3) Kamera-Ratgeber klar vom Produktvergleich trennen
{
  let text = read(files.camera);
  text = scalar(text, "seoTitle", "Futterautomat mit Kamera: sinnvoll oder unnötig?");
  text = scalar(text, "seoDescription", "Futterautomat mit Kamera einordnen: Was Livebild wirklich zeigt, welche Grenzen Video hat und welche Modelle sich im direkten Vergleich unterscheiden.");
  text = scalar(text, "updatedAt", "2026-07-25");
  text = text.replace(
    /comparisonHref:\s*\/vergleiche\/beste-futterautomaten\/?/g,
    "comparisonHref: /vergleiche/beste-futterautomaten-mit-kamera/"
  );
  text = text.replace(
    /^\s*secondaryHref:.*$/m,
    '  secondaryHref: "/vergleiche/beste-futterautomaten-mit-kamera/"'
  );
  text = text.replace(
    /^\s*secondaryLabel:.*$/m,
    '  secondaryLabel: "Kamera-Modelle direkt vergleichen"'
  );
  text = ensureCardCta(
    text,
    "Eine Kamera lohnt sich nur mit klarem Kontrollbedarf",
    "/vergleiche/beste-futterautomaten-mit-kamera/",
    "Kamera-Modelle vergleichen",
    "Kamera-Antwort-CTA"
  );
  const section = `
## Ratgeber oder Produktvergleich?

Diese Seite beantwortet, **ob** eine Kamera für deinen Alltag sinnvoll ist und welche Grenzen Livebild, Audio und Ereignisclips haben. Der separate [Vergleich der besten Futterautomaten mit Kamera](/vergleiche/beste-futterautomaten-mit-kamera/) beantwortet, **welches konkrete Modell** zu deinen Anforderungen passt.

So vermeiden beide Seiten dieselbe Suchintention: erst den Nutzen klären, danach Produkte vergleichen.

`;
  if (!text.includes("## Ratgeber oder Produktvergleich?")) {
    text = text.replace("## Zwei unterschiedliche Produktkonzepte", section + "## Zwei unterschiedliche Produktkonzepte");
  }
  stage(files.camera, text);
}

// 4) PETLIBRO als Marken-Hub stärken
{
  const original = read(files.petlibro);
  const { fm } = splitFrontmatter(original);
  let nextFm = scalar(fm, "updatedAt", "2026-07-25");
  nextFm = nextFm.replace(
    /(\nseo:\n\s+title:)\s*"[^"]*"/,
    '$1 "PETLIBRO Erfahrungen 2026: Modelle, App und Unterschiede"'
  );
  nextFm = nextFm.replace(
    /(\nseo:\n[\s\S]*?\n\s+description:)\s*"[^"]*"/,
    '$1 "PETLIBRO Futterautomaten und Trinkbrunnen: Granary, Polar, One RFID, Space und Dockstream nach App, Kamera, Kühlung, Zugang und Folgekosten."'
  );
  const body = `PETLIBRO gehört zu den breitesten Marken für smarte Fütterung und Trinktechnik. Genau diese Vielfalt ist Stärke und Risiko zugleich: Granary, Air, Polar, One RFID, Space und Dockstream lösen unterschiedliche Aufgaben und sollten nicht nur nach App oder Design verglichen werden.

## Welche PETLIBRO-Serie passt?

| Serie | Hauptaufgabe | Typische Grenze |
|---|---|---|
| Granary | Trockenfutter mit App oder Kamera | keine individuelle Tiertrennung |
| Air | kompakte Trockenfutterautomaten | weniger Spezialfunktionen |
| Polar | aktiv gekühltes Nassfutter | nur drei Mahlzeiten und Netzabhängigkeit der Kühlung |
| One RFID | geschützter Futterzugang | Halsband-Tag statt implantiertem Mikrochip |
| Space | großer, geschützter Trockenfuttervorrat | groß und stärker apporientiert |
| Dockstream | Trinkbrunnen mit Kabel, Akku, App oder RFID | Varianten und Filter sind nicht beliebig kompatibel |

## Unsere wichtigsten PETLIBRO-Modelle

- [PETLIBRO Granary WiFi](/produkt/petlibro-granary-wifi-feeder/) für flexible Trockenfutter-Zeitpläne,
- [PETLIBRO Granary Camera](/produkt/petlibro-granary-camera-feeder/) für zusätzliche Sichtkontrolle,
- [PETLIBRO Polar](/produkt/petlibro-polar-wet-food-feeder/) für aktiv gekühltes Nassfutter,
- [PETLIBRO One RFID](/produkt/petlibro-one-rfid-smart-feeder/) für getrennte Rationen,
- [PETLIBRO Space](/produkt/petlibro-space-smart-feeder/) für großen Vorrat,
- [PETLIBRO Dockstream 2 Smart](/produkt/petlibro-dockstream-2-smart/) für App-gestützte Wasserüberwachung.

## App, Cloud und Abo trennen

Nicht jedes PETLIBRO-Gerät benötigt dieselben Onlinedienste. Zeitpläne, Livebild, Cloud-Aufzeichnung, AI-Auswertung und Verbrauchsmaterial-Abos sind getrennte Funktionen. Vor dem Kauf sollte deshalb nicht nur „mit App“ geprüft werden, sondern:

- welche Grundfunktion ohne Abo erhalten bleibt,
- ob gespeicherte Pläne offline weiterlaufen,
- welche Videoaufzeichnung lokal oder nur in der Cloud möglich ist,
- welche Filter oder Trockenmittel regelmäßig nachgekauft werden müssen.

## Stärken und Grenzen der Marke

PETLIBRO ist besonders stark bei Speziallösungen, die viele Wettbewerber nicht abdecken: aktive Nassfutterkühlung, Kamera-Feeder, RFID-Zugang und smarte Trinkbrunnen.

Die Grenzen liegen in der Modellvielfalt, teils ähnlichen Produktnamen und modellgebundenem Zubehör. Eine gute PETLIBRO-Kaufentscheidung beginnt deshalb bei der Aufgabe und nicht bei der Produktserie.

## Passende Vergleiche

- [Futterautomaten für Katzen vergleichen](/vergleiche/beste-futterautomaten-fuer-katzen/)
- [Futterautomaten für Hunde vergleichen](/vergleiche/beste-futterautomaten-fuer-hunde/)
- [Nassfutterautomaten vergleichen](/vergleiche/beste-futterautomaten-fuer-nassfutter/)
- [Futterautomaten mit Kamera vergleichen](/vergleiche/beste-futterautomaten-mit-kamera/)
- [Trinkbrunnen für Hunde vergleichen](/vergleiche/beste-trinkbrunnen-fuer-hunde/)
- [Trinkbrunnen für Katzen vergleichen](/vergleiche/beste-trinkbrunnen-fuer-katzen/)

## Methodik

Die Herstellerseite fasst offizielle PETLIBRO-Unterlagen und die strukturierten PfotenTechnik-Produktdaten zusammen. Sie ist kein pauschaler Langzeittest der gesamten Marke. Unterschiede zwischen Modellgenerationen, regionalen Produktseiten und Zubehörvarianten werden nicht verallgemeinert.`;
  stage(files.petlibro, joinFrontmatter(nextFm, body));
}

// 5) Hub-Ankertexte und Offline-Einstieg
{
  let text = read(files.hub);
  text = text.replace('cta: "Kamera-Modelle ansehen"', 'cta: "Kamera-Ratgeber lesen"');
  text = text.replace('cta: "Lösungen vergleichen"', 'cta: "Mehrkatzen-Ratgeber lesen"');
  text = ensureCardCta(
    text,
    "Zeitplan statt Fernfütterung",
    "/futterautomat-ohne-wlan/",
    "Offline-Lösungen einordnen",
    "Hub-Offline-Link"
  );
  text = scalar(text, "updatedAt", "2026-07-25");
  stage(files.hub, text);
}

// 6) Zwei-Katzen-Seite: nur Datums-/Hub-Verstärkung, Inhalt bleibt stabil
{
  let text = read(files.twoCats);
  if (!text.includes("/vergleiche/beste-futterautomaten-fuer-zwei-katzen/")) {
    throw new Error("Zwei-Katzen-Seite verweist nicht auf die spezialisierte Comparison.");
  }
  text = scalar(text, "updatedAt", "2026-07-25");
  stage(files.twoCats, text);
}

// 7) Product-/Review-JSON-LD mit sichtbarer 100er-Skala und Pros/Cons
{
  let text = read(files.renderer);
  const start = "const productSchema = {";
  const end = "const productSearchValues = [";
  const schema = `const toReviewItemList = (items = []) => ({
  "@type": "ItemList",
  itemListElement: items
    .filter(Boolean)
    .slice(0, 5)
    .map((name, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name
    }))
});

const structuredReviewBody =
  contentProduct.review?.verdict ??
  contentProduct.review?.summary ??
  contentProduct.recommendation;

const productSchema = {
  "@context": "https://schema.org",
  "@type": "Product",
  name: contentProduct.title,
  description: seoDescription,
  url: new URL(canonical, site.domain).toString(),
  image: [
    new URL(optimizedOgImage.src, site.domain).toString()
  ],
  sku: contentProduct.slug,
  category: contentProduct.category.label,
  brand: {
    "@type": "Brand",
    name: contentProduct.manufacturer.name
  },
  review: {
    "@type": "Review",
    name: \`\${contentProduct.title} – redaktionelle Einordnung\`,
    reviewBody: structuredReviewBody,
    datePublished: publishedAt,
    author: {
      "@type": "Organization",
      name: author.name
    },
    publisher: {
      "@type": "Organization",
      name: "PfotenTechnik"
    },
    reviewRating: {
      "@type": "Rating",
      ratingValue: productScore100,
      bestRating: 100,
      worstRating: 0
    },
    ...(contentProduct.strengths?.length
      ? { positiveNotes: toReviewItemList(contentProduct.strengths) }
      : {}),
    ...(contentProduct.weaknesses?.length
      ? { negativeNotes: toReviewItemList(contentProduct.weaknesses) }
      : {})
  }
};

`;
  text = replaceBetween(text, start, end, schema, "Product-Schema");
  stage(files.renderer, text);
}

// 8) Dauerhaftes Audit
const auditSource = `#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const app = path.resolve(here, "../..");
const checks = [];
const read = (p) => fs.readFileSync(path.join(app, p), "utf8");
const check = (name, ok, detail = "") => checks.push({ name, ok, detail });

const offline = read("src/content/pages/futterautomat-ohne-wlan.md");
check("Offline-Comparison", offline.includes("/vergleiche/beste-futterautomaten-ohne-wlan/"));
check("Offline-Snippet", offline.includes("ohne App, Cloud und Konto"));

const camera = read("src/content/pages/futterautomat-mit-kamera.md");
check("Kamera-Comparison", camera.includes("/vergleiche/beste-futterautomaten-mit-kamera/"));
check("Kamera-Intent", camera.includes("sinnvoll oder unnötig"));

const polar = read("src/content/products/petlibro-polar-wet-food-feeder.md");
check("Polar aktiv", polar.includes('productStatus: "active"'));
check("Polar 2,4 GHz", polar.includes("2,4 GHz"));
check("Polar Ausfallschutz", polar.includes("12 Stunden"));
check("Polar Maße", polar.includes("361 × 340 × 196 mm"));
check("Polar Gewicht", polar.includes("3,4 kg"));

const fountain = read("src/content/comparisons/beste-trinkbrunnen-fuer-hunde.md");
const itemCount = (fountain.match(/^  - slug:/gm) ?? []).length;
const slugs = [...fountain.matchAll(/^  - slug: "([^"]+)"/gm)].map((m) => m[1]);
check("Hunde-Brunnen 6 Modelle", itemCount === 6, String(itemCount));
check("Hunde-Brunnen eindeutig", new Set(slugs).size === slugs.length);
check("Hunde-Brunnen Snippet", fountain.includes("6 Modelle im Vergleich 2026"));

const manufacturer = read("src/content/manufacturers/petlibro.md");
check("PETLIBRO Hub", manufacturer.includes("Welche PETLIBRO-Serie passt?"));
check("PETLIBRO Comparisons", manufacturer.includes("/vergleiche/beste-futterautomaten-fuer-nassfutter/"));

const renderer = read("src/pages/produkt/[product].astro");
check("Product positiveNotes", renderer.includes("positiveNotes"));
check("Product negativeNotes", renderer.includes("negativeNotes"));
check("Product 100er Skala", renderer.includes("bestRating: 100"));
check("Review datePublished", renderer.includes("datePublished: publishedAt"));

const failed = checks.filter((entry) => !entry.ok);
for (const entry of checks) {
  console.log(\`\${entry.ok ? "OK" : "FEHLER"}  \${entry.name}\${entry.detail ? \` (\${entry.detail})\` : ""}\`);
}
if (failed.length) {
  console.error(\`\\n\${failed.length} Prüfung(en) fehlgeschlagen.\`);
  process.exit(1);
}
console.log("\\nWoche-2-SEO-Audit erfolgreich.");
`;
if (fs.existsSync(files.audit)) {
  stage(files.audit, auditSource);
} else {
  changed.set(files.audit, { old: null, next: auditSource });
}

// Vorprüfung
console.log(`[${PATCH}] Repository: ${root}`);
console.log(`[${PATCH}] Geplante Änderungen: ${changed.size}`);

if (CHECK) {
  for (const file of changed.keys()) console.log(`ÄNDERN: ${rel(file)}`);
  console.log(`[${PATCH}] Vorprüfung erfolgreich. Es wurde nichts verändert.`);
  process.exit(0);
}

const backupRoot = path.join(
  root,
  ".patch-backups",
  `${PATCH}-${new Date().toISOString().replaceAll(":", "-")}`
);

try {
  for (const [file, state] of changed) {
    if (state.old !== null) {
      const backup = path.join(backupRoot, rel(file));
      fs.mkdirSync(path.dirname(backup), { recursive: true });
      fs.writeFileSync(backup, state.old, "utf8");
    }
  }

  for (const [file, state] of changed) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, state.next, "utf8");
    console.log(`GEÄNDERT: ${rel(file)}`);
  }

  const auditUrl = pathToFileURL(files.audit).href;
  await import(`${auditUrl}?t=${Date.now()}`);
  console.log(`[${PATCH}] Erfolgreich angewendet.`);
  console.log(`[${PATCH}] Backup: ${backupRoot}`);
  console.log("Nächster Schritt: npm run build:pfotentechnik");
} catch (error) {
  console.error(`[${PATCH}] Fehler: ${error.message}`);
  for (const [file, state] of changed) {
    if (state.old === null) {
      if (fs.existsSync(file)) fs.unlinkSync(file);
    } else {
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, state.old, "utf8");
    }
  }
  console.error(`[${PATCH}] Alle Änderungen wurden zurückgesetzt.`);
  process.exit(1);
}
