/** Generated by pfotentechnik-internal-link-and-selflink-cleanup-1.0.1. Redirect aliases remain sourced from public/_redirects. */
export const PFOTENTECHNIK_HOSTS = new Set(["pfotentechnik.de", "www.pfotentechnik.de"]);

export const COMPARISON_REDIRECT_ALIASES: Readonly<Record<string, string>> = Object.freeze({
  "/beste-futterautomaten-fuer-berufstaetige/": "/vergleiche/beste-futterautomaten-fuer-berufstaetige/",
  "/beste-futterautomaten-fuer-hunde/": "/vergleiche/beste-futterautomaten-fuer-hunde/",
  "/beste-futterautomaten-fuer-katzen/": "/vergleiche/beste-futterautomaten-fuer-katzen/",
  "/beste-futterautomaten-fuer-kleine-hunde/": "/vergleiche/beste-futterautomaten-fuer-kleine-hunde/",
  "/beste-futterautomaten-fuer-mehrtierhaushalte/": "/vergleiche/beste-futterautomaten-fuer-mehrtierhaushalte/",
  "/beste-futterautomaten-fuer-nassfutter/": "/vergleiche/beste-futterautomaten-fuer-nassfutter/",
  "/beste-futterautomaten-fuer-seniorenkatzen/": "/vergleiche/beste-futterautomaten-fuer-seniorenkatzen/",
  "/beste-futterautomaten-fuer-welpen/": "/vergleiche/beste-futterautomaten-fuer-welpen/",
  "/beste-futterautomaten-fuer-zwei-katzen/": "/vergleiche/beste-futterautomaten-fuer-zwei-katzen/",
  "/beste-futterautomaten-mit-akku/": "/vergleiche/beste-futterautomaten-mit-akku/",
  "/beste-futterautomaten-mit-edelstahl-napf/": "/vergleiche/beste-futterautomaten-mit-edelstahl-napf/",
  "/beste-futterautomaten-mit-kamera/": "/vergleiche/beste-futterautomaten-mit-kamera/",
  "/beste-futterautomaten-ohne-wlan/": "/vergleiche/beste-futterautomaten-ohne-wlan/",
  "/beste-futterautomaten-unter-100-euro/": "/vergleiche/beste-futterautomaten-unter-100-euro/",
  "/beste-gps-tracker-fuer-hunde/": "/vergleiche/beste-gps-tracker-fuer-hunde/",
  "/beste-gps-tracker-fuer-katzen/": "/vergleiche/beste-gps-tracker-fuer-katzen/",
  "/beste-trinkbrunnen-fuer-hunde/": "/vergleiche/beste-trinkbrunnen-fuer-hunde/",
  "/beste-trinkbrunnen-fuer-katzen/": "/vergleiche/beste-trinkbrunnen-fuer-katzen/",
  "/futterautomat-fuer-grosse-hunde/": "/vergleiche/futterautomat-fuer-grosse-hunde/",
  "/futterautomat-fuer-zwei-katzen/": "/vergleiche/beste-futterautomaten-fuer-zwei-katzen/",
  "/futterautomat-gegen-schlingen/": "/vergleiche/futterautomat-gegen-schlingen/",
  "/futterautomat-mit-app/": "/vergleiche/futterautomat-mit-app/",
  "/futterautomat-mit-kamera/": "/vergleiche/beste-futterautomaten-mit-kamera/",
  "/futterautomat-nassfutter/": "/vergleiche/beste-futterautomaten-fuer-nassfutter/",
  "/futterautomat-ohne-wlan/": "/vergleiche/beste-futterautomaten-ohne-wlan/",
  "/gps-tracker-mit-langer-akkulaufzeit/": "/vergleiche/gps-tracker-mit-langer-akkulaufzeit/",
  "/gps-tracker-ohne-abo/": "/vergleiche/gps-tracker-ohne-abo/",
  "/kleine-gps-tracker-fuer-katzen/": "/vergleiche/kleine-gps-tracker-fuer-katzen/"
});

const FUNCTIONAL_QUERY_KEYS = new Set(["filter", "tab", "sort", "view", "page", "step"]);

export const normalizeInternalPath = (value?: string, options: { keepFunctionalQuery?: boolean } = {}) => {
  const input = String(value ?? "").trim();
  if (!input) return "";
  if (input.startsWith("#")) return input;
  if (/^(?:mailto:|tel:|sms:|javascript:|data:)/i.test(input)) return "";
  let url: URL;
  try { url = new URL(input, "https://pfotentechnik.de/"); } catch { return ""; }
  if (!PFOTENTECHNIK_HOSTS.has(url.hostname.toLowerCase())) return "";
  let pathname = url.pathname.replace(/\/{2,}/g, "/");
  pathname = pathname === "/" ? "/" : pathname.replace(/\/+$/, "") + "/";
  let resolved = pathname;
  const seen = new Set<string>();
  while (COMPARISON_REDIRECT_ALIASES[resolved] && !seen.has(resolved)) {
    seen.add(resolved);
    resolved = COMPARISON_REDIRECT_ALIASES[resolved];
  }
  if (!options.keepFunctionalQuery) return resolved;
  const functional = new URLSearchParams();
  for (const [key, val] of url.searchParams) if (FUNCTIONAL_QUERY_KEYS.has(key)) functional.append(key, val);
  const query = functional.toString();
  return query ? resolved + "?" + query : resolved;
};

export const isInternalTarget = (value?: string) => {
  const input = String(value ?? "").trim();
  if (!input) return false;
  if (input.startsWith("#") || input.startsWith("/")) return true;
  try { return PFOTENTECHNIK_HOSTS.has(new URL(input).hostname.toLowerCase()); } catch { return false; }
};

export const isSelfLinkTarget = (target?: string, current?: string) => {
  const raw = String(target ?? "").trim();
  if (!raw || raw.startsWith("#")) return false;
  const targetFunctional = normalizeInternalPath(raw, { keepFunctionalQuery: true });
  const currentFunctional = normalizeInternalPath(current, { keepFunctionalQuery: true });
  if (!targetFunctional || !currentFunctional) return false;
  if (targetFunctional.includes("?") && targetFunctional !== normalizeInternalPath(raw)) return targetFunctional === currentFunctional;
  return normalizeInternalPath(raw) === normalizeInternalPath(current);
};

export const filterSelfLinkItems = <T extends { href?: string }>(items: T[], current?: string) =>
  items.filter((item) => item?.href && !isSelfLinkTarget(item.href, current));
