#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";

const NAME="pfotentechnik-surefeed-connect-current-data-25.10.7";
const SLUG="surefeed-microchip-pet-feeder-connect";
const CHECKED_AT="2026-08-03T16:38:00.000Z";
const SOURCE="https://www.surepetcare.com/de-de/futterautomat/microchip-pet-feeder-connect";
const log=(m)=>console.log(`[${NAME}] ${m}`);

function rootFrom(start){let d=path.resolve(start);for(let i=0;i<14;i+=1){if(fs.existsSync(path.join(d,"apps","pfotentechnik","package.json")))return d;const p=path.dirname(d);if(p===d)break;d=p;}throw new Error("Repository-Wurzel nicht gefunden.");}
function splitMd(src,label){const l=src.replace(/\r\n/g,"\n").split("\n");if(l[0]?.trim()!=="---")throw new Error(`${label}: Frontmatter-Start fehlt.`);const e=l.findIndex((x,i)=>i>0&&x.trim()==="---");if(e<0)throw new Error(`${label}: Frontmatter-Ende fehlt.`);return{fm:l.slice(1,e),body:l.slice(e+1)};}
function key(line){if(!line||/^\s/.test(line))return null;const i=line.indexOf(":");if(i<1)return null;const k=line.slice(0,i).trim();return /^[A-Za-z0-9_-]+$/.test(k)?k:null;}
function range(lines,k){const s=lines.findIndex(x=>key(x)===k);if(s<0)return null;let e=lines.length;for(let i=s+1;i<lines.length;i+=1){if(key(lines[i])){e=i;break;}}return{s,e};}
function block(lines,k){const r=range(lines,k);return r?lines.slice(r.s,r.e):[];}
function replaceBlock(lines,k,next){const r=range(lines,k);return r?[...lines.slice(0,r.s),...next,...lines.slice(r.e)]:[...lines,...next];}
function scalar(lines,k,v){return replaceBlock(lines,k,[`${k}: ${v}`]);}
function sections(lines){const out=[];let c={h:null,l:[]};for(const line of lines){if(line.startsWith("## ")){out.push(c);c={h:line.slice(3).trim(),l:[line]};}else c.l.push(line);}out.push(c);return out;}
function upsertSection(lines,h,content,before=[]){const s=sections(lines);const n={h,l:[`## ${h}`,"",...content,""]};const i=s.findIndex(x=>x.h===h);if(i>=0)s[i]=n;else{const b=s.findIndex(x=>x.h&&before.includes(x.h));b>=0?s.splice(b,0,n):s.push(n);}return s.flatMap(x=>x.l);}
function serialize(fm,body){const b=[...body];while(b.length&&!b[0].trim())b.shift();while(b.length&&!b.at(-1).trim())b.pop();return["---",...fm,"---",...b,""].join("\n");}
function itemRange(lines,slug){const s=lines.findIndex(x=>x.trim()===`- slug: ${slug}`);if(s<0)return null;const ind=lines[s].match(/^\s*/)?.[0].length??0;let e=lines.length;for(let i=s+1;i<lines.length;i+=1){const ci=lines[i].match(/^\s*/)?.[0].length??0;if(lines[i].trim().startsWith("- slug:")&&ci===ind){e=i;break;}if(lines[i].trim()&&ci<ind){e=i;break;}}return{s,e,ind};}
function upsertRec(lines){const r=itemRange(lines,SLUG);if(!r)return{found:false,lines};const fi=" ".repeat(r.ind+2),vi=" ".repeat(r.ind+4);const rep=[`${fi}recommendation: >-`,`${vi}Mikrochipgesteuerter Einzelnapf für getrennte Rationen. Mikrochipzugang und Portionswaage`,`${vi}arbeiten direkt am Gerät; App-Protokolle zu Fressmenge, Häufigkeit, Dauer und Tageszeiten`,`${vi}benötigen den Sure Petcare Hub. Einzelgerät, Hub und Bundle sind getrennte Kaufvarianten.`,`${vi}Preis und Lieferbarkeit deshalb aktuell und je Variante prüfen.`];let s=-1;for(let i=r.s+1;i<r.e;i+=1)if(lines[i].startsWith(`${fi}recommendation:`)){s=i;break;}if(s>=0){let e=s+1;while(e<r.e){const x=lines[e];if(x.startsWith(fi)&&!x.startsWith(vi))break;e+=1;}return{found:true,lines:[...lines.slice(0,s),...rep,...lines.slice(e)]};}let ins=r.s+1;for(let i=r.s+1;i<r.e;i+=1)if(lines[i].startsWith(`${fi}label:`)||lines[i].startsWith(`${fi}type:`))ins=i+1;return{found:true,lines:[...lines.slice(0,ins),...rep,...lines.slice(ins)]};}
function write(file,next){const prev=fs.existsSync(file)?fs.readFileSync(file,"utf8"):null;if(prev===next){log(`Bereits aktuell: ${path.relative(ROOT,file)}`);return;}fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,next,"utf8");log(`Geändert: ${path.relative(ROOT,file)}`);}
function run(script){log(`Prüfe: ${script}`);const npm=process.platform==="win32"?"npm.cmd":"npm";const r=spawnSync(npm,["--workspace","apps/pfotentechnik","run",script],{cwd:ROOT,stdio:"inherit",shell:false,env:process.env});if(r.error)throw r.error;if(r.status!==0)throw new Error(`${script} fehlgeschlagen (Exit ${r.status})`);log(`BESTANDEN: ${script}`);}
function assertHas(src,marks,label){for(const m of marks)if(!src.includes(m))throw new Error(`${label}: fehlt ${m}`);}

const ROOT=rootFrom(process.cwd()),APP=path.join(ROOT,"apps","pfotentechnik");
const PRODUCT=path.join(APP,"src","content","products",`${SLUG}.md`),DIR=path.join(APP,"src","content","comparisons"),PKG=path.join(APP,"package.json"),TEST=path.join(APP,"test","surefeed-connect-current-data-25.10.7.test.mjs");
if(!fs.existsSync(PRODUCT)||!fs.existsSync(DIR))throw new Error("Produktdatei oder Vergleichsverzeichnis fehlt.");
const comparisons=fs.readdirSync(DIR).filter(n=>n.endsWith(".md")).map(n=>path.join(DIR,n)).filter(f=>fs.readFileSync(f,"utf8").includes(`slug: ${SLUG}`)).sort();if(!comparisons.length)throw new Error("Keine SureFeed-relevanten Vergleiche gefunden.");
const scripts=JSON.parse(fs.readFileSync(PKG,"utf8")).scripts??{};for(const s of ["lint:content","audit:products:strict","comparison:data:audit:strict","audit:product-standard-3:strict","build"])if(!scripts[s])throw new Error(`npm-Skript fehlt: ${s}`);
const original=fs.readFileSync(PRODUCT,"utf8"),doc=splitMd(original,"Produkt"),score=block(doc.fm,"score").join("\n"),recommendation=block(doc.fm,"recommendation").join("\n");if(!score||!recommendation)throw new Error("Score oder Empfehlung fehlen.");
const BACKUP=path.join(ROOT,".patch-backups",`${NAME}-${new Date().toISOString().replace(/[:.]/g,"-")}`),targets=[PRODUCT,...comparisons,TEST];fs.mkdirSync(BACKUP,{recursive:true});for(const f of targets)if(fs.existsSync(f)){const d=path.join(BACKUP,path.relative(ROOT,f));fs.mkdirSync(path.dirname(d),{recursive:true});fs.copyFileSync(f,d);}log(`Backup: ${path.relative(ROOT,BACKUP)}`);
const rollback=()=>{for(const f of targets){const b=path.join(BACKUP,path.relative(ROOT,f));if(fs.existsSync(b)){fs.mkdirSync(path.dirname(f),{recursive:true});fs.copyFileSync(b,f);}else if(f===TEST)fs.rmSync(f,{force:true});}};
try{
 let fm=[...doc.fm];fm=scalar(fm,"updatedAt",'"2026-08-03"');fm=replaceBlock(fm,"price",["price:",'  currency: "EUR"','  status: "unknown"',`  checkedAt: "${CHECKED_AT}"`,"  source:",'    id: "sure-petcare-de"','    label: "Sure Petcare Deutschland"','    type: "manual"']);fm=scalar(fm,"priceState",'"unknown"');fm=scalar(fm,"priceUpdated",`"${CHECKED_AT}"`);fm=scalar(fm,"priceAvailable","false");fm=scalar(fm,"availability",'"unknown"');fm=scalar(fm,"availabilityReason",'"Einzelgerät, Hub und Bundle werden getrennt angeboten. Die deutsche Herstellerseite zeigt Preise, zugleich aber Nicht-vorrätig-Signale; Händlerbestand kann abweichen. Preis und Lieferstatus je Variante aktuell prüfen."');fm=scalar(fm,"availabilityUpdated",`"${CHECKED_AT}"`);
 let body=[...doc.body];body=upsertSection(body,"Gerät, Hub und Bundle",["Mikrochipzugang, Deckelsteuerung, integrierte Waage und LED-Portionshilfe gehören zum Gerät. Für die Verbindung mit der Sure Petcare App ist zusätzlich ein **Sure Petcare Hub** nötig, der per Ethernet am Router angeschlossen wird.","","Wer bereits einen kompatiblen Sure Petcare Hub besitzt, kann das Einzelgerät in das vorhandene Connect-System aufnehmen. Beim ersten Sure-Petcare-Connect-Produkt müssen entweder das Bundle aus Futterautomat und Hub oder ein separat erhältlicher Hub eingeplant werden. Laut Hersteller können bis zu zehn kompatible Connect-Geräte einen Hub gemeinsam nutzen."],["App-Funktionen und gemessene Fressdaten","Preis und Verfügbarkeit","Quellenlage"]);body=upsertSection(body,"App-Funktionen und gemessene Fressdaten",["Die integrierte Waage und LED-Portionsanzeige helfen beim manuellen Befüllen auf **1 Gramm genau**. Über die App lassen sich für das registrierte Tier Fressmenge, Häufigkeit, Dauer und Tageszeiten verfolgen; zusätzlich kann das System Push-Mitteilungen bei Fressereignissen senden.","","Diese Daten sind eine Verlaufshilfe, aber kein medizinischer Befund. Der Connect-Napf schützt eine manuell eingefüllte Portion und ist kein zeitgesteuerter Vorratsautomat."],["Preis und Verfügbarkeit","Quellenlage"]);body=upsertSection(body,"Preis und Verfügbarkeit",["Die deutsche Herstellerseite trennt Einzelgerät, separaten Hub und Bundle. Sie nennt dafür unterschiedliche Preise, zeigt aktuell aber zugleich Hinweise auf fehlenden Bestand. Händlerangebote können davon abweichen.","","Deshalb wird weder ein Herstellerpreis noch ein Händlerpreis dauerhaft als redaktioneller Festpreis übernommen. Preis und Lieferbarkeit gelten als **aktuell zu prüfen**, getrennt nach Einzelgerät, Hub, Bundle und Händlerangebot."],["Quellenlage"]);body=upsertSection(body,"Quellenlage",[`Die technischen, systembezogenen sowie Preis- und Verfügbarkeitsangaben wurden am 3. August 2026 mit der [deutschen Herstellerseite zum SureFeed Mikrochip Futterautomat Connect](${SOURCE}) abgeglichen.`,"","Editorial Score und redaktionelle Empfehlung wurden durch diesen Datenabgleich nicht verändert."]);
 const next=serialize(fm,body),nd=splitMd(next,"Zielprodukt");if(block(nd.fm,"score").join("\n")!==score||block(nd.fm,"recommendation").join("\n")!==recommendation)throw new Error("Score oder Empfehlung würden verändert.");if(/^\s*current:/m.test(block(nd.fm,"price").join("\n")))throw new Error("Statischer Preis bleibt bestehen.");assertHas(next,['priceState: "unknown"','priceAvailable: false','availability: "unknown"','Gerät, Hub und Bundle','Fressmenge, Häufigkeit, Dauer und Tageszeiten','1 Gramm genau'],"Produkt");write(PRODUCT,next);
 for(const file of comparisons){const src=fs.readFileSync(file,"utf8"),d=splitMd(src,path.basename(file)),u=upsertRec(d.fm);if(!u.found)throw new Error(`${path.basename(file)}: SureFeed-Item nicht gefunden.`);const b=upsertSection(d.body,"SureFeed Connect richtig einordnen",["Der **SureFeed Mikrochip Futterautomat Connect** ist ein geschützter Einzelnapf und kein zeitgesteuerter Vorratsautomat. Mikrochipzugang und integrierte Portionswaage arbeiten direkt am Gerät.","","Für App-Protokolle zu Fressmenge, Häufigkeit, Dauer und Tageszeiten wird ein **Sure Petcare Hub** benötigt. Ein vorhandener kompatibler Hub kann weiterverwendet werden; andernfalls sind Bundle oder separater Hub nötig. Einzelgerät, Hub und Bundle sind getrennte Kaufvarianten, deshalb werden Preis und Lieferbarkeit aktuell und je Variante geprüft."],["Fazit","Quellen"]);const n=serialize(u.lines,b);assertHas(n,["App-Protokolle zu Fressmenge, Häufigkeit, Dauer und Tageszeiten","Einzelgerät, Hub und Bundle sind getrennte Kaufvarianten"],path.basename(file));write(file,n);}
 const test=`import assert from "node:assert/strict";import fs from "node:fs";import path from "node:path";import test from "node:test";const APP=process.cwd(),p=path.join(APP,"src/content/products/${SLUG}.md"),d=path.join(APP,"src/content/comparisons"),s=fs.readFileSync(p,"utf8");test("Hub und Bundle",()=>{assert.match(s,/Gerät, Hub und Bundle/);assert.match(s,/bis zu zehn kompatible Connect-Geräte/)});test("Preis dynamisch",()=>{const b=s.match(/\\nprice:\\n([\\s\\S]*?)\\n[a-zA-Z0-9_-]+:/)?.[1]??"";assert.doesNotMatch(b,/^\\s*current:/m);assert.match(s,/priceState: "unknown"/);assert.match(s,/priceAvailable: false/);assert.match(s,/availability: "unknown"/)});test("App-Daten",()=>{assert.match(s,/Fressmenge, Häufigkeit, Dauer und Tageszeiten/);assert.match(s,/1 Gramm genau/);assert.match(s,/400 ml/);assert.doesNotMatch(s,/Statistiken als PDF/)});test("Score und Empfehlung",()=>{assert.match(s,/\\nscore: 79\\n/);assert.match(s,/recommendation: Sinnvoll für getrennte Rationen/)});test("Vergleiche",()=>{const files=fs.readdirSync(d).filter(n=>n.endsWith(".md")).map(n=>path.join(d,n)).filter(f=>fs.readFileSync(f,"utf8").includes("slug: ${SLUG}"));assert.ok(files.length>0);for(const f of files){const c=fs.readFileSync(f,"utf8");assert.match(c,/SureFeed Connect richtig einordnen/);assert.match(c,/Einzelgerät, Hub und Bundle sind getrennte Kaufvarianten/)}});`;write(TEST,test);
 const tr=spawnSync(process.execPath,["--test",path.relative(APP,TEST)],{cwd:APP,stdio:"inherit",shell:false,env:process.env});if(tr.error)throw tr.error;if(tr.status!==0)throw new Error(`Patch-Test fehlgeschlagen (Exit ${tr.status})`);for(const s of ["lint:content","audit:products:strict","comparison:data:audit:strict","audit:product-standard-3:strict","build"])run(s);
 const report=path.join(APP,"reports","product-research","surefeed-connect-current-data-25.10.7.json");fs.mkdirSync(path.dirname(report),{recursive:true});fs.writeFileSync(report,JSON.stringify({patch:NAME,status:"passed",source:SOURCE,checkedAt:CHECKED_AT,product:path.relative(ROOT,PRODUCT),comparisons:comparisons.map(f=>path.relative(ROOT,f)),scoreChanged:false,recommendationChanged:false,staticPriceRemoved:true,availabilityUnknown:true,backup:path.relative(ROOT,BACKUP)},null,2)+"\n");log(`Report: ${path.relative(ROOT,report)}`);log(`Abgeschlossen. Vergleiche: ${comparisons.length}`);
}catch(error){rollback();log(`FEHLER: ${error instanceof Error?error.message:String(error)}`);log("Änderungen wurden zurückgerollt.");process.exitCode=1;}
