#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
const PATCH="pfotentechnik-pettec-cam-360-33.5.0";
function findRoot(start){let d=path.resolve(start);while(true){if(fs.existsSync(path.join(d,"apps","pfotentechnik","package.json")))return d;const p=path.dirname(d);if(p===d)throw new Error(`[${PATCH}] Root nicht gefunden.`);d=p}}
const root=findRoot(path.dirname(fileURLToPath(import.meta.url))),app=path.join(root,"apps","pfotentechnik"),yaml=createRequire(path.join(app,"package.json"))("js-yaml"),at=p=>path.join(app,...p.split("/"));
const files={product:at("src/content/products/pettec-cam-360.md"),comparison:at("src/content/comparisons/beste-haustierkameras.md"),hub:at("src/content/pages/haustierkameras.md"),prompt:at("research/visual-prompts/pettec-cam-360-visual-master-prompt.txt"),test:at("test/pettec-cam-360-33.5.0.test.mjs")};
function parse(s,l){const m=s.match(/^---\s*\r?\n([\s\S]*?)\r?\n---\s*\r?\n?([\s\S]*)$/);if(!m)throw new Error(`[${PATCH}] Frontmatter fehlt: ${l}`);return{data:yaml.load(m[1],{schema:yaml.JSON_SCHEMA}),body:m[2].trim()}}
function dump(d){return`---\n${yaml.dump(d.data,{schema:yaml.JSON_SCHEMA,noRefs:true,lineWidth:120,quotingType:'"',forceQuotes:true})}---\n\n${d.body.trim()}\n`}
function section(body,id,content){const a=`<!-- ${id}:start -->`,b=`<!-- ${id}:end -->`,block=`${a}\n${content.trim()}\n${b}`;if(body.includes(a)&&body.includes(b)){const esc=v=>v.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return body.replace(new RegExp(`${esc(a)}[\\s\\S]*?${esc(b)}`),block)}return`${body.trim()}\n\n${block}`}

const product=dump({data:{
  title:"PetTec Cam 360",slug:"pettec-cam-360",type:"product",layout:"product",testStatus:"manufacturer-data",productStatus:"active",
  description:"Stationäre 3-MP-Schwenk-/Neigkamera mit lokaler microSD-Speicherung, Nachtsicht, Bewegungs- und Geräuscherkennung, Tracking und Basisfunktionen ohne Pflichtabo.",
  recommendation:"Für einen festen Innenbereich, wenn lokale microSD-Aufzeichnung und kostenlose App-Basisfunktionen wichtiger sind als eine ausschließlich cloudbasierte Historie.",
  manufacturer:{key:"pettec",name:"PetTec",slug:"pettec"},category:{key:"haustierkameras",label:"Haustierkameras",path:"/haustierkameras/"},productUrl:"/produkt/pettec-cam-360/",
  publishedAt:"2026-08-15",updatedAt:"2026-08-15",author:{name:"PfotenTechnik Redaktion",role:"Redaktion"},
  seo:{title:"PetTec Cam 360: lokal speichern ohne Pflichtabo",description:"PetTec Cam 360 mit 3 MP, microSD, optionaler Cloud, Nachtsicht, Tracking und Zwei-Wege-Audio transparent eingeordnet.",canonical:"/produkt/pettec-cam-360/",sitemap:true,priority:0.8},
  hub:{sections:["produkte","haustierkameras"]},tags:["haustierkamera","pettec","microsd","lokale-speicherung","ohne-pflichtabo"],
  images:{hero:{src:"../../assets/images/project/pfotentechnik/comparison/default-editorial-hero.webp",alt:"Neutrale redaktionelle Darstellung einer stationären Schwenk-Neige-Haustierkamera"},gallery:[]},
  price:{current:null,currency:"EUR",status:"unknown",checkedAt:"2026-08-15",source:{id:"pettec-de",label:"PetTec",type:"editorial"}},priceAutomation:"editorial",priceState:"unknown",priceAvailable:false,affiliateAvailable:false,
  availability:"unknown",availabilityReason:"Preis und Lieferstatus werden nicht als dauerhafte redaktionelle Angabe gespeichert.",availabilityUpdated:"2026-08-15",editorialStatus:"required",recommendationStatus:"limited",maintenanceStatus:"required",
  rating:0,ratings:{},externalEvidence:{status:"constrained",note:"Aktuell nur Herstellerdaten; kein eigener Praxistest oder juristische Datenschutzprüfung."},
  decision:{bestFor:["Lokale Videoaufzeichnung auf microSD","Grundfunktionen ohne monatliches Pflichtabo","Fester Innenbereich mit Schwenk-/Neigeabdeckung"],attention:["Optionaler Cloud Event Video Service bleibt verfügbar","Ohne Pflichtabo bedeutet nicht ohne Cloud-Funktionen","Herstellerangaben zu DSGVO und deutschen Servern sind keine eigene Rechtsprüfung","microSD-Karte und Speicherdauer vor Kauf prüfen"]},
  review:{summary:"PetTec trennt lokale microSD-Aufzeichnung und kostenlose Basisfunktionen von optionalen Cloud- und AI-Diensten.",verdict:"Klare lokale Speicheroption für einen festen Bereich; Datenschutz hängt zusätzlich von Konto, App, Fernzugriff und Konfiguration ab."},
  strengths:["Lokale microSD-Speicherung","Kein Pflichtabo für Grundfunktionen laut Hersteller","3-MP-Kamera mit Schwenken/Neigen","Nachtsicht und Zwei-Wege-Audio"],
  weaknesses:["Optionale Cloud bleibt Teil des Systems","Datenschutzclaims nur herstellerseitig","microSD-Kapazität und Aufbewahrung aktuell prüfen","Fester Standort deckt nicht mehrere getrennte Räume ab"],
  features:["3 MP","Schwenken und Neigen","Bewegungsdetektion","Geräuscherkennung","Bewegungsverfolgung","Nachtsicht","Zwei-Wege-Audio","microSD","optionale Cloud"],useCase:"Stationäre Haustierkamera mit lokaler Speicherung und optionaler Cloud",
  specs:[{label:"Kamera",value:"3 MP"},{label:"Schwenken/Neigen",value:"Ja; 360°-Rundumsicht ist Herstellerbeschreibung"},{label:"Erkennung",value:"Bewegung und Geräusch"},{label:"Tracking",value:"Bewegungsverfolgung"},{label:"Nachtsicht",value:"Ja"},{label:"Audio",value:"Zwei-Wege-Audio"},{label:"Lokale Speicherung",value:"microSD möglich"},{label:"Cloud",value:"Optionaler Cloud Event Video Service und optionale Cloud-AI-Dienste"},{label:"Pflichtabo",value:"Nein für Grundfunktionen laut Hersteller"},{label:"Kostenlose App",value:"Livestream, Fotos, Zwei-Wege-Audio und weitere Basisfunktionen laut Hersteller"},{label:"Abmessungen",value:"63,5 × 63,5 × 57 mm"},{label:"Gewicht",value:"180 g"},{label:"Kabel",value:"2 m"},{label:"Datenschutz",value:"DSGVO-Konformität und deutsche Server sind Herstellerangaben, nicht redaktionell rechtlich bestätigt"}],
  comparisonData:{version:1,custom:{klasse:"Stationäre Pan/Tilt-Kamera mit lokaler Option",speicher:"microSD lokal möglich; Cloud optional",abo:"Kein Pflichtabo; optionale Bezahldienste",interaktion:"Zwei-Wege-Audio",abdeckung:"Schwenken/Neigen; Hersteller beschreibt 360°",bild:"3 MP; Nachtsicht",lokale_speicherung:"Ja, microSD",cloud_erforderlich:"Nein für lokale Aufzeichnung/Basisfunktionen",cloud_optional:"Ja",pflichtabo:"Nein",bezahlfunktionen:"Cloud Event Video und Cloud AI optional",kostenlose_grundfunktionen:"Livestream, Fotos, Audio laut Hersteller",microsd:"Ja",aufloesung:"3 MP",schwenk_neige:"Ja",tracking:"Bewegungsverfolgung",nachtsicht:"Ja",audio:"Zwei-Wege-Audio"}},
  comparisonFilters:{animal:["dog","cat"],petSize:["small","medium","large"],foodType:[],app:true,camera:true},alternatives:["petlibro-scout-smart-camera","furbo-mini-360","enabot-rola-mini"],comparisons:["beste-haustierkameras"],
  decisionJourney:{cluster:"haustierkameras",stage:"decision",intent:"haustierkamera-mit-lokaler-speicherung-pruefen",primaryQuestion:"Sind lokale microSD-Aufzeichnung, optionale Cloud und kostenlose Basisfunktionen die passende Datenstrategie?",next:["/vergleiche/beste-haustierkameras/"],fallback:["/haustierkameras/"]},
  faq:[{question:"Braucht die PetTec Cam 360 ein Abo?",answer:"Für die vom Hersteller genannten Grundfunktionen besteht kein Pflichtabo. Cloud Event Video und Cloud AI sind optionale Bezahldienste."},{question:"Kann die Kamera lokal speichern?",answer:"Ja. PetTec dokumentiert Aufzeichnung auf microSD. Karte, Kapazitätsgrenzen und gewünschte Aufbewahrungsdauer sollten aktuell geprüft werden."},{question:"Ist die Kamera ohne Cloud nutzbar?",answer:"Lokale microSD-Aufzeichnung und Grundfunktionen sind ohne Pflichtabo vorgesehen. PetTec bietet trotzdem optionale Cloud-Dienste; daher wird das System nicht pauschal als cloudfrei bezeichnet."},{question:"Bestätigt PfotenTechnik die DSGVO-Konformität?",answer:"Nein. DSGVO-Konformität und Server in Deutschland sind Aussagen des Herstellers, keine eigene juristische Prüfung oder Garantie."}],
  editorial:{assessmentType:"data-review",evidence:["manufacturer-documentation","technical-specifications","comparative-analysis"],testedHandsOn:false,lastVerifiedAt:"2026-08-15",note:"Herstellerdaten; kein eigener Produkttest und keine Rechtsberatung."},
  evidenceSources:[{source:"PetTec Cam 360",url:"https://pettec.de/products/pet-cam-360",accessedAt:"2026-08-15",assertion:"3 MP, Pan/Tilt, Erkennung, Tracking, Nachtsicht, Audio, Maße und Speicheroptionen sind Herstellerangaben.",fields:["specs","features","comparisonData"]},{source:"PetTec Kameras ohne Abo",url:"https://pettec.de/pages/kameras-ohne-abo",accessedAt:"2026-08-15",assertion:"Lokale microSD-Speicherung und Nutzung ohne Pflichtabo sind Herstellerangaben.",fields:["decision","faq","comparisonData"]},{source:"PetTec App",url:"https://pettec.de/pages/app",accessedAt:"2026-08-15",assertion:"Kostenlose Basisfunktionen und optionale Cloud-Dienste sind Herstellerangaben.",fields:["specs","faq","comparisonData"]}],
},body:`## Lokal speichern, Cloud optional halten\n\nDie zentrale Kaufentscheidung ist nicht die höchste Auflösung. Die Cam 360 kann laut PetTec lokal auf **microSD** aufzeichnen und bietet Grundfunktionen ohne monatliches Pflichtabo. Gleichzeitig existieren ein optionaler Cloud Event Video Service und optionale Cloud-AI-Funktionen. „Ohne Abo“ bedeutet deshalb nicht automatisch „ohne Cloud“.\n\nPetTec beschreibt DSGVO-Konformität und Server in Deutschland. Das sind Herstellerangaben, keine juristische Bestätigung durch PfotenTechnik. Datenschutz hängt außerdem von App-Konto, Mikrofon, Fernzugriff, Updates und Konfiguration ab.\n\nDer [Haustierkamera-Hub](/haustierkameras/) erklärt die Speicherentscheidung; der [Vergleich](/vergleiche/beste-haustierkameras/) stellt sie Cloud-only- und mobilen Kameraklassen gegenüber.`});

function comparison(source){const doc=parse(source,"Kameravergleich"),prior=new Map((doc.data.items??[]).map(i=>[i.slug,i]));const item=prior.get("pettec-cam-360")??{slug:"pettec-cam-360",type:"product",values:{}};item.label="PetTec Cam 360";item.recommendation="Für lokale microSD-Aufzeichnung und Basisfunktionen ohne Pflichtabo; optionale Cloud bleibt eine bewusste Zusatzentscheidung.";item.values={...(item.values??{}),klasse:"Stationäre Pan/Tilt-Kamera mit lokaler Option",speicher:"microSD lokal; Cloud optional",abo:"Kein Pflichtabo; Bezahlfunktionen optional",interaktion:"Zwei-Wege-Audio",abdeckung:"Schwenken/Neigen; Hersteller beschreibt 360°",bild:"3 MP; Nachtsicht",lokale_speicherung:"Ja",cloud_erforderlich:"Nein für lokale Aufzeichnung",cloud_optional:"Ja",pflichtabo:"Nein",bezahlfunktionen:"Cloud Event Video / Cloud AI optional",kostenlose_grundfunktionen:"Livestream, Fotos, Audio",microsd:"Ja",aufloesung:"3 MP",schwenk_neige:"Ja",tracking:"Bewegungsverfolgung",nachtsicht:"Ja",audio:"Zwei-Wege-Audio"};if(!prior.has(item.slug))doc.data.items.push(item);
 const known={"petlibro-scout-smart-camera":{lokale_speicherung:"Nein dokumentiert",cloud_erforderlich:"Ja für Aufzeichnung",cloud_optional:"Nein für Aufzeichnung",pflichtabo:"Für Aufzeichnung/KI tarifabhängig",bezahlfunktionen:"Cloud-/KI-Tarif",kostenlose_grundfunktionen:"Umfang aktuell prüfen",microsd:"Nein",aufloesung:"1080p",schwenk_neige:"Ja",tracking:"KI-/Tariffunktionen prüfen",nachtsicht:"Farbe und Schwarz-Weiß",audio:"Zwei-Wege-Audio"},"furbo-mini-360":{lokale_speicherung:"Nicht belastbar ausgewiesen",cloud_erforderlich:"Aktuellen Umfang prüfen",cloud_optional:"Optionale Dienste",pflichtabo:"Kein Pflichtabo für alle Basisfunktionen behauptet",bezahlfunktionen:"Optionale Dienste prüfen",kostenlose_grundfunktionen:"Aktuellen Umfang prüfen",microsd:"Nicht ausgewiesen",aufloesung:"2K QHD",schwenk_neige:"360°-Rotation",tracking:"Nicht belastbar ausgewiesen",nachtsicht:"Ja",audio:"Zwei-Wege-Audio"},"enabot-rola-mini":{lokale_speicherung:"Nicht belastbar ausgewiesen",cloud_erforderlich:"Nicht belastbar ausgewiesen",cloud_optional:"Nicht belastbar ausgewiesen",pflichtabo:"Kein Pflichtabo belastbar belegt",bezahlfunktionen:"Aktuell prüfen",kostenlose_grundfunktionen:"App-Fahrt und Audio",microsd:"Nicht ausgewiesen",aufloesung:"2K",schwenk_neige:"Mobiler Standort statt Pan/Tilt",tracking:"Bewegungsaufzeichnung",nachtsicht:"Nicht belastbar ausgewiesen",audio:"Zwei-Wege-Audio"}};for(const candidate of doc.data.items)if(known[candidate.slug])candidate.values={...(candidate.values??{}),...known[candidate.slug]};
 const extras=[["lokale_speicherung","Lokale Speicherung"],["cloud_erforderlich","Cloud erforderlich"],["cloud_optional","Cloud optional"],["pflichtabo","Pflichtabo"],["bezahlfunktionen","Optionale Bezahlfunktionen"],["kostenlose_grundfunktionen","Kostenlose Grundfunktionen"],["microsd","microSD"],["aufloesung","Auflösung"],["schwenk_neige","Schwenken / Neigen"],["tracking","Tracking"],["nachtsicht","Nachtsicht"],["audio","Zwei-Wege-Audio"]],criteria=new Map(doc.data.criteria.map(c=>[c.key,c]));for(const[key,label]of extras)criteria.set(key,{key,label,format:"text",fallback:"Nicht ausgewiesen"});doc.data.criteria=[...criteria.values()];doc.data.updatedAt="2026-08-15";doc.data.description="Vier Haustierkamera-Klassen nach lokaler Speicherung, Cloud, Pflichtabo, Interaktion, Blickbereich und Bildfunktionen vergleichen.";doc.data.tableTitle="Vier Speicher- und Kameraklassen direkt vergleichen";doc.data.recommendation={title:"Speicherweg vor Auflösung entscheiden",text:"PetTec ergänzt lokale microSD ohne Pflichtabo, Scout steht für Cloud-only-Aufzeichnung, Furbo für stationäre Interaktion und ROLA Mini für mobile Perspektiven. Unbekannte Daten bleiben offen.",alternativeSlug:"pettec-cam-360"};doc.data.decisionJourney={...(doc.data.decisionJourney??{}),next:[...new Set([...(doc.data.decisionJourney?.next??[]),"/produkt/pettec-cam-360/"])]};doc.body=section(doc.body,"pt:pettec-local-storage",`## Neue Kaufrolle: lokale Speicherung ohne Pflichtabo\n\nDie [PetTec Cam 360](/produkt/pettec-cam-360/) ergänzt den Vergleich um lokale microSD-Aufzeichnung. Pflichtabo, optionale Cloud und kostenlose Grundfunktionen stehen in getrennten Feldern. Unbekannte Angaben anderer Produkte werden nicht aufgefüllt. Lokale Speicherung reduziert Cloud-Abhängigkeit, macht App-Konto, Fernzugriff und Gerätesicherheit aber nicht automatisch datenschutzkonform.`);return dump(doc)}
function hub(source){const doc=parse(source,"Kamerahub"),products=new Set(doc.data.contentPlatform?.products??[]);products.add("pettec-cam-360");doc.data.contentPlatform.products=[...products];doc.data.updatedAt="2026-08-15";doc.body=section(doc.body,"pt:pettec-storage-choice",`## Lokale Speicherung oder Cloud?\n\nLokale Speicherung kann laufende Kosten und die Abhängigkeit von einer Video-Cloud reduzieren. Cloud-Speicher kann externen Zugriff und Sicherung vereinfachen, verarbeitet die Aufnahmen aber in einem zusätzlichen Dienst. **Ohne Abo** bedeutet nicht automatisch **ohne Cloud**.\n\nDie [PetTec Cam 360](/produkt/pettec-cam-360/) bietet laut Hersteller microSD-Aufzeichnung und Grundfunktionen ohne Pflichtabo, daneben aber optionale Cloud-Dienste. Datenschutz hängt nicht nur vom Speicherort ab, sondern auch von Konto, App, Mikrofon, Fernzugriff, Updates und Konfiguration. Die Kaufrollen stehen im [Haustierkamera-Vergleich](/vergleiche/beste-haustierkameras/).`);return dump(doc)}
const prompt=`MASTER-PROMPT: PetTec Cam 360\n\nFotorealistische redaktionelle Produktserie derselben kompakten stationären Schwenk-/Neigkamera. Keine erfundenen Logos, Cloud-Siegel, DSGVO-Siegel, Displays oder Speicherkarten-Slots an falscher Position.\n\nFeste Motivfolge:\n1. Premium Hero\n2. Thumbnail\n3. Perspektivansicht\n4. Linsen- und Schwenk-/Neigdetail\n5. microSD-/lokaler-Speicher-Kontext ohne erfundene UI\n6. reale Nutzung im Haustierbereich\n\nPro Antwort genau ein Bild erzeugen und stoppen. Ausschließlich auf exakt „Weiter“ das nächste Motiv erzeugen. Nichts überspringen oder wiederholen; Modell, Farbe und Geometrie bleiben identisch.\n`;
const test=`import assert from "node:assert/strict";import fs from "node:fs";import path from "node:path";import test from "node:test";import{createRequire}from"node:module";import{fileURLToPath}from"node:url";const app=path.resolve(path.dirname(fileURLToPath(import.meta.url)),".."),yaml=createRequire(path.join(app,"package.json"))("js-yaml"),load=(kind,slug)=>{const source=fs.readFileSync(path.join(app,"src/content",kind,slug+".md"),"utf8"),m=source.match(/^---\\s*\\r?\\n([\\s\\S]*?)\\r?\\n---/);assert.ok(m);return{source,data:yaml.load(m[1],{schema:yaml.JSON_SCHEMA})}};test("PetTec separates local, required subscription and optional cloud",()=>{const p=load("products","pettec-cam-360"),c=p.data.comparisonData.custom;assert.match(c.lokale_speicherung,/microSD|Ja/);assert.equal(c.pflichtabo,"Nein");assert.equal(c.cloud_optional,"Ja");assert.doesNotMatch(p.source,/vollständig ohne Cloud|komplett ohne Cloud|Cloud-frei/i);assert.match(p.source,/Herstellerangaben/);assert.equal(p.data.rating,0)});test("camera comparison and hub link product",()=>{const c=load("comparisons","beste-haustierkameras"),h=load("pages","haustierkameras");assert.ok(c.data.items.some(i=>i.slug==="pettec-cam-360"));assert.ok(h.data.contentPlatform.products.includes("pettec-cam-360"));assert.match(c.source,/pettec-cam-360/);assert.match(h.source,/pettec-cam-360/)});test("neutral image exists",()=>{const p=load("products","pettec-cam-360"),image=path.resolve(path.join(app,"src/content/products"),p.data.images.hero.src);assert.ok(fs.existsSync(image))});\n`;
const desired=new Map([[files.product,product],[files.comparison,comparison(fs.readFileSync(files.comparison,"utf8"))],[files.hub,hub(fs.readFileSync(files.hub,"utf8"))],[files.prompt,prompt],[files.test,test]]),managed=new Set([files.product,files.prompt,files.test]),identity=(f,s)=>f===files.product?/slug:\s*["']?pettec-cam-360/.test(s):f===files.prompt?s.includes("MASTER-PROMPT: PetTec Cam 360"):f===files.test&&s.includes("PetTec separates local");const changes=[...desired].filter(([f,c])=>!fs.existsSync(f)||fs.readFileSync(f,"utf8")!==c);for(const[f,c]of changes)if(managed.has(f)&&fs.existsSync(f)&&!identity(f,fs.readFileSync(f,"utf8"))&&fs.readFileSync(f,"utf8")!==c)throw new Error(`[${PATCH}] Konflikt: ${path.relative(root,f)}`);let backup=null;if(changes.length){backup=path.join(root,".patch-backups",`${PATCH}-${new Date().toISOString().replace(/[:.]/g,"-")}`);for(const[f,c]of changes){if(fs.existsSync(f)){const b=path.join(backup,path.relative(root,f));fs.mkdirSync(path.dirname(b),{recursive:true});fs.copyFileSync(f,b)}fs.mkdirSync(path.dirname(f),{recursive:true});const t=`${f}.${crypto.randomUUID()}.tmp`;fs.writeFileSync(t,c,"utf8");fs.renameSync(t,f)}}for(const f of[files.product,files.comparison,files.hub])parse(fs.readFileSync(f,"utf8"),path.relative(root,f));console.log(`[${PATCH}] ${changes.length?`${changes.length} Datei(en) installiert; Backup: ${backup}`:"Zielzustand bereits vorhanden (no-op)."}`);
