#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
const PATCH="pfotentechnik-search-evidence-opportunity-33.6.0";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const app=path.join(root,"apps/pfotentechnik");
const target=path.join(app,"scripts/product-evidence/research-queue.mjs");
const testFile=path.join(app,"test/product-evidence-search-opportunity-33.6.0.test.mjs");
if(!fs.existsSync(target)) throw new Error(`[${PATCH}] Erwartete Datei fehlt: ${path.relative(root,target)}`);
const stamp=new Date().toISOString().replace(/[:.]/g,"-");
const backup=path.join(root,".patch-backups",`${PATCH}-${stamp}`);
const backupTarget=path.join(backup,path.relative(root,target));
fs.mkdirSync(path.dirname(backupTarget),{recursive:true}); fs.copyFileSync(target,backupTarget);
console.log(`[${PATCH}] Backup: ${path.relative(root,backup)}`);
const queue=String.raw`#!/usr/bin/env node
import fs from "node:fs"; import path from "node:path"; import {fileURLToPath} from "node:url";
const app=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../.."), productDir=path.join(app,"src/content/products"), out=path.join(app,"reports/product-evidence"), seoDir=path.join(app,"src/data/seo"); fs.mkdirSync(out,{recursive:true});
const arg=k=>process.argv.find(x=>x.startsWith(k+"="))?.split("=")[1]; const limit=Math.max(1,Number(arg("--limit"))||10), primaryKey=arg("--range")||"28d", contextKey=arg("--context")||"3m";
const read=f=>{try{return JSON.parse(fs.readFileSync(f,"utf8"))}catch{return null}}; let dashboard=null,sourceFile=""; for(const n of ["search-dashboard-ranges.json","gsc-dashboard-ranges.json","search-dashboard.json","gsc-dashboard.json"]){const d=read(path.join(seoDir,n));if(d){dashboard=d;sourceFile=n;break}}
const range=k=>dashboard?.ranges?.[k]||(((dashboard?.key||dashboard?.range)===k)?dashboard:null), primary=range(primaryKey), context=range(contextKey);
const norm=v=>{try{const u=new URL(String(v).startsWith("http")?v:`https://pfotentechnik.de/${String(v||"").replace(/^\\/+/,"")}`);return (u.pathname.replace(/\\/+/g,"/").replace(/\\/+$/,"")||"")+"/"}catch{return "/"}}; const num=v=>Number.isFinite(Number(v))?Number(v):0;
const field=(raw,k)=>raw.match(new RegExp(`^${k}:\\\\s*["']?([^"'\\\\n]+)`,"m"))?.[1]?.trim()||"";
const ev=raw=>({hasExternal:/^externalEvidence:\\s*$/m.test(raw),professional:(raw.match(/^\\s*-\\s+publisher:/gm)||[]).length,userSources:(raw.match(/^\\s*-\\s+platform:/gm)||[]).length,consensus:(raw.match(/^\\s+finding:/gm)||[]).length});
const search=(r,slug)=>{if(!r)return{page:null,pq:[]};const p=`/produkt/${slug}/`;return{page:(r.pages||[]).filter(x=>norm(x.page)===p).sort((a,b)=>num(b.impressions)-num(a.impressions))[0]||null,pq:(r.pageQueries||[]).filter(x=>norm(x.page)===p).sort((a,b)=>num(b.impressions)-num(a.impressions))}};
const rankScore=(p,i)=>!i||!p?0:p>=6&&p<=15?30:p>15&&p<=25?Math.round(30-(p-15)*1.2):p<6?18:p<=40?Math.max(5,Math.round(18-(p-25)*.8)):3; const bench=p=>p<=3?8:p<=5?5:p<=10?3:p<=20?1.5:1;
let products=fs.readdirSync(productDir).filter(n=>/\\.mdx?$/i.test(n)).map(name=>{const raw=fs.readFileSync(path.join(productDir,name),"utf8"),slug=field(raw,"slug")||name.replace(/\\.mdx?$/i,""),title=field(raw,"title")||slug,evidence=ev(raw),a=search(primary,slug),c=search(context,slug),page=a.page||{},impressions=num(page.impressions)||a.pq.reduce((s,x)=>s+num(x.impressions),0),clicks=num(page.clicks)||a.pq.reduce((s,x)=>s+num(x.clicks),0),position=num(page.position)||(a.pq.length?a.pq.reduce((s,x)=>s+num(x.position)*Math.max(1,num(x.impressions)),0)/a.pq.reduce((s,x)=>s+Math.max(1,num(x.impressions)),0):0),ctr=impressions?clicks/impressions*100:num(page.ctr);return{file:`src/content/products/${name}`,slug,title,rating:num(field(raw,"rating")),recommendationStatus:field(raw,"recommendationStatus"),evidence,search:{impressions,clicks,position,ctr,queries:a.pq.slice(0,8),contextImpressions:num(c.page?.impressions)||c.pq.reduce((s,x)=>s+num(x.impressions),0)}}});
const maxImp=Math.max(1,...products.map(x=>x.search.impressions)); for(const p of products){const s=p.search,missing=[!p.evidence.professional,!p.evidence.userSources,!p.evidence.consensus].filter(Boolean).length;const score={ranking:rankScore(s.position,s.impressions),impressions:s.impressions?Math.round(20*Math.log1p(s.impressions)/Math.log1p(maxImp)):0,ctrPotential:s.impressions?Math.round(15*Math.max(0,1-s.ctr/bench(s.position||30))):0,queryMatch:s.queries.length?Math.min(15,8+Math.min(7,s.queries.length)):0,evidenceGap:Math.round(15*missing/3),commercial:(p.recommendationStatus==="recommended"?3:1)+(p.rating>=80||p.rating>=4?2:0)};score.total=Object.values(score).reduce((a,b)=>a+b,0);p.score=score;p.searchSignal=s.impressions>0||s.contextImpressions>0} products.sort((a,b)=>b.score.total-a.score.total||b.search.impressions-a.search.impressions||b.rating-a.rating);
const generatedAt=new Date().toISOString(),source={dashboardFile:sourceFile||null,primaryRange:primaryKey,primaryAvailable:!!primary,contextRange:contextKey,contextAvailable:!!context},weights={ranking:30,impressions:20,ctrPotential:15,pageQueryMatch:15,evidenceGap:15,commercialRelevance:5}; fs.writeFileSync(path.join(out,"search-opportunity.json"),JSON.stringify({generatedAt,source,weights,products},null,2)+"\\n");
fs.writeFileSync(path.join(out,"search-opportunity.md"),["# Search × Evidence Opportunity","",`- Search-Quelle: ${sourceFile||"keine"}`,`- Primär: ${primaryKey}${primary?"":" (nicht verfügbar)"}`,`- Kontext: ${contextKey}${context?"":" (nicht verfügbar)"}`,"","| # | Produkt | Score | Impr. | Klicks | Pos. | Evidence-Gap |","| ---: | --- | ---: | ---: | ---: | ---: | ---: |",...products.map((p,i)=>`| ${i+1} | ${p.title.replace(/\\|/g,"\\\\|")} | ${p.score.total} | ${p.search.impressions} | ${p.search.clicks} | ${p.search.position?p.search.position.toFixed(1):"–"} | ${p.score.evidenceGap}/15 |`)].join("\\n")+"\\n");
const selected=products.slice(0,limit),rules=["Keine eigenen Tests behaupten.","Externe Tests mit Publisher, URL, Datum und Methodik getrennt erfassen.","Nutzerbewertungen pro Plattform getrennt erfassen.","Sterne verschiedener Plattformen nicht mitteln.","Konsens nur bei wiederkehrenden Mustern aus mehreren Quellen.","Search-Signale priorisieren Recherche, ersetzen aber keine Evidenzprüfung."]; fs.writeFileSync(path.join(out,"research-queue.json"),JSON.stringify({generatedAt,source,rules,products:selected},null,2)+"\\n");
fs.writeFileSync(path.join(out,"research-queue.md"),["# Research Queue: externe Produktevidenz","",`Priorisiert mit ${primaryKey}-Search-Signalen und ${contextKey} als Kontext. Quelle: ${sourceFile||"keine Search-Daten gefunden"}.`,"",...selected.flatMap((p,i)=>[`## ${i+1}. ${p.title}`,`- Slug: ${p.slug}`,`- Datei: ${p.file}`,`- Opportunity-Score: ${p.score.total}/100`,`- Search: ${p.search.impressions} Impressionen · ${p.search.clicks} Klicks · Position ${p.search.position?p.search.position.toFixed(1):"–"}`,`- Evidence-Gap: ${p.score.evidenceGap}/15 · Professional ${p.evidence.professional} · Nutzerquellen ${p.evidence.userSources} · Konsens ${p.evidence.consensus}`,p.search.queries.length?`- Relevante Queries: ${p.search.queries.slice(0,5).map(q=>`${q.query} (${num(q.impressions)} Impr., Pos. ${num(q.position).toFixed(1)})`).join("; ")}`:"- Relevante Queries: noch kein PageQuery-Signal","- Auftrag: fehlende unabhängige professionelle Reviews und belastbare Nutzerquellen recherchieren; wiederkehrende Muster belegen.",""])].join("\\n")+"\\n"); console.log(`Research Queue: ${selected.length} Produkte · Search-Quelle: ${sourceFile||"keine"} · Range: ${primaryKey}`); console.log(`Opportunity Report: reports/product-evidence/search-opportunity.md`);
`;
const test=String.raw`import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";const s=fs.readFileSync(new URL("../scripts/product-evidence/research-queue.mjs",import.meta.url),"utf8");test("Cockpit-Daten",()=>{assert.match(s,/search-dashboard-ranges\\.json/);assert.match(s,/gsc-dashboard-ranges\\.json/);assert.doesNotMatch(s,/csv-parse|readCSV|gsc-import/i)});test("28d plus 3m",()=>{assert.match(s,/primaryKey.*28d/);assert.match(s,/contextKey.*3m/)});test("PageQueries und Produktpfad",()=>{assert.match(s,/pageQueries/);assert.match(s,/produkt\\/\\$\\{slug\\}/)});test("Scoring",()=>{for(const k of ["ranking","impressions","ctrPotential","queryMatch","evidenceGap","commercial"])assert.match(s,new RegExp(k))});test("Reports",()=>{for(const f of ["search-opportunity.json","search-opportunity.md","research-queue.json","research-queue.md"])assert.ok(s.includes(f))});`;
try{fs.writeFileSync(target,queue);fs.writeFileSync(testFile,test);console.log(`[${PATCH}] Geschrieben: ${path.relative(root,target)}`);console.log(`[${PATCH}] Geschrieben: ${path.relative(root,testFile)}`);for(const [label,args] of [["Syntax",["--check",target]],["Regressionstest",["--test",testFile]],["Opportunity Queue",[target,"--limit=30"]]]){console.log(`[${PATCH}] Prüfe: ${label}`);const r=spawnSync(process.execPath,args,{cwd:root,stdio:"inherit"});if(r.status!==0)throw new Error(`${label} fehlgeschlagen (Exit ${r.status})`);console.log(`[${PATCH}] BESTANDEN: ${label}`)}console.log(`[${PATCH}] Abgeschlossen.`)}catch(e){try{fs.copyFileSync(backupTarget,target);if(fs.existsSync(testFile))fs.rmSync(testFile)}catch{}console.error(`[${PATCH}] FEHLER: ${e.message}`);console.error(`[${PATCH}] Änderungen wurden zurückgerollt.`);process.exit(1)}
