#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const PATCH = "pfotentechnik-external-evidence-batch-4-33.8.2";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const app = path.join(root, "apps", "pfotentechnik");
const productDir = path.join(app, "src", "content", "products");
const testFile = path.join(app, "test", "external-evidence-batch-4-33.8.2.test.mjs");
const audit = path.join(app, "scripts", "product-evidence", "audit.mjs");
const queue = path.join(app, "scripts", "product-evidence", "research-queue.mjs");

const blocks = {
  "petkit-yumshare-solo-2": `externalEvidence:\n  professionalReviews: []\n  userReviews: []\n  consensus:\n    strengths: []\n    weaknesses: []\n    editorialAssessment: >-\n      Für das konkrete Modell YumShare Solo 2 ist die unabhängige, modellgenaue Review-Lage zum Prüfzeitpunkt noch zu dünn.\n      Bewertungen und Tests des älteren YumShare Solo werden nicht auf Solo 2 übertragen.\n  note: >-\n    Evidence-Gap bewusst dokumentiert. Externe Bewertungen des Vorgängers werden nicht als Solo-2-Evidenz verwendet.\n`,
  "petlibro-polar-wet-food-feeder": `externalEvidence:\n  professionalReviews:\n    - publisher: "Reviewed"\n      title: "Petlibro Polar Wet Food Feeder Review"\n      url: "https://www.reviewed.com/pets/content/petlibro-polar-wet-food-feeder-high-tech-mealtime"\n      publishedAt: "2024-07-23"\n      checkedAt: "2026-08-10"\n      methodology: "hands-on"\n      positives:\n        - "Einrichtung und Bedienung wurden im Praxistest als unkompliziert beschrieben."\n        - "Die aktive Kühlung löst das zentrale Frischeproblem von Nassfutter ohne wechselnde Kühlakkus."\n      negatives:\n        - "Das Gerät benötigt relativ viel Stellfläche."\n        - "Es bietet nur wenige vorbereitete Mahlzeiten."\n      findings:\n        - "Reviewed bewertete das Gerät im realen Einsatz mit Nassfutter."\n    - publisher: "Cats.com"\n      title: "Petlibro Polar Wet Food Feeder Review"\n      url: "https://cats.com/petlibro-polar-wet-food-feeder-review"\n      checkedAt: "2026-08-10"\n      methodology: "hands-on"\n      positives:\n        - "Mehrwöchiger Einsatz mit Katzen bestätigte den praktischen Nutzen für geplante Nassfuttermahlzeiten."\n      negatives:\n        - "Reinigung und Preis wurden schwächer bewertet als der Kernnutzen."\n      findings:\n        - "Cats.com testete den Polar über mehrere Wochen."\n  userReviews:\n    - platform: "Chewy"\n      url: "https://www.chewy.com/petlibro-polar-automatic-smart-dog/product-reviews/1311726"\n      checkedAt: "2026-08-10"\n      rating: 3.9\n      scale: 5\n      reviewCount: 153\n      recurringPositives:\n        - "Kühlung und geplante frische Mahlzeiten werden häufig als Hauptnutzen genannt."\n      recurringCriticism:\n        - "Einzelne Berichte nennen Probleme mit Kühlung oder Software."\n  consensus:\n    strengths:\n      - finding: "Aktive Kühlung ist der klar belegte Kernvorteil gegenüber einfachen Kühlakku-Lösungen."\n        sourceCount: 3\n        confidence: "high"\n    weaknesses:\n      - finding: "Platzbedarf und begrenzte Mahlzeitenzahl schränken die Flexibilität ein."\n        sourceCount: 2\n        confidence: "medium"\n    editorialAssessment: >-\n      Die unabhängigen Praxistests stützen den Kernnutzen der aktiven Kühlung deutlich.\n  note: >-\n    Externe Ratings bleiben von der redaktionellen PfotenTechnik-Bewertung getrennt.\n`,
  "petkit-eversweet-ultra": `externalEvidence:\n  professionalReviews: []\n  userReviews:\n    - platform: "Chewy"\n      url: "https://www.chewy.com/petkit-ever-sweet-ultra-automatic/product-reviews/4452958"\n      checkedAt: "2026-08-10"\n      rating: 4.3\n      scale: 5\n      reviewCount: 4\n      recurringPositives:\n        - "Reinigungskonzept und reduzierte Filterwartung werden positiv hervorgehoben."\n      recurringCriticism:\n        - "Die kleine Stichprobe enthält Kritik an App-Abhängigkeit und Bedienung."\n  consensus:\n    strengths: []\n    weaknesses: []\n    editorialAssessment: >-\n      Die vorhandene Nutzerstichprobe ist zu klein für belastbaren Konsens.\n  note: >-\n    Teil-Evidenz. Zum Prüfzeitpunkt liegt keine ausreichend belastbare unabhängige Hands-on-Review des konkreten Modells vor.\n`,
  "petlibro-stainless-steel-fountain": `externalEvidence:\n  professionalReviews:\n    - publisher: "Cat Food Dispensers Reviews"\n      title: "Petlibro Stainless Steel Cat Water Fountain Review"\n      url: "https://www.catfooddispensersreviews.com/petlibro-stainless-steel-cat-water-fountain-review/"\n      checkedAt: "2026-08-10"\n      methodology: "hands-on"\n      positives:\n        - "Stabile Edelstahlkonstruktion und kompakte Größe wurden positiv bewertet."\n      negatives:\n        - "Pumpe und Kunststoffteile bleiben wartungsrelevant."\n      findings:\n        - "Der Review beschreibt Material, Aufbau und Nutzung im Alltag."\n  userReviews:\n    - platform: "Chewy"\n      url: "https://www.chewy.com/petlibro-stainless-steel-dog-cat/product-reviews/1391262"\n      checkedAt: "2026-08-10"\n      rating: 4.0\n      scale: 5\n      reviewCount: 2388\n      recurringPositives:\n        - "Leiser Betrieb, Edelstahloberfläche und gute Akzeptanz werden häufig genannt."\n      recurringCriticism:\n        - "Pumpenausfälle und schwer zugängliche Reinigungsbereiche werden wiederholt kritisiert."\n  consensus:\n    strengths:\n      - finding: "Edelstahl-Trinkfläche, leiser Betrieb und gute Tierakzeptanz sind die am besten gestützten Stärken."\n        sourceCount: 2\n        confidence: "high"\n    weaknesses:\n      - finding: "Pumpe und kleinere Kunststoffkomponenten bleiben die wichtigsten Wartungsrisiken."\n        sourceCount: 2\n        confidence: "medium"\n    editorialAssessment: >-\n      Die große Nutzerbasis stützt die positiven Alltagssignale, zeigt aber ein relevantes Pumpenrisiko.\n`,
  "petkit-eversweet-max-cordless": `externalEvidence:\n  professionalReviews:\n    - publisher: "WIRED"\n      title: "My Cat's Favorite Pet Fountain Is on Sale Right Now"\n      url: "https://www.wired.com/story/petkit-eversweet-max-prime-big-deal-day-deal"\n      publishedAt: "2025-10-08"\n      checkedAt: "2026-08-10"\n      methodology: "hands-on"\n      positives:\n        - "Kabelloser Betrieb, Edelstahl-Trinkfläche und App-Protokollierung werden positiv hervorgehoben."\n      negatives:\n        - "Der Wasserstand wird in der App nicht direkt angezeigt."\n      findings:\n        - "WIRED beschreibt den Eversweet Max als im eigenen Haushalt getesteten Brunnen."\n  userReviews:\n    - platform: "Chewy"\n      url: "https://www.chewy.com/petkit-eversweet-max-stainless-steel/product-reviews/1351358"\n      checkedAt: "2026-08-10"\n      rating: 4.4\n      scale: 5\n      reviewCount: 32\n      recurringPositives:\n        - "Leiser Betrieb und einfache Reinigung werden wiederholt gelobt."\n      recurringCriticism:\n        - "Einrichtung, App-Verbindung und Sensoranzeigen bereiten einzelnen Nutzern Probleme."\n  consensus:\n    strengths:\n      - finding: "Sehr leiser Betrieb und flexible kabellose Aufstellung gehören zu den am besten gestützten Vorteilen."\n        sourceCount: 2\n        confidence: "high"\n    weaknesses:\n      - finding: "App-Einrichtung und Sensorik können im Einzelfall erklärungsbedürftig sein."\n        sourceCount: 1\n        confidence: "medium"\n    editorialAssessment: >-\n      Hands-on-Eindruck und Nutzerfeedback passen beim leisen Betrieb und der flexiblen Aufstellung gut zusammen.\n`,
  "cat-mate-c500": `externalEvidence:\n  professionalReviews:\n    - publisher: "Cats.com"\n      title: "Cat Mate C500 Automatic Pet Feeder Review"\n      url: "https://cats.com/cat-mate-c500-automatic-pet-feeder-review"\n      checkedAt: "2026-08-10"\n      methodology: "hands-on"\n      positives:\n        - "Mehrwöchiger Test bestätigt die einfache Grundfunktion für zeitgesteuerte Mahlzeiten."\n      negatives:\n        - "Kühlakkus sind nur eine zeitlich begrenzte Kühlhilfe und keine aktive Kühlung."\n      findings:\n        - "Cats.com testete den C500 über mehrere Wochen mit Katzen."\n  userReviews:\n    - platform: "Chewy"\n      url: "https://www.chewy.com/cat-mate-c500-digital-5-meal/product-reviews/154555"\n      checkedAt: "2026-08-10"\n      rating: 4.0\n      scale: 5\n      reviewCount: 407\n      recurringPositives:\n        - "Einfache Zeitsteuerung und Eignung für Nassfutter werden häufig positiv bewertet."\n      recurringCriticism:\n        - "Einzelne Nutzer berichten von blockierten oder nicht korrekt weiterdrehenden Schalen."\n  consensus:\n    strengths:\n      - finding: "Der C500 ist eine einfache Lösung für mehrere zeitversetzte Mahlzeiten ohne App-Abhängigkeit."\n        sourceCount: 2\n        confidence: "high"\n    weaknesses:\n      - finding: "Die Kühlung durch Akkus ist begrenzt und ersetzt keine aktive Kühlung."\n        sourceCount: 2\n        confidence: "high"\n    editorialAssessment: >-\n      Der C500 punktet mit Einfachheit und Nassfuttertauglichkeit, bleibt bei Kühlung technisch simpel.\n`,
  "oneisall-2-in-1-feeder-water": `externalEvidence:\n  professionalReviews:\n    - publisher: "WIRED"\n      title: "These 11 Automatic Cat Feeders Were the Best We Tested in 2026"\n      url: "https://www.wired.com/gallery/best-automatic-cat-feeders/"\n      checkedAt: "2026-08-10"\n      methodology: "hands-on"\n      positives:\n        - "WIRED beschreibt das Modell nach eigenem Test als einfach, zuverlässig und preiswert."\n      negatives:\n        - "Futter und Wasser stehen konstruktionsbedingt sehr nah beieinander."\n      findings:\n        - "Das Gerät eignet sich laut WIRED vor allem als einfache, platzsparende Lösung."\n  userReviews: []\n  consensus:\n    strengths: []\n    weaknesses: []\n    editorialAssessment: >-\n      Der unabhängige WIRED-Test ist belastbar, eine ausreichend große unabhängige Nutzerbasis fehlt noch.\n  note: >-\n    Teil-Evidenz. Herstellerangaben werden nur als Spezifikation genutzt, nicht als unabhängige Bewertung.\n`,
  "surefeed-microchip-pet-feeder-connect": `externalEvidence:\n  professionalReviews:\n    - publisher: "Expert Reviews"\n      title: "SureFeed Microchip Pet Feeder Connect review"\n      url: "https://www.expertreviews.co.uk/archived/surefeed-microchip-pet-feeder-connect-review"\n      publishedAt: "2019-05-30"\n      checkedAt: "2026-08-10"\n      methodology: "hands-on"\n      positives:\n        - "Futtermenge und Fressverhalten lassen sich pro Tier nachvollziehen."\n      negatives:\n        - "Angewöhnung kann dauern und die Kosten steigen im Mehrtierhaushalt."\n      findings:\n        - "Der Review bewertet die Connect-Funktionen einschließlich Waage, Hub und App."\n    - publisher: "Tech Advisor"\n      title: "Sure Petcare Microchip Pet Feeder review"\n      url: "https://www.techadvisor.com/article/720358/sure-petcare-microchip-pet-feeder-review.html"\n      checkedAt: "2026-08-10"\n      methodology: "hands-on"\n      positives:\n        - "Mikrochip-Zugang verhindert im Test Futterdiebstahl zwischen Katzen."\n      negatives:\n        - "Für Connect-Funktionen ist ein zusätzlicher Hub nötig."\n      findings:\n        - "Der Test erfolgte im Mehrkatzen-Haushalt."\n  userReviews:\n    - platform: "Zooplus UK"\n      url: "https://www.zooplus.co.uk/feedback/shop/cats/cat_bowls_feeders/feeders/programmable/761816"\n      checkedAt: "2026-08-10"\n      rating: 3.2\n      scale: 5\n      reviewCount: 10\n      recurringPositives:\n        - "Selektive Fütterung und App-Protokollierung werden bei funktionierenden Geräten gelobt."\n      recurringCriticism:\n        - "Mehrere Berichte nennen Defekte an Öffnungsmechanik oder Batteriekontakten."\n  consensus:\n    strengths:\n      - finding: "Selektiver Mikrochip-Zugang und individuelle Futterprotokollierung lösen reale Mehrtierprobleme."\n        sourceCount: 3\n        confidence: "high"\n    weaknesses:\n      - finding: "Preis, Hub-Abhängigkeit und Zusatzkosten sind klare Nachteile."\n        sourceCount: 3\n        confidence: "high"\n    editorialAssessment: >-\n      Die professionellen Tests stützen die Kernfunktion deutlich; Haltbarkeitsberichte werden vorsichtig gewichtet.\n`,
  "petlibro-dockstream-rfid-smart": `externalEvidence:\n  professionalReviews:\n    - publisher: "WIRED"\n      title: "The 21 Best Early Amazon Pet Day Deals"\n      url: "https://www.wired.com/story/amazon-pet-day-deals"\n      publishedAt: "2025-05-09"\n      checkedAt: "2026-08-10"\n      methodology: "editorial-review"\n      positives:\n        - "RFID ermöglicht individuelle Trinkprotokolle in Mehrkatzenhaushalten."\n      negatives:\n        - "Für die individuelle Zuordnung muss die Katze den RFID-Anhänger tragen."\n      findings:\n        - "WIRED ordnet die RFID-Version als besonders interessant für Monitoringbedarf ein."\n  userReviews:\n    - platform: "Chewy"\n      url: "https://www.chewy.com/petlibro-dockstream-rfid-smart/product-reviews/1311742"\n      checkedAt: "2026-08-10"\n      rating: 3.5\n      scale: 5\n      reviewCount: 33\n      recurringPositives:\n        - "Sehr leiser Betrieb und individuelles Monitoring werden positiv hervorgehoben."\n      recurringCriticism:\n        - "Einzelne Nutzer berichten von Zuverlässigkeits- oder Erkennungsproblemen."\n  consensus:\n    strengths:\n      - finding: "Individuelles RFID-Trinktracking ist der klare Mehrwert gegenüber normalen Smart-Fountains."\n        sourceCount: 2\n        confidence: "high"\n    weaknesses:\n      - finding: "Das System ist vom RFID-Anhänger und korrekter Erkennung abhängig."\n        sourceCount: 1\n        confidence: "medium"\n    editorialAssessment: >-\n      Das Monitoring-Konzept ist stark; Zuverlässigkeit und Tag-Akzeptanz bleiben wichtige Prüfpunkte.\n`,
  "petsafe-freshfeed-refrigerated-feeder": `externalEvidence:\n  professionalReviews: []\n  userReviews:\n    - platform: "Chewy"\n      url: "https://www.chewy.com/petsafe-freshfeed-refrigerated-dog/product-reviews/3967438"\n      checkedAt: "2026-08-10"\n      rating: 4.5\n      scale: 5\n      reviewCount: 31\n      recurringPositives:\n        - "Aktive Kühlung, App-Einrichtung und planbare Mahlzeiten werden häufig positiv beschrieben."\n      recurringCriticism:\n        - "Viele Rezensionen stammen aus kostenlos bereitgestellten Produkttests und sind vorsichtig zu gewichten."\n        - "Hohe Bauform und schmale Näpfe können für manche Katzen unpassend sein."\n  consensus:\n    strengths: []\n    weaknesses: []\n    editorialAssessment: >-\n      Die frühe Nutzerbasis ist überwiegend positiv, enthält aber viele incentivierte Bewertungen. Ohne unabhängigen Praxistest wird noch kein Mehrquellen-Konsens abgeleitet.\n  note: >-\n    Teil-Evidenz. Die Nutzerquelle wird wegen des hohen Anteils kostenlos bereitgestellter Testprodukte vorsichtig gewichtet.\n`
};

const stamp = new Date().toISOString().replace(/[:.]/g, "-");
const backup = path.join(root, ".patch-backups", `${PATCH}-${stamp}`);
fs.mkdirSync(backup, { recursive: true });
const changed = [];
const skipped = [];

const insertBlock = (raw, block, slug) => {
  if (/^externalEvidence:\s*$/m.test(raw)) return null;
  for (const rx of [/^decision:\s*$/m, /^review:\s*$/m, /^strengths:\s*$/m]) {
    const match = raw.match(rx);
    if (match && match.index !== undefined) return raw.slice(0, match.index) + block + raw.slice(match.index);
  }
  throw new Error(`Kein sicherer Einfügeanker für ${slug} gefunden.`);
};

try {
  for (const [slug, block] of Object.entries(blocks)) {
    const file = path.join(productDir, `${slug}.md`);
    if (!fs.existsSync(file)) throw new Error(`Produktdatei fehlt: ${path.relative(root, file)}`);
    const raw = fs.readFileSync(file, "utf8");
    if (/^externalEvidence:\s*$/m.test(raw)) { skipped.push(slug); continue; }
    const backupFile = path.join(backup, path.relative(root, file));
    fs.mkdirSync(path.dirname(backupFile), { recursive: true });
    fs.copyFileSync(file, backupFile);
    fs.writeFileSync(file, insertBlock(raw, block, slug), "utf8");
    changed.push(slug);
    console.log(`[${PATCH}] Evidence ergänzt: ${slug}`);
  }

  const targetList = Object.keys(blocks);
  const test = `import assert from "node:assert/strict";\nimport fs from "node:fs";\nimport path from "node:path";\nimport test from "node:test";\nimport { fileURLToPath } from "node:url";\nconst app=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");\nconst targets=${JSON.stringify(targetList)};\nconst read=s=>fs.readFileSync(path.join(app,"src/content/products",s+".md"),"utf8");\n\ntest("Batch 4 enthält externalEvidence für alle zehn Zielprodukte",()=>{for(const slug of targets) assert.match(read(slug),/^externalEvidence:\\s*$/m,slug);});\ntest("bestehende PfotenTechnik-Ratings werden nicht ersetzt",()=>{for(const slug of targets) assert.match(read(slug),/^rating:\\s*[0-9.]+/m,slug);});\ntest("keine PfotenTechnik-Hands-on-Behauptung wird erzeugt",()=>{for(const slug of targets) assert.doesNotMatch(read(slug),/PfotenTechnik[^\\n]{0,80}hands-on|von PfotenTechnik getestet/i,slug);});\ntest("bewusste Evidence-Gaps bleiben transparent",()=>{assert.match(read("petkit-yumshare-solo-2"),/Evidence-Gap bewusst dokumentiert/);assert.match(read("petkit-eversweet-ultra"),/Teil-Evidenz/);assert.match(read("oneisall-2-in-1-feeder-water"),/Teil-Evidenz/);assert.match(read("petsafe-freshfeed-refrigerated-feeder"),/Teil-Evidenz/);});\ntest("starke Quellen sind modellbezogen hinterlegt",()=>{assert.ok(read("petlibro-polar-wet-food-feeder").includes("reviewed.com/pets/content/petlibro-polar"));assert.ok(read("cat-mate-c500").includes("cats.com/cat-mate-c500"));assert.ok(read("surefeed-microchip-pet-feeder-connect").includes("expertreviews.co.uk"));assert.ok(read("petlibro-dockstream-rfid-smart").includes("wired.com/story/amazon-pet-day-deals"));});\n`;
  fs.writeFileSync(testFile, test, "utf8");

  const syntax = spawnSync(process.execPath, ["--check", testFile], { cwd: root, stdio: "inherit" });
  if (syntax.status !== 0) throw new Error(`Generierter Test ist syntaktisch ungültig (Exit ${syntax.status})`);

  for (const [label, args] of [
    ["Batch-Test", ["--test", testFile]],
    ["Product-Evidence-Audit", [audit]],
    ["Research-Queue", [queue, "--limit=30"]]
  ]) {
    console.log(`[${PATCH}] Prüfe: ${label}`);
    const result = spawnSync(process.execPath, args, { cwd: root, stdio: "inherit" });
    if (result.status !== 0) throw new Error(`${label} fehlgeschlagen (Exit ${result.status})`);
    console.log(`[${PATCH}] BESTANDEN: ${label}`);
  }

  console.log(`[${PATCH}] Abgeschlossen. Geändert: ${changed.length}, übersprungen: ${skipped.length}`);
  console.log(`[${PATCH}] Backup: ${path.relative(root, backup)}`);
} catch (error) {
  for (const slug of changed) {
    const file = path.join(productDir, `${slug}.md`);
    const backupFile = path.join(backup, path.relative(root, file));
    if (fs.existsSync(backupFile)) fs.copyFileSync(backupFile, file);
  }
  if (fs.existsSync(testFile)) fs.rmSync(testFile);
  console.error(`[${PATCH}] FEHLER: ${error instanceof Error ? error.message : String(error)}`);
  console.error(`[${PATCH}] Änderungen wurden zurückgerollt.`);
  process.exit(1);
}
