export type ProductAvailability = "available" | "temporarily-unavailable" | "out-of-stock" | "discontinued" | "unknown";
export type PriceState = "available" | "unknown" | "removed" | "stale";
export type RecommendationStatus = "recommended" | "limited" | "archived";
export type EditorialStatus = "complete" | "recommended" | "required" | "archived";
export type MaintenanceStatus = "complete" | "recommended" | "required" | "archived";

export type ProductOperations = {
  current: number | null;
  currency: string;
  formattedPrice: string | null;
  priceUpdated?: string;
  priceAgeDays: number | null;
  priceAvailable: boolean;
  priceState: PriceState;
  affiliateAvailable: boolean;
  affiliateUrl: string | null;
  availability: ProductAvailability;
  availabilityLabel: string;
  availabilityReason?: string;
  availabilityUpdated?: string;
  editorialStatus: EditorialStatus;
  recommendationStatus: RecommendationStatus;
  maintenanceStatus: MaintenanceStatus;
  maintenanceLabel: string;
  recommendationLabel: string;
  warnings: string[];
  missingRequiredFields: string[];
  consciouslyUnavailable: boolean;
  archived: boolean;
  isArchive: boolean;
  isTask: boolean;
  priorityRank: number;
  purchasable: boolean;
  autoRecommendationEligible: boolean;
};

export const AVAILABILITY_VALUES: readonly ProductAvailability[];
export const PRICE_STATE_VALUES: readonly PriceState[];
export const RECOMMENDATION_STATUS_VALUES: readonly RecommendationStatus[];
export const EDITORIAL_STATUS_VALUES: readonly EditorialStatus[];
export const MAINTENANCE_STATUS_VALUES: readonly MaintenanceStatus[];
export const AVAILABILITY_LABELS: Readonly<Record<ProductAvailability, string>>;
export const STATUS_LABELS: Readonly<Record<string, string>>;

export function parseLocalizedPrice(value: unknown): number | null;
export function formatPrice(value: unknown, currency?: string): string | null;
export function ageInDays(value: unknown, now?: number): number | null;
export function isConsciouslyUnavailable(availability: unknown): boolean;
export function isArchivedAvailability(availability: unknown): boolean;
export function isPurchasable(productOrOperations: any): boolean;
export function isAutoRecommendationEligible(productOrOperations: any): boolean;
export function availabilityFromOffer(value: unknown): ProductAvailability | null;
export function inferInitialAvailability(data: any, now?: number): ProductAvailability;
export function requiredFieldIssues(data: any): string[];
export function deriveProductOperations(data: any, options?: { now?: Date | number }): ProductOperations;
export function operationFieldsFrom(data: any, options?: { now?: Date | number }): Record<string, unknown>;
export function recommendationTieBreaker(data: any): number;
export function compareMaintenanceRows(left: any, right: any): number;
export function buildOperationsDashboard(rows: any[]): Record<string, number>;
export function toOperationsRecord(data: any, options?: { now?: Date | number }): any;
export function createKeyedSerialExecutor(): <T>(key: string, task: () => Promise<T> | T) => Promise<T>;
export function createInFlightDeduper(): <T>(key: string, task: () => Promise<T> | T) => Promise<T>;
