import fs from 'node:fs';import path from 'node:path';import {execFileSync} from 'node:child_process';
const repo=process.cwd(),out=repo+'/reports/editorial-leakage-35.3',app=repo+'/apps/pfotentechnik';
const {createRequire}=await import('node:module');const yaml=createRequire(app+'/package.json')('js-yaml');const parseFrontmatter=s=>({data:yaml.load(s.match(/^---\r?\n([\s\S]*?)\r?\n---/)[1])});
const before=JSON.parse(fs.readFileSync(out+'/before.json')),after=JSON.parse(fs.readFileSync(out+'/after.json'));
const base='9a5722c54599cc94f53477baed112f0ffb7bc0b1';const fields=['title','slug','seo','seoTitle','seoDescription','rating','ratings','score','price','affiliate','affiliateUrl','offers','productUrl','publishedAt','updatedAt','recommendation','decision','strengths','weaknesses','evidenceSources'];
const exceptions=[];let files=0,products=0;
for(const collection of ['pages','products','comparisons','manufacturers'])for(const file of fs.readdirSync(app+'/src/content/'+collection).filter(f=>f.endsWith('.md'))){const p='apps/pfotentechnik/src/content/'+collection+'/'+file;const old=parseFrontmatter(execFileSync('git',['show',base+':'+p],{encoding:'utf8'})).data,now=parseFrontmatter(fs.readFileSync(repo+'/'+p,'utf8')).data;files++;if(collection==='products')products++;for(const field of fields)if(JSON.stringify(old[field])!==JSON.stringify(now[field]))exceptions.push({source:p,field,before:old[field],after:now[field]});}
const linkChanges=[];for(const b of before.pages){const a=after.pages.find(p=>p.url===b.url);const tally=xs=>xs.reduce((o,x)=>(o[x]=(o[x]??0)+1,o),{});const l=tally(b.links.map(x=>x.split('#')[0])),r=tally(a.links.map(x=>x.split('#')[0]));const changes=Object.keys({...l,...r}).filter(k=>l[k]!==r[k]).map(url=>({url,before:l[url]??0,after:r[url]??0}));if(changes.length||JSON.stringify(b.links.map(x=>x.split('#')[0]))!==JSON.stringify(a.links.map(x=>x.split('#')[0])))linkChanges.push({url:b.url,changes,reason:changes.length?'Required public description cleanup changes existing text-derived contextual link selection; no destination or ranking configuration edited.':'Same destinations and counts; automatically selected link order changed.'});}
const select=(p,kind)=>p.surfaces.filter(s=>s.surface==='PUBLIC_METADATA'&&s.location===kind).map(s=>s.text);
const metaChanges=before.pages.flatMap(b=>{const a=after.pages.find(p=>p.url===b.url);return ['body:title','description','og:title','og:description','twitter:title','twitter:description'].filter(k=>JSON.stringify(select(b,k))!==JSON.stringify(select(a,k))).map(k=>({url:b.url,kind:k,before:select(b,k),after:select(a,k)}));});
const sitemapNow=fs.readFileSync(app+'/dist/sitemap-0.xml','utf8');
const prior=JSON.parse(fs.readFileSync(repo+'/reports/google-signal-integrity-35.2.1/postfix/audit.json'));
const final=JSON.parse(fs.readFileSync(out+'/signals/audit.json'));
const schemaBefore=JSON.parse(fs.readFileSync(repo+'/reports/google-signal-integrity-35.2.1/postfix/product-visible-evidence.json'));
const schemaAfter=JSON.parse(fs.readFileSync(out+'/signals/product-visible-evidence.json'));
const schemaRatings=schemaAfter.map(p=>({url:p.url,before:JSON.stringify(schemaBefore.find(b=>b.url===p.url)?.schemas.filter(s=>s['@type']==='Review').map(s=>s.reviewRating)),after:JSON.stringify(p.schemas.filter(s=>s['@type']==='Review').map(s=>s.reviewRating))}));
const result={baseCommit:base,contentFilesChecked:files,productsChecked:products,protectedFieldExceptions:exceptions,publicMetadataChanges:metaChanges,contextualLinkChanges:linkChanges,canonicalUnchanged:before.pages.every(b=>JSON.stringify(b.canonical)===JSON.stringify(after.pages.find(a=>a.url===b.url).canonical)),robotsUnchanged:before.pages.every(b=>JSON.stringify(b.robots)===JSON.stringify(after.pages.find(a=>a.url===b.url).robots)),legacyFragmentsPreserved:before.pages.every(b=>b.ids.every(id=>after.pages.find(a=>a.url===b.url).ids.includes(id))),schemaRatingChanges:schemaRatings.filter(x=>x.before!==x.after),signalsBefore:prior.summary,signalsAfter:final.summary,sitemapEntries:[...sitemapNow.matchAll(/<url>([\s\S]*?)<\/url>/g)].map(m=>m[1]),redirectsUnchanged:execFileSync('git',['show',base+':apps/pfotentechnik/public/_redirects'],{encoding:'utf8'})===fs.readFileSync(app+'/public/_redirects','utf8')};
fs.writeFileSync(out+'/validation/invariants.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({...result,sitemapEntries:result.sitemapEntries.length,signalsBefore:undefined,signalsAfter:undefined},null,2));
