#!/usr/bin/env node
import fs from "node:fs";import path from "node:path";import {fileURLToPath} from "node:url";
const repoRoot=process.cwd(),installerRoot=path.dirname(fileURLToPath(import.meta.url)),backupRoot=path.join(repoRoot,`.advisor-2.1-backup-${new Date().toISOString().replace(/[:.]/g,"-")}`),manifestPath=path.join(repoRoot,".advisor-2.1-manifest.json");
const payloadFiles=["apps/pfotentechnik/src/components/advisor/FeederAdvisor.astro","apps/pfotentechnik/src/components/AdvisorCta.astro","apps/pfotentechnik/src/pages/berater/futterautomat.astro"],homepage="apps/pfotentechnik/src/pages/index.astro",comparison="apps/pfotentechnik/src/pages/vergleiche/[comparison].astro";
const abs=r=>path.join(repoRoot,r);function backup(r){if(!fs.existsSync(abs(r)))return;const t=path.join(backupRoot,r);fs.mkdirSync(path.dirname(t),{recursive:true});fs.copyFileSync(abs(r),t)}
function addImport(s,line,anchor){if(s.includes(line))return s;if(s.includes(anchor))return s.replace(anchor,anchor+"\n"+line);const end=s.indexOf("\n---",3);if(end<0)throw new Error("Astro-Frontmatter nicht erkannt");return s.slice(0,end)+"\n"+line+s.slice(end)}
function restore(files){for(const r of [...files].reverse()){const b=path.join(backupRoot,r);if(fs.existsSync(b)){fs.mkdirSync(path.dirname(abs(r)),{recursive:true});fs.copyFileSync(b,abs(r))}else if(payloadFiles.includes(r)&&fs.existsSync(abs(r)))fs.rmSync(abs(r),{force:true})}}
const touched=[...payloadFiles,homepage,comparison];try{for(const r of ["package.json","apps/pfotentechnik/package.json",homepage,comparison])if(!fs.existsSync(abs(r)))throw new Error(`Im Repository-Root ausführen. Fehlend: ${r}`);
for(const r of payloadFiles){backup(r);const src=path.join(installerRoot,"files",r);fs.mkdirSync(path.dirname(abs(r)),{recursive:true});fs.copyFileSync(src,abs(r));console.log(`Installiert: ${r}`)}
backup(homepage);let h=fs.readFileSync(abs(homepage),"utf8");h=addImport(h,'import AdvisorCta from "../components/AdvisorCta.astro";','import { buildHomepageModel } from "../domain/home/buildHomepageModel";');if(!h.includes('data-advisor-integration="homepage"')){const m='  <HomePage model={model} />';if(!h.includes(m))throw new Error("Homepage-Anker nicht gefunden");h=h.replace(m,m+'\n  <div data-advisor-integration="homepage" class="advisor-home-entry">\n    <AdvisorCta />\n  </div>');h+='\n<style>\n  .advisor-home-entry { width: min(1180px, calc(100% - 32px)); margin: 0 auto; }\n</style>\n'}fs.writeFileSync(abs(homepage),h);
backup(comparison);let c=fs.readFileSync(abs(comparison),"utf8");c=addImport(c,'import AdvisorCta from "../../components/AdvisorCta.astro";','import ConversionJourney from "../../components/ConversionJourney.astro";');if(!c.includes('data-advisor-integration="comparison"')){const m='    <ConversionJourney';const i=c.indexOf(m);if(i<0)throw new Error("Vergleichsseiten-Anker nicht gefunden");const ins='    <div data-advisor-integration="comparison">\n      <AdvisorCta title="Welche Geräteklasse passt zu deinen Anforderungen?" text="Beantworte fünf kurze Fragen und grenze Futterart, Steuerung, Tierzahl und Portionsbereich ein, bevor du einzelne Modelle vergleichst." />\n    </div>\n\n';c=c.slice(0,i)+ins+c.slice(i)}fs.writeFileSync(abs(comparison),c);
fs.writeFileSync(manifestPath,JSON.stringify({installedAt:new Date().toISOString(),backupRoot,files:touched},null,2)+"\n");console.log("\nAdvisor 2.1 erfolgreich installiert.\nJetzt: npm run build:pfotentechnik")}catch(e){restore(touched);console.error("Advisor-Installation fehlgeschlagen; Änderungen zurückgesetzt.");console.error(e instanceof Error?e.message:e);process.exit(1)}
