import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
const g=fs.readFileSync(path.join(process.cwd(),"src/components/product-experience-2/ProductGallery2.astro"),"utf8");
const h=fs.readFileSync(path.join(process.cwd(),"src/components/product-experience-2/ProductHero2.astro"),"utf8");
test("full bleed",()=>{assert.match(h,/data-mobile-gallery-full-bleed/);assert.match(h,/width: 100dvw/);assert.match(h,/margin-left: -50dvw/);});
test("no artificial whitespace",()=>{assert.match(g,/aspect-ratio: 1 \/ 1/);assert.match(g,/object-fit: cover/);assert.doesNotMatch(g,/height: clamp\(300px, 92vw, 460px\)/);});
test("controls overlay image",()=>{assert.match(g,/bottom: 12px/);assert.match(g,/position: absolute/);assert.match(g,/pointer-events: none/);});
test("desktop and single image remain",()=>{assert.match(g,/px2-editorial-gallery__desktop/);assert.match(g,/is-single/);});
