import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {resolveCommerceOffers,compareCommerceOffers} from '../src/domain/commerceOffers.mjs';
import {buildNetworkLink} from '../../../packages/affiliate-core/src/affiliate/networks.mjs';
import {affiliatePrograms} from '../src/config/affiliate-programs.mjs';
import {extractShopifyVariant,refreshOfficialOffer,refreshCommerceTasks} from '../src/lib/price-intelligence/commerce-refresh.mjs';
import {checkProductPrice,checkAllProductPrices} from '../src/lib/price-intelligence/service.mjs';
import {updateProductOffer,readProductDocument} from '../src/lib/price-intelligence/frontmatter-price.mjs';
import {commerceCockpitMarkup} from '../src/lib/price-intelligence/commerce-view.mjs';
const now=Date.parse('2026-09-21T12:00:00Z');
const price=(current=119.99)=>({current,currency:'EUR',status:'unknown',checkedAt:'2026-09-21T10:00:00Z'});
const official=(overrides={})=>({id:'petlibro-de',merchant:'petlibro',network:'awin',program:'petlibro-de',officialProductUrl:'https://de.petlibro.com/products/dockstream-2-smart-fountain?variant=123',mappingStatus:'verified',verifiedAt:'2026-09-21',commerceDataProvider:'shopify-product',variantId:'123',expectedSku:'PL-WF116-31W',price:price(),priceState:'available',availability:'available',evidenceSources:[{source:'PETLIBRO',url:'https://de.petlibro.com/products/dockstream-2-smart-fountain',accessedAt:'2026-09-21',assertion:'Identity verified',fields:['officialProductUrl'],sourceType:'officialStore'}],...overrides});
const product=(offers=[])=>({slug:'petlibro-example',productStatus:'active',price:price(149.99),priceState:'available',availability:'available',affiliate:{url:'https://www.amazon.de/dp/B012345678?tag=yusha0f-21'},offers});
const resolve=(data,context)=>resolveCommerceOffers(data,context,{now});
test('Amazon only retains existing affiliate target and price',()=>{const r=resolve(product());assert.equal(r.length,1);assert.equal(r[0].merchant,'amazon');assert.equal(r[0].affiliateUrl,product().affiliate.url);assert.equal(r[0].current,149.99);});

test('existing Amazon short links retain their URL and PartnerNet identity',()=>{const p=product();p.affiliate.url='https://amzn.to/3Twv3YG';const offer=resolve(p)[0];assert.equal(offer.merchant,'amazon');assert.equal(offer.network,'partnernet');assert.equal(offer.affiliateUrl,p.affiliate.url);});

test('mismatched destination variant cannot advertise another variant price',async()=>{
  const offer=official({variantId:'999'});assert.equal(resolve({offers:[offer]})[0].canLink,false);
  await assert.rejects(()=>refreshOfficialOffer(offer),/Varianten-ID/);
});
test('PETLIBRO only works without Amazon or legacy fields',()=>{const r=resolve({slug:'p',offers:[official()]});assert.equal(r.length,1);assert.ok(r[0].canLink);assert.match(r[0].affiliateUrl,/awin1/);});
test('Amazon and PETLIBRO coexist without mutating product or neutral evidence',()=>{const p={...product([official()]),evidenceSources:[{url:official().officialProductUrl}]};const before=JSON.stringify(p);assert.equal(resolve(p).length,2);assert.equal(JSON.stringify(p),before);assert.ok(!p.evidenceSources[0].url.includes('awin1'));});
test('PETLIBRO cheaper sorts only verified comparable totals, commission excluded',()=>{const offers=resolve(product([official()]));offers.forEach(o=>Object.assign(o,{comparisonKey:'same-unit',shipping:0}));const r=compareCommerceOffers(offers);assert.equal(r.cheapestId,'petlibro-de');assert.equal(r.saving,30);});
test('Amazon cheaper sorts first regardless of commission',()=>{const offers=resolve(product([official({price:price(199.99)})]));offers.forEach(o=>Object.assign(o,{comparisonKey:'same-unit',shipping:0}));assert.equal(compareCommerceOffers(offers).cheapestId,'legacy');});
test('unknown price permits verified destination with no price/savings claim',()=>{const r=resolve(product([official({price:price(null)})]));assert.ok(r[1].canLink);assert.equal(r[1].current,null);assert.equal(compareCommerceOffers(r).cheapestId,null);});
test('stale, future and failed prices are never advertised',()=>{for(const patch of [{price:{...price(),checkedAt:'2026-08-01'}},{price:{...price(),checkedAt:'2027-01-01'}},{error:'provider failed'}])assert.equal(resolve({offers:[official(patch)]})[0].current,null);});
test('variant mismatch, unknown shipping or currency excludes comparisons',()=>{const a=resolve(product([official()]));a.forEach(o=>Object.assign(o,{comparisonKey:'same',shipping:0}));for(const field of ['comparisonKey','currency','shipping']){const b=structuredClone(a);b[1][field]=field==='shipping'?null:'different';assert.equal(compareCommerceOffers(b).cheapestId,null);}});
test('unresolved/invalid and cross-domain destinations cannot become affiliate links',()=>{for(const patch of [{mappingStatus:'unresolved'},{mappingStatus:'invalid'},{officialProductUrl:'https://evil.example/products/x'},{officialProductUrl:'javascript:alert(1)'},{merchant:'tractive'}])assert.equal(resolve({offers:[official(patch)]})[0].affiliateUrl,null);});
test('Awin IDs, encoding and context are deterministic and confined to core',()=>{const url=new URL(buildNetworkLink(affiliatePrograms['petlibro-de'],official().officialProductUrl,{product:'p',placement:'product-commerce',pageType:'product'}));assert.equal(url.searchParams.get('awinmid'),'77942');assert.equal(url.searchParams.get('awinaffid'),'2987821');assert.equal(url.searchParams.get('ued'),official().officialProductUrl);assert.equal(url.searchParams.get('clickref'),'p_product-commerce_product');});
test('editorial manufacturer placement is distinct; sponsored attributes remain',()=>{const r=resolve({offers:[official()]},{placement:'editorial-manufacturer'})[0];assert.match(r.affiliateUrl,/editorial-manufacturer/);assert.equal(r.rel,'sponsored nofollow noopener');assert.equal(r.target,'_blank');});
test('ADCELL unconfigured fails closed; verified template needs no UI changes',()=>{assert.equal(buildNetworkLink(affiliatePrograms['tractive-de'],'https://tractive.com/de/p',{}),null);const program={...affiliatePrograms['tractive-de'],enabled:true,verifiedTemplate:true,linkTemplate:'https://www.adcell.de/example?verified={destination}&context={context}'};const result=resolveCommerceOffers({slug:'tractive-test',offers:[official({merchant:'tractive',network:'adcell',program:'tractive-de',commerceDataProvider:'manual',officialProductUrl:'https://tractive.com/de/p'})]}, {}, {now,programs:{'tractive-de':program}});assert.ok(result[0].canLink);assert.match(result[0].affiliateUrl,/adcell/);});
test('one failing provider does not abort another',async()=>{const calls=[];const r=await refreshCommerceTasks([{id:'amazon',provider:'html',run:async()=>{calls.push('amazon');throw Error('fail');}},{id:'petlibro',provider:'shopify',run:async()=>calls.push('petlibro')}]);assert.deepEqual(calls,['amazon','petlibro']);assert.equal(r[0].ok,false);assert.equal(r[1].ok,true);});
test('single product refresh includes legacy and all offers, persists failures',async()=>{const doc={slug:'refresh-case',file:'memory',data:product([official()])};let legacyCalls=0;const result=await checkProductPrice(doc.slug,{find:async()=>doc,checkLegacy:async()=>{legacyCalls++;},refresh:async()=>{throw Error('PETLIBRO unavailable');},persist:async(file,id,updater)=>{doc.data.offers[0]=updater(doc.data.offers[0]);}});assert.equal(legacyCalls,1);assert.equal(result.providerResults.length,2);assert.equal(result.ok,true);assert.match(result.record.commerceOffers[1].error,/unavailable/);assert.equal(result.record.commerceOffers[1].current,null);});
test('global refresh covers all configured products including manufacturer-only editorial records',async()=>{const called=[];const documents=[{slug:'a',data:product()},{slug:'b',data:{priceAutomation:'editorial',offers:[official()]}}];const r=await checkAllProductPrices({}, {listDocuments:async()=>documents,check:async slug=>{called.push(slug);return {ok:true};}});assert.deepEqual(called,['a','b']);assert.equal(r.succeeded,2);});
test('official data extraction pins SKU/variant and currency, never chooses cheapest bundle',()=>{const data={variants:[{id:123,sku:'PL-WF116-31W',price:11599,available:true},{id:999,sku:'wrong',price:999,available:true}]};assert.equal(extractShopifyVariant(data,official(),'EUR').current,115.99);assert.throws(()=>extractShopifyVariant(data,official({expectedSku:'wrong'}),'EUR'));assert.throws(()=>extractShopifyVariant(data,official(),'USD'));});
test('Shopify refresh validates redirects and supports official JS JSON format',async()=>{const fetchResource=async url=>({resolvedUrl:url,contentType:'text/javascript',buffer:Buffer.from(JSON.stringify(url.endsWith('/cart.js')?{currency:'EUR'}:{variants:[{id:123,sku:'PL-WF116-31W',price:12345,available:true}]}))});const r=await refreshOfficialOffer(official(),{fetchResource});assert.equal(r.price.current,123.45);await assert.rejects(()=>refreshOfficialOffer(official(),{fetchResource:async()=>({resolvedUrl:'https://evil.example',contentType:'application/json'})}));});
test('Cockpit exposes merchant/network/source/URL/freshness/error and escapes input',()=>{const offers=resolve(product([official({error:'<script>alert(1)</script>'})]));const html=commerceCockpitMarkup(offers,'product');assert.match(html,/PETLIBRO/);assert.match(html,/awin/);assert.match(html,/Offizielle Produkt-URL/);assert.match(html,/letzter Versuch/);assert.match(html,/data-offer-editor/);assert.ok(!html.includes('<script>'));});
test('atomic offer persistence preserves legacy fields, nested editorial YAML and body',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'pt-commerce-'));try{const file=path.join(dir,'p.md');await fs.writeFile(file,'---\nslug: p\nprice: {current: 99, currency: EUR}\naffiliate: {url: "https://www.amazon.de/dp/B012345678"}\ncomparisonData:\n  editorial:\n    score: 80\nevidenceSources: []\n---\nOriginal body\n');const before=await readProductDocument(file);await updateProductOffer(file,'petlibro-de',official());const after=await readProductDocument(file);assert.deepEqual(after.data.price,before.data.price);assert.deepEqual(after.data.affiliate,before.data.affiliate);assert.deepEqual(after.data.comparisonData,before.data.comparisonData);assert.match(await fs.readFile(file,'utf8'),/Original body/);const saved=await fs.readFile(file,'utf8');await assert.rejects(()=>updateProductOffer(file,'petlibro-de',{id:'bad'}));assert.equal(await fs.readFile(file,'utf8'),saved);}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('public commerce UI retains disclosure and contains no network-specific parameters',async()=>{const box=await fs.readFile(new URL('../src/components/product-experience-2/PriceBox2.astro',import.meta.url),'utf8');assert.match(box,/affiliate-hinweis/);assert.match(box,/data-placement/);assert.ok(!/awinmid|awinaffid|clickref|Convert-a-Link|MasterTag/.test(box));});

test('persisted legacy comparison metadata participates without mutating resolved offers',()=>{
  const p=product([official({comparisonKey:'unit-123',shipping:0})]);
  Object.assign(p.price,{comparisonKey:'unit-123',shipping:0});
  assert.equal(compareCommerceOffers(resolve(p)).cheapestId,'petlibro-de');
});

test('verified exact variant supersedes generic same-shop price while retaining legacy data',()=>{
  const p=product([official()]);p.affiliate.url='https://de.petlibro.com/products/dockstream-2-smart-fountain';
  const r=resolve(p);assert.equal(r.length,2);assert.equal(r[0].canLink,false);
  assert.equal(compareCommerceOffers(r).offers.length,1);assert.equal(p.price.current,149.99);
  p.offers[0].availability='out-of-stock';
  const empty=compareCommerceOffers(resolve(p));assert.equal(empty.offers.length,0);assert.equal(empty.hasConfiguredOffers,true);
});
