import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../../..");
const APP=path.join(ROOT,"apps","pfotentechnik");
const read=(...parts)=>fs.readFileSync(path.join(APP,...parts),"utf8");
test("Schema unterstützt Implementation Briefings",()=>{const s=read("src","lib","seo","research","schema.ts");assert.match(s,/ResearchImplementationBrief/);assert.match(s,/implementationBrief?:ResearchImplementationBrief/);assert.match(s,/acceptanceCriteria:string[]/);});
test("Research Prompt verlangt ausführbare Briefings",()=>{const s=read("src","lib","seo","research","prompt-builder.ts");assert.match(s,/IMPLEMENTIERUNGS-BRIEFING/);assert.match(s,/implementationBrief/);assert.match(s,/Akzeptanzkriterien/);});
test("Growth erzeugt kopierbaren Entwickler-Prompt",()=>{const s=read("src","lib","seo","research","growth.ts");assert.match(s,/buildImplementationBrief/);assert.match(s,/buildResearchImplementationPrompt/);assert.match(s,/konfliktarmen, wiederholbaren Installer-Patch/);});
test("Workbench zeigt Briefing und Kopierbutton",()=>{const s=read("src","components","admin","ResearchWorkbench.astro");assert.match(s,/Umsetzungsauftrag kopieren/);assert.match(s,/data-copy-implementation-prompt/);assert.match(s,/Konkret umsetzen/);assert.match(s,/Fertig, wenn/);assert.match(s,/Nicht ändern/);});
