#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const ID='pfotentechnik-topical-authority-center-1.0.0';
const MARKER=`Generated by ${ID}`;
const force=process.argv.includes('--force');
const check=process.argv.includes('--check');
const here=path.dirname(fileURLToPath(import.meta.url));
const payload=path.join(here,'topical-authority-center-payload');

function findRoot(start){
  let current=path.resolve(start);
  while(true){
    if(fs.existsSync(path.join(current,'apps/pfotentechnik'))&&fs.existsSync(path.join(current,'package.json')))return current;
    const parent=path.dirname(current);
    if(parent===current)throw new Error('Repository-Root nicht gefunden. Starte innerhalb von affiliate-template.');
    current=parent;
  }
}
const repo=findRoot(process.cwd());
const app=path.join(repo,'apps/pfotentechnik');
const backup=path.join(repo,'.patch-backups',`${ID}-${new Date().toISOString().replace(/[:.]/g,'-')}`);
const targets={
  layout:path.join(app,'src/layouts/SeoAdminLayout.astro'),
  pkg:path.join(app,'package.json'),
  loader:path.join(app,'src/lib/seo/topical-authority/loadTopicalAuthority.ts'),
  page:path.join(app,'src/pages/admin/seo/topical-authority.astro'),
  audit:path.join(app,'scripts/seo/audit-topical-authority.mjs'),
  test:path.join(app,'test/topical-authority-center.test.mjs'),
};
const sources={
  loader:path.join(payload,'loadTopicalAuthority.ts'),
  page:path.join(payload,'topical-authority.astro'),
  audit:path.join(payload,'audit-topical-authority.mjs'),
  test:path.join(payload,'topical-authority-center.test.mjs'),
};
const fail=(message)=>{console.error(`\n[${ID}] FEHLER: ${message}`);process.exit(1)};
const read=(file)=>fs.existsSync(file)?fs.readFileSync(file,'utf8'):fail(`Pflichtdatei fehlt: ${path.relative(repo,file)}`);
function backupFile(file){if(!fs.existsSync(file)||check)return;const out=path.join(backup,path.relative(repo,file));fs.mkdirSync(path.dirname(out),{recursive:true});fs.copyFileSync(file,out)}
function ensureOwned(file){if(!fs.existsSync(file))return;const current=fs.readFileSync(file,'utf8');if(current.includes(MARKER)||force)return;fail(`Konflikt: ${path.relative(repo,file)} existiert bereits und gehört nicht zu ${ID}. Prüfe die Datei oder nutze bewusst --force.`)}
for(const file of Object.values(sources))if(!fs.existsSync(file))fail(`Payload fehlt: ${file}`);

let layout=read(targets.layout);
if(!layout.includes('"topical-authority"')){
  const match=layout.match(/active\?:\s*([^;]+);/);
  if(!match)fail('active-Typ in SeoAdminLayout.astro nicht erkannt.');
  layout=layout.replace(match[0],`active?: ${match[1].trim()} | "topical-authority";`);
}
if(!layout.includes('/admin/seo/topical-authority/')){
  const anchor='["advisor", "/admin/seo/advisor/", "Co-Pilot"],';
  if(!layout.includes(anchor))fail('Navigationsanker Co-Pilot nicht gefunden.');
  layout=layout.replace(anchor,`${anchor}\n  ["topical-authority", "/admin/seo/topical-authority/", "Topical Authority"],`);
}
const pkg=JSON.parse(read(targets.pkg));
pkg.scripts ||= {};
pkg.scripts['audit:topical-authority']='node scripts/seo/audit-topical-authority.mjs';
pkg.scripts['audit:topical-authority:strict']='node scripts/seo/audit-topical-authority.mjs --strict';
pkg.scripts['test:topical-authority']='node --test test/topical-authority-center.test.mjs';
const packageText=JSON.stringify(pkg,null,2)+'\n';

for(const file of [targets.loader,targets.page,targets.audit,targets.test])ensureOwned(file);
const plan=[
  [targets.layout,layout],
  [targets.pkg,packageText],
  [targets.loader,read(sources.loader)],
  [targets.page,read(sources.page)],
  [targets.audit,read(sources.audit)],
  [targets.test,read(sources.test)],
];
console.log(`[${ID}] Vorprüfung`);
console.log(`Repository: ${repo}`);
console.log(`Modus: ${check?'Check':force?'Force':'Sicher'}\n`);
for(const [file,content] of plan){const old=fs.existsSync(file)?fs.readFileSync(file,'utf8'):null;console.log(`${old===content?'Unverändert':old===null?'Neu':'Geändert'}: ${path.relative(repo,file)}`)}
if(check){console.log('\nKeine Dateien geschrieben (--check).');process.exit(0)}
for(const [file] of plan)backupFile(file);
for(const [file,content] of plan){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,content,'utf8')}
fs.chmodSync(targets.audit,0o755);
fs.mkdirSync(backup,{recursive:true});
fs.writeFileSync(path.join(backup,'manifest.json'),JSON.stringify({patch:ID,installedAt:new Date().toISOString(),files:plan.map(([file])=>path.relative(repo,file))},null,2)+'\n');
console.log(`\n[${ID}] Installation abgeschlossen.`);
console.log(`Backup: ${path.relative(repo,backup)}`);
console.log('\nJetzt ausführen:');
console.log('npm --workspace apps/pfotentechnik run test:topical-authority');
console.log('npm --workspace apps/pfotentechnik run audit:topical-authority:strict');
console.log('npm --workspace apps/pfotentechnik run build');
console.log('\nSeite: /admin/seo/topical-authority/');
