#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const PATCH_ID = "pfotentechnik-topical-authority-cluster-detection-fix-1.1.1";
const FORCE = process.argv.includes("--force");

function findRepoRoot(startDir) {
  let current = path.resolve(startDir);
  while (true) {
    if (
      fs.existsSync(path.join(current, "apps", "pfotentechnik")) &&
      fs.existsSync(path.join(current, "package.json"))
    ) return current;
    const parent = path.dirname(current);
    if (parent === current) break;
    current = parent;
  }
  throw new Error("Repository-Root nicht gefunden.");
}

function fail(message) {
  console.error(`[${PATCH_ID}] FEHLER: ${message}`);
  process.exit(1);
}

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const sourceFile = path.join(scriptDir, "loadTopicalAuthority.1.1.1.ts");
if (!fs.existsSync(sourceFile)) fail(`Patch-Datei fehlt: ${sourceFile}`);

const repoRoot = findRepoRoot(process.cwd());
const target = path.join(
  repoRoot,
  "apps",
  "pfotentechnik",
  "src",
  "lib",
  "seo",
  "topical-authority",
  "loadTopicalAuthority.ts"
);

if (!fs.existsSync(target)) fail(`Zieldatei fehlt: ${path.relative(repoRoot, target)}`);

const before = fs.readFileSync(target, "utf8");
const source = fs.readFileSync(sourceFile, "utf8");

const recognized =
  before.includes("Generated by pfotentechnik-topical-authority-center-1.0.0") ||
  before.includes("Generated by pfotentechnik-topical-authority-cluster-detection-fix-1.1.1") ||
  before.includes("export function loadTopicalAuthority") &&
  before.includes("CLUSTER_DEFINITIONS");

if (!recognized && !FORCE) {
  fail(
    "Die Loader-Datei wurde nicht sicher als Topical-Authority-Datei erkannt. " +
    "Nach manueller Prüfung kann --force verwendet werden."
  );
}

if (before === source) {
  console.log(`[${PATCH_ID}] Bereits installiert.`);
  process.exit(0);
}

const backupRoot = path.join(
  repoRoot,
  ".patch-backups",
  `${PATCH_ID}-${new Date().toISOString().replace(/[:.]/g, "-")}`
);
const backupFile = path.join(backupRoot, path.relative(repoRoot, target));
fs.mkdirSync(path.dirname(backupFile), { recursive: true });
fs.copyFileSync(target, backupFile);
fs.writeFileSync(target, source, "utf8");

console.log(`[${PATCH_ID}] Ersetzt: ${path.relative(repoRoot, target)}`);
console.log(`[${PATCH_ID}] Backup: ${path.relative(repoRoot, backupRoot)}`);
console.log("");
console.log("Die Cluster-Erkennung nutzt jetzt:");
console.log("- exakte Slug- und Titelanker");
console.log("- doppelte Signale für Beschreibung und Body");
console.log("- Ausschlussregeln zwischen Kategorien");
console.log("- keine pauschale Hersteller-Zuordnung");
console.log("- Score 0 bei vollständig fehlenden Clustern");
console.log("");
console.log("Jetzt ausführen:");
console.log("npm --workspace apps/pfotentechnik run test:topical-authority");
console.log("npm --workspace apps/pfotentechnik run audit:topical-authority:strict");
console.log("npm --workspace apps/pfotentechnik run build");
