// Generated by pfotentechnik-topical-authority-cluster-detection-fix-1.1.1
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export type TopicalDocumentType = "page" | "comparison" | "product" | "manufacturer";
export type AuthorityStatus = "strong" | "developing" | "gap";

export type TopicalDocument = {
  type: TopicalDocumentType;
  slug: string;
  title: string;
  description: string;
  filePath: string;
  route: string;
  body: string;
  raw: string;
  links: string[];
  manufacturer?: string;
};

export type TopicalCluster = {
  id: string;
  label: string;
  description: string;
  status: AuthorityStatus;
  score: number;
  counts: {
    pages: number;
    comparisons: number;
    products: number;
    manufacturers: number;
    total: number;
  };
  coverage: {
    hub: boolean;
    guides: boolean;
    comparisons: boolean;
    products: boolean;
    manufacturers: boolean;
    journey: boolean;
  };
  linkCoverage: number;
  documents: Array<Pick<TopicalDocument, "type" | "slug" | "title" | "route" | "filePath">>;
  gaps: string[];
  nextAction: string;
  priority: "high" | "medium" | "low";
};

export type TopicalOpportunity = {
  id: string;
  title: string;
  cluster: string;
  priority: "high" | "medium" | "low";
  impact: number;
  effort: "niedrig" | "mittel" | "hoch";
  reason: string;
  action: string;
  kind: "build" | "expand" | "consolidate" | "link" | "validate";
};

export type TopicalAuthorityData = {
  generatedAt: string;
  authorityScore: number;
  summary: {
    documents: number;
    clusters: number;
    strong: number;
    developing: number;
    gaps: number;
    orphanCandidates: number;
    opportunities: number;
  };
  clusters: TopicalCluster[];
  opportunities: TopicalOpportunity[];
  orphanCandidates: TopicalDocument[];
  inventory: Record<TopicalDocumentType, number>;
};

type ClusterDefinition = {
  id: string;
  label: string;
  description: string;
  slugPatterns: readonly RegExp[];
  titlePatterns: readonly RegExp[];
  descriptionPatterns: readonly RegExp[];
  bodyPatterns: readonly RegExp[];
  excludePatterns: readonly RegExp[];
  hubPatterns: readonly RegExp[];
  thresholds: {
    pages: number;
    comparisons: number;
    products: number;
    manufacturers: number;
  };
  strategy: "build" | "expand" | "consolidate" | "validate";
};

const APP_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../../..");
const CONTENT_ROOT = path.join(APP_ROOT, "src", "content");

const CLUSTER_DEFINITIONS: readonly ClusterDefinition[] = [
  {
    id: "futterautomaten",
    label: "Futterautomaten",
    description: "Automatische Fütterung, Portionierung, Nassfutter, App und besondere Nutzungssituationen.",
    slugPatterns: [/futterautomat/i, /futterspender/i],
    titlePatterns: [/futterautomat/i, /futterspender/i, /automatische fütterung/i],
    descriptionPatterns: [/futterautomat/i, /automatische fütterung/i, /portionierung/i],
    bodyPatterns: [/futterautomat/i, /futterausgabe/i, /portionierung/i],
    excludePatterns: [/trinkbrunnen/i, /gps-tracker/i, /katzenklappe/i, /katzentoilette/i],
    hubPatterns: [/^futterautomat(?:en)?$/i, /smarte-futterautomaten/i],
    thresholds: { pages: 6, comparisons: 4, products: 8, manufacturers: 0 },
    strategy: "consolidate",
  },
  {
    id: "trinkbrunnen",
    label: "Trinkbrunnen",
    description: "Trinkverhalten, Hygiene, Filter, Materialien und Trinkbrunnen für Hunde und Katzen.",
    slugPatterns: [/trinkbrunnen/i, /katzentrinkbrunnen/i],
    titlePatterns: [/trinkbrunnen/i, /wasserbrunnen/i],
    descriptionPatterns: [/trinkbrunnen/i, /wasserbrunnen/i],
    bodyPatterns: [/trinkbrunnen/i, /brunnenfilter/i, /wasserfontäne/i],
    excludePatterns: [/futterautomat/i, /gps-tracker/i, /katzenklappe/i, /katzentoilette/i],
    hubPatterns: [/^trinkbrunnen$/i, /^katzentrinkbrunnen$/i],
    thresholds: { pages: 6, comparisons: 2, products: 6, manufacturers: 0 },
    strategy: "expand",
  },
  {
    id: "gps-tracker",
    label: "GPS-Tracker",
    description: "Ortung, Reichweite, Akkulaufzeit, Abos, Datenschutz und Nutzung mit Hund oder Katze.",
    slugPatterns: [/gps-tracker/i, /gps-halsband/i, /bluetooth-tag/i, /geofence/i, /ortung/i],
    titlePatterns: [/gps-tracker/i, /gps halsband/i, /bluetooth-tag/i, /ortung/i],
    descriptionPatterns: [/gps-tracker/i, /gps-ortung/i, /live-ortung/i, /geofence/i],
    bodyPatterns: [/gps-ortung/i, /live-ortung/i, /geofence/i, /mobilfunknetz/i],
    excludePatterns: [/futterautomat/i, /trinkbrunnen/i, /katzenklappe/i, /katzentoilette/i],
    hubPatterns: [/^gps-tracker$/i, /gps-tracker-fuer-hunde-und-katzen/i],
    thresholds: { pages: 6, comparisons: 3, products: 6, manufacturers: 0 },
    strategy: "expand",
  },
  {
    id: "katzenklappen",
    label: "Katzenklappen",
    description: "Mikrochip-, App- und selektive Katzenklappen inklusive Einbau und Mehrkatzenhaushalt.",
    slugPatterns: [/katzenklappe/i, /mikrochip-katzenklappe/i, /microchip-cat-flap/i],
    titlePatterns: [/katzenklappe/i, /mikrochipklappe/i, /microchip cat flap/i],
    descriptionPatterns: [/katzenklappe/i, /mikrochipklappe/i, /selektiver zugang/i],
    bodyPatterns: [/katzenklappe/i, /mikrochipklappe/i, /selektiver zugang/i],
    excludePatterns: [/futterautomat/i, /trinkbrunnen/i, /gps-tracker/i, /katzentoilette/i],
    hubPatterns: [/^katzenklappen?$/i, /smarte-katzenklappen/i],
    thresholds: { pages: 4, comparisons: 2, products: 4, manufacturers: 0 },
    strategy: "build",
  },
  {
    id: "haustierkameras",
    label: "Haustierkameras",
    description: "Kameras zur Beobachtung, Kommunikation und Aktivitätskontrolle von Haustieren.",
    slugPatterns: [/haustierkamera/i, /tierkamera/i, /pet-camera/i],
    titlePatterns: [/haustierkamera/i, /tierkamera/i, /pet camera/i],
    descriptionPatterns: [/haustierkamera/i, /tierkamera/i, /pet camera/i],
    bodyPatterns: [/haustierkamera/i, /tierkamera/i, /zwei-wege-audio/i],
    excludePatterns: [/futterautomat/i, /trinkbrunnen/i, /gps-tracker/i, /katzenklappe/i, /katzentoilette/i],
    hubPatterns: [/^haustierkameras?$/i],
    thresholds: { pages: 3, comparisons: 1, products: 5, manufacturers: 0 },
    strategy: "validate",
  },
  {
    id: "katzentoiletten",
    label: "Automatische Katzentoiletten",
    description: "Selbstreinigung, Hygiene, Sicherheit und laufende Kosten.",
    slugPatterns: [/katzentoilette/i, /katzenklo/i, /litter-robot/i, /selbstreinigende-katzentoilette/i],
    titlePatterns: [/katzentoilette/i, /katzenklo/i, /litter robot/i, /selbstreinigende katzentoilette/i],
    descriptionPatterns: [/katzentoilette/i, /automatisches katzenklo/i, /litter robot/i],
    bodyPatterns: [/selbstreinigende katzentoilette/i, /automatisches katzenklo/i, /litter robot/i],
    excludePatterns: [/futterautomat/i, /trinkbrunnen/i, /gps-tracker/i, /katzenklappe/i],
    hubPatterns: [/automatische-katzentoiletten/i, /^katzentoiletten$/i],
    thresholds: { pages: 3, comparisons: 1, products: 5, manufacturers: 0 },
    strategy: "validate",
  },
];

function walkMarkdown(directory: string): string[] {
  if (!fs.existsSync(directory)) return [];
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const absolute = path.join(directory, entry.name);
    if (entry.isDirectory()) return walkMarkdown(absolute);
    return /\.mdx?$/i.test(entry.name) ? [absolute] : [];
  });
}

function cleanScalar(value: string): string | boolean | number {
  const trimmed = value.trim().replace(/^["']|["']$/g, "");
  if (trimmed === "true") return true;
  if (trimmed === "false") return false;
  if (/^-?\d+(?:\.\d+)?$/.test(trimmed)) return Number(trimmed);
  return trimmed;
}

function readFrontmatter(raw: string): Record<string, unknown> {
  const match = raw.match(/^---\s*\n([\s\S]*?)\n---/);
  if (!match) return {};
  const data: Record<string, unknown> = {};
  for (const line of match[1].split(/\r?\n/)) {
    const field = line.match(/^([A-Za-z][\w-]*):\s*(.*)$/);
    if (!field || !field[2].trim()) continue;
    data[field[1]] = cleanScalar(field[2]);
  }
  return data;
}

function extractLinks(raw: string): string[] {
  const values = new Set<string>();
  for (const match of raw.matchAll(/\]\((\/?[^)\s#]+)(?:#[^)]+)?\)/g)) values.add(match[1]);
  for (const match of raw.matchAll(/href=["'](\/[^"'#?]+)[^"']*["']/g)) values.add(match[1]);
  return [...values];
}

function routeFor(type: TopicalDocumentType, slug: string): string {
  if (type === "comparison") return `/vergleiche/${slug}/`;
  if (type === "product") return `/produkt/${slug}/`;
  if (type === "manufacturer") return `/hersteller/${slug}/`;
  return `/${slug}/`;
}

function loadCollection(type: TopicalDocumentType, directory: string): TopicalDocument[] {
  return walkMarkdown(directory).map((filePath) => {
    const raw = fs.readFileSync(filePath, "utf8");
    const frontmatter = readFrontmatter(raw);
    const slug = path.basename(filePath).replace(/\.mdx?$/i, "");
    return {
      type,
      slug,
      title: String(frontmatter.title || frontmatter.name || slug.replace(/-/g, " ")),
      description: String(frontmatter.description || frontmatter.excerpt || ""),
      manufacturer: String(frontmatter.manufacturer || frontmatter.brand || ""),
      filePath: path.relative(APP_ROOT, filePath).split(path.sep).join("/"),
      route: routeFor(type, slug),
      body: raw.replace(/^---\s*\n[\s\S]*?\n---/, "").trim(),
      raw,
      links: extractLinks(raw),
    };
  });
}

function normalize(value: string | undefined): string {
  return String(value || "").toLocaleLowerCase("de-DE");
}

function matchesAny(value: string, patterns: readonly RegExp[]): boolean {
  return patterns.some((pattern) => pattern.test(value));
}

function belongsToCluster(document: TopicalDocument, definition: ClusterDefinition): boolean {
  const slug = normalize(document.slug);
  const title = normalize(document.title);
  const description = normalize(document.description);
  const body = normalize(document.body);
  const primary = `${slug} ${title} ${description}`;

  const slugMatch = matchesAny(slug, definition.slugPatterns);
  const titleMatch = matchesAny(title, definition.titlePatterns);
  const descriptionMatch = matchesAny(description, definition.descriptionPatterns);
  const bodyMatch = matchesAny(body, definition.bodyPatterns);
  const excluded = matchesAny(primary, definition.excludePatterns);

  if (excluded) return false;
  if (slugMatch || titleMatch) return true;

  if (document.type === "manufacturer") return false;
  if (document.type === "product") return descriptionMatch && bodyMatch;

  return descriptionMatch && bodyMatch;
}

function round(value: number): number {
  return Math.round(Math.max(0, Math.min(100, value)));
}

function ratio(actual: number, target: number): number {
  if (target <= 0) return 1;
  return Math.min(1, actual / target);
}

function normalizeRoute(value: string): string {
  const route = value.startsWith("/") ? value : `/${value}`;
  return route.endsWith("/") ? route : `${route}/`;
}

function calculateLinkCoverage(documents: TopicalDocument[]): number {
  if (documents.length <= 1) return 0;
  const routes = new Set(documents.map((document) => document.route));
  const linked = documents.filter((document) =>
    document.links.some((link) => routes.has(normalizeRoute(link)) && normalizeRoute(link) !== document.route)
  ).length;
  return round((linked / documents.length) * 100);
}

function buildCluster(definition: ClusterDefinition, documents: TopicalDocument[]): TopicalCluster {
  const members = documents.filter((document) => belongsToCluster(document, definition));
  const counts = {
    pages: members.filter((item) => item.type === "page").length,
    comparisons: members.filter((item) => item.type === "comparison").length,
    products: members.filter((item) => item.type === "product").length,
    manufacturers: members.filter((item) => item.type === "manufacturer").length,
    total: members.length,
  };

  const hub = members.some(
    (item) => item.type === "page" && definition.hubPatterns.some((pattern) => pattern.test(item.slug))
  );
  const guides = counts.pages >= definition.thresholds.pages;
  const comparisons = counts.comparisons >= definition.thresholds.comparisons;
  const products = counts.products >= definition.thresholds.products;
  const manufacturers = definition.thresholds.manufacturers <= 0
    ? true
    : counts.manufacturers >= definition.thresholds.manufacturers;
  const linkCoverage = calculateLinkCoverage(members);
  const journey = hub && comparisons && products && linkCoverage >= 55;

  const score = members.length === 0
    ? 0
    : round(
        (hub ? 20 : 0)
        + ratio(counts.pages, definition.thresholds.pages) * 20
        + ratio(counts.comparisons, definition.thresholds.comparisons) * 22
        + ratio(counts.products, definition.thresholds.products) * 22
        + (linkCoverage / 100) * 16
      );

  const gaps = [
    !hub ? "Cornerstone-Hub fehlt" : "",
    !guides ? `Ratgeberabdeckung zu gering (${counts.pages}/${definition.thresholds.pages})` : "",
    !comparisons ? `Vergleichsabdeckung zu gering (${counts.comparisons}/${definition.thresholds.comparisons})` : "",
    !products ? `Produktabdeckung zu gering (${counts.products}/${definition.thresholds.products})` : "",
    members.length > 1 && linkCoverage < 55 ? `Interne Cluster-Verlinkung nur ${linkCoverage} %` : "",
  ].filter(Boolean);

  const status: AuthorityStatus = score >= 78 ? "strong" : score >= 42 ? "developing" : "gap";
  const priority = definition.id === "katzenklappen" && score < 65
    ? "high"
    : status === "strong" ? "low" : "medium";

  const nextActions = {
    build: "Hub, zwei kaufnahe Vergleiche und unterstützende Ratgeber als geschlossene Journey aufbauen.",
    expand: "Fehlende Kaufintentionen ergänzen und vorhandene Wissensseiten mit passenden Vergleichen verbinden.",
    consolidate: "Intent-Überschneidungen prüfen, Zielseiten schärfen und die Journey konsolidieren.",
    validate: "Nur nach Sicherheits-, Produkt-, Quellen- und Affiliate-Prüfung als Expansion freigeben.",
  } as const;

  return {
    id: definition.id,
    label: definition.label,
    description: definition.description,
    status,
    score,
    counts,
    coverage: { hub, guides, comparisons, products, manufacturers, journey },
    linkCoverage,
    documents: members
      .map(({ type, slug, title, route, filePath }) => ({ type, slug, title, route, filePath }))
      .sort((a, b) => a.type.localeCompare(b.type) || a.title.localeCompare(b.title, "de")),
    gaps,
    nextAction: nextActions[definition.strategy],
    priority,
  };
}

function buildOpportunities(clusters: TopicalCluster[]): TopicalOpportunity[] {
  const byId = new Map(clusters.map((cluster) => [cluster.id, cluster]));
  const result: TopicalOpportunity[] = [];
  const add = (item: TopicalOpportunity) => result.push(item);

  const cats = byId.get("katzenklappen");
  if (cats && cats.score < 65) {
    add({
      id: "ta-katzenklappen-core",
      title: "Katzenklappen als nächsten Kerncluster aufbauen",
      cluster: cats.label,
      priority: "high",
      impact: 96,
      effort: "hoch",
      reason: "Die Kategorie passt zur Positionierung, ist aber deutlich schwächer als die bestehenden Kerncluster.",
      action: "Cornerstone, Mikrochip-Vergleich, App-Vergleich und differenzierte Praxisratgeber planen.",
      kind: "build",
    });
  }

  const feeder = byId.get("futterautomaten");
  if (feeder && feeder.counts.total >= 20) {
    add({
      id: "ta-futterautomaten-consolidate",
      title: "Futterautomaten konsolidieren statt weiter verbreitern",
      cluster: feeder.label,
      priority: "high",
      impact: 91,
      effort: "mittel",
      reason: "Der Cluster ist breit genug, dass weitere ähnliche Seiten Intent-Überschneidungen erhöhen können.",
      action: "Intent-Matrix erstellen und Ratgeber → Vergleich → Produkt konsequent ausrichten.",
      kind: "consolidate",
    });
  }

  for (const cluster of clusters.filter((item) => item.documents.length > 2 && item.linkCoverage < 55)) {
    add({
      id: `ta-link-${cluster.id}`,
      title: `Interne Journey für ${cluster.label} schließen`,
      cluster: cluster.label,
      priority: cluster.priority === "high" ? "high" : "medium",
      impact: Math.max(60, 85 - cluster.linkCoverage),
      effort: "mittel",
      reason: `Nur ${cluster.linkCoverage} % der erkannten Dokumente verlinken innerhalb des eigenen Clusters.`,
      action: "Hub, Ratgeber, Vergleiche und Produkte mit entscheidungsorientierten Links verbinden.",
      kind: "link",
    });
  }

  for (const id of ["haustierkameras", "katzentoiletten"]) {
    const cluster = byId.get(id);
    if (cluster && cluster.score < 35) {
      add({
        id: `ta-validate-${id}`,
        title: `${cluster.label} als Expansion validieren`,
        cluster: cluster.label,
        priority: "low",
        impact: id === "haustierkameras" ? 70 : 62,
        effort: "hoch",
        reason: "Der Cluster fehlt weitgehend und sollte nicht ohne Markt-, Produkt- und Quellenprüfung produziert werden.",
        action: "Nachfrage, Produktbestand, Primärquellen, Sicherheitsrisiken und Affiliate-Eignung prüfen.",
        kind: "validate",
      });
    }
  }

  return result.sort(
    (a, b) =>
      ({ high: 3, medium: 2, low: 1 }[b.priority] - { high: 3, medium: 2, low: 1 }[a.priority])
      || b.impact - a.impact
  );
}

function detectOrphans(documents: TopicalDocument[]): TopicalDocument[] {
  const inbound = new Map(documents.map((document) => [document.route, 0]));
  for (const document of documents) {
    for (const link of document.links) {
      const route = normalizeRoute(link);
      if (inbound.has(route) && route !== document.route) {
        inbound.set(route, (inbound.get(route) || 0) + 1);
      }
    }
  }
  return documents
    .filter((document) => document.type !== "manufacturer")
    .filter((document) => (inbound.get(document.route) || 0) === 0)
    .sort((a, b) => a.type.localeCompare(b.type) || a.title.localeCompare(b.title, "de"))
    .slice(0, 50);
}

export function loadTopicalAuthority(): TopicalAuthorityData {
  const documents = [
    ...loadCollection("page", path.join(CONTENT_ROOT, "pages")),
    ...loadCollection("comparison", path.join(CONTENT_ROOT, "comparisons")),
    ...loadCollection("product", path.join(CONTENT_ROOT, "products")),
    ...loadCollection("manufacturer", path.join(CONTENT_ROOT, "manufacturers")),
  ];

  const clusters = CLUSTER_DEFINITIONS
    .map((definition) => buildCluster(definition, documents))
    .sort((a, b) => b.score - a.score || a.label.localeCompare(b.label, "de"));
  const opportunities = buildOpportunities(clusters);
  const orphanCandidates = detectOrphans(documents);
  const activeClusters = clusters.filter((cluster) => cluster.counts.total > 0 || cluster.id === "katzenklappen");
  const authorityScore = round(
    activeClusters.reduce((sum, cluster) => sum + cluster.score, 0) / Math.max(1, activeClusters.length)
  );

  return {
    generatedAt: new Date().toISOString(),
    authorityScore,
    summary: {
      documents: documents.length,
      clusters: clusters.length,
      strong: clusters.filter((cluster) => cluster.status === "strong").length,
      developing: clusters.filter((cluster) => cluster.status === "developing").length,
      gaps: clusters.filter((cluster) => cluster.status === "gap").length,
      orphanCandidates: orphanCandidates.length,
      opportunities: opportunities.length,
    },
    clusters,
    opportunities,
    orphanCandidates,
    inventory: {
      page: documents.filter((document) => document.type === "page").length,
      comparison: documents.filter((document) => document.type === "comparison").length,
      product: documents.filter((document) => document.type === "product").length,
      manufacturer: documents.filter((document) => document.type === "manufacturer").length,
    },
  };
}
